### PR TITLE
docs: Fix RFC3339 example

### PR DESCRIPTION
**Pull request by x0b**
#### What is the purpose of this change?

Fix example timestamp in filtering docs.

#### Was the change discussed in an issue or in the forum before?

Ref: https://forum.rclone.org/t/max-age-min-age-rfc3339-format-rejected/22204

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [ ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by x0b** [comment]
Closing in favour of #5013

**Comment by edwardxml** [comment]
Sorry, didn't mean to crash with your PR. I do fully credit you with spotting the error.

**Comment by cdnstatic** [comment]
No problem

**Comment by x0b** [comment]
No problem.

**Pull request closed without merging**
