### PR TITLE
azblob: support azure workload identity authentication

### PR DESCRIPTION
**Pull request by tareqhs**
#### What is the purpose of this change?

Allow using azure workload identity authentication for azblob backend. Available through the standard environment authentication chain when azblob's `env_auth` is set to `true`.

#### Was the change discussed in an issue or in the forum before?

No.

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ ] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Review by ncw — COMMENTED** [review]
So it is just upgrade the deps to fix?

Is this worth a note in the docs in the authentication section? https://github.com/rclone/rclone/blob/master/docs/content/azureblob.md

**Comment by tareqhs** [comment]
@ncw it is not really a fix. this is a new feature in the azure sdk (and azure cloud in general). sure, i will add doc asap.

**Review by ncw — APPROVED** [review]
Super job - thank you. I'll merge now.

**Comment by ncw** [comment]
Thank you!

PS Meant to squash merge but clicked the rebase button by accident :-( Oh well!

**Comment by hegdemahendra** [comment]
Hi @tareksha @ncw ,

In which rclone version this 4th env auth option (Workload Identity) will be available?
I am using v1.62.2 , I guess its not present in that.

Thanks
Mahendra

**Comment by ncw** [comment]
@hegdemahendra this is in [the latest beta](https://beta.rclone.org/) which is due to become v1.63 by the end of the week hopefully.

**Comment by hegdemahendra** [comment]
Thank you !

**Pull request merged**
