### PR TITLE
docs: more explicit doc for --all with params

### PR DESCRIPTION
**Pull request by wholtz**
#### What is the purpose of this change?

enhanced documentation

#### Was the change discussed in an issue or in the forum before?

#5825

#### Checklist

- [ x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [ x] I have added tests for all changes in this PR if appropriate.
- [x ] I have added documentation for the changes if appropriate.
- [x ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x ] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ivandeex** [comment]
(docs ==true && config == true) == (albertony == true) ? :)

**Comment by albertony** [comment]
I agree that the existing sentence is a bit too vague. But by saying command line parameters we exclude [environment variables](https://rclone.org/docs/#environment-variables).

```
set RCLONE_FTP_HOST=XYZ
rclone config create xxx ftp --all
Option host.
FTP host to connect to.
E.g. "ftp.example.com".
Enter a string value. Press Enter for the default ("XYZ").
```

Perhaps not exclude this possibility, by inserting an "or as environment variables", or something else?

**Comment by wholtz** [comment]
I was unaware parameters could come from environmental variables. Updated wording include environmental variables.

**Comment by albertony** [comment]
Thanks!

**Pull request merged**
