### PR TITLE
http: fix webdav OPTIONS response (#6433)

### PR DESCRIPTION
**Pull request by yuudi**
#### What is the purpose of this change?

fix behavior changes of webdav server OPTIONS reponse on commit 6c8148ef39ea51b1d4092128c598ac12c6fc1523

#### Was the change discussed in an issue or in the forum before?

#6433

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by blaineam** [comment]
I can test this when you get a beta for this up. Hoping this fixes the webdav serve issues for macOS finder and Synology DSM.

**Review by ncw — APPROVED** [review]
That looks very good - I'll merge that now - thank you.

**Comment by ncw** [comment]
@blaineam that should arrive in [the latest beta](https://beta.rclone.org/) in 15-30 mins.

**Comment by blaineam** [comment]
@ncw This fixed the broken rclone (beta) webdav serve for macos finder clients, I appreciate @yuudi quick work resolving this bug.

**Pull request merged**
