### PR TITLE
Rename Unknwon/goconfig to unknwon/goconfig

### PR DESCRIPTION
**Pull request by oxo42**
#### Fix the capitalization of Unknwon/goconfig

Due to reasons I cannot control, my company's thrift party repository system does not allow case conflicting files.  e.g. it will reject a commit that has
* `Foo/file1.txt`
* `foo/file2.txt`

The correct go package for [Unknwon/goconfig](https://github.com/Unknwon/goconfig) is shown on the README as
```
go get github.com/unknwon/goconfig
```

I am using a package that transitively depends on rclone.  `unknwon/goconfig` is already in my repository.

#### Checklist

- [X] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [X] I have added tests for all changes in this PR if appropriate.
- [X] I have added documentation for the changes if appropriate.
- [X] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by albertony** [comment]
Yeah, it was changed at some point:

https://github.com/unknwon/goconfig/commit/4b0d4b818a95f1242556e08cbf9912d169cbade7

**Comment by albertony** [comment]
... except the linting failed:

> fs/config/configfile/configfile.go:12: File is not `goimports`-ed (goimports)

**Comment by ncw** [comment]
@oxo42 can you run go fmt on the the changed files? Since the case changed the imports will order differently.

Thanks

**Comment by oxo42** [comment]
Sorry I made the initial pull request from

**Review by ncw — APPROVED** [review]
This looks great, thank you.

I will merge it now.

**Pull request merged**
