### PR TITLE
restic: refactor to use lib/http

### PR DESCRIPTION
**Pull request by innovate-invent**
#### What is the purpose of this change?

refactors restic service to use new lib/http library

#### Was the change discussed in an issue or in the forum before?

https://github.com/rclone/rclone/pull/3842

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ncw** [comment]
This linter failed for this one?

```
cmd/serve/restic/restic.go:209:10: should not use basic type string as key in context.WithValue (golint)
		ctx := context.WithValue(r.Context(), "remote", urlpath)
		       ^
```

**Comment by innovate-invent** [comment]
I don't know what that error was about. I am not sure it is related.

**Comment by ncw** [comment]
This looks like it is missing the Auth too?

**Comment by ncw** [comment]
I expect the windows/386 build problem is unrelated - the logs are gone so I can't see now.

Can you rebase this and push it again then it will rebuild.

**Comment by ncw** [comment]
I'm going to merge this as part of the [fix-remove-httplib](https://github.com/rclone/rclone/tree/fix-remove-httplib) branch.

I've had to update it quite a lot for the lib/http changes.

Thank you for doing this and expect to see it in rclone v1.61

**Pull request closed without merging**
