### PR TITLE
mount: allow mounting to root directory on windows

### PR DESCRIPTION
**Pull request by albertony**
#### What is the purpose of this change?

Fixed bug in mount on Windows introduced in 1.54.0, where mounting on root directory is no longer possible.

Edit: Added a second commit that also fixes a less critical issue regarding relative paths when mounting to directory. More details below. Let me know if you want me to move this to a separate MR or something..

##### Done

- Removed incorrect error return for mountpath that represents a directry at root level on existing drive.
- Also removed the distinction between `X:` and `X:\`: The latter will be converted to `X:` and used for drive letter mount, previously it would be reported as error "parent of mountpoint directory does not exist". Any other paths logically representing the same, such as `X:\some\folder\..\..` will still be reported as error: "parent of mountpoint directory does not exist".
- Edit (second commit): Calling filepath.Abs on the supplied mount path, which fixes handling of relative paths (see below). It is also better as the debug log message "Mounting on .." will show the actual path used, e.g. when mounting to `C:some\..\crazy\..\..\path` (which actually works)
##### Examples:

If C: exists and X: does not:

`rclone mount remote: C:` fails (mountpoint path already exists)
`rclone mount remote: C:\` fails (mountpoint path already exists)
`rclone mount remote: C:\MyMount` works (directory mounting)
`rclone mount remote: C:\test\abc\..\..\MyMount` works (same result as with `C:\MyMount`)

`rclone mount remote: X:` works (drive mounting)
`rclone mount remote: X:\` works (drive mounting)
`rclone mount remote: X:\MyMount` fails (parent of mountpoint directory does not exist)

##### ~Possible future~ Additional improvements (relative paths):

In the released version some relative paths work, but others that should/could does not:

`rclone mount remote: .` fails, but that is correct (mountpoint path already exists)
`rclone mount remote: MyMount` fails, which it should not (trying to find parent path fails)
`rclone mount remote: .\MyMount` fails, same as above
`rclone mount remote: ..\MyMount` works

Fixed this with the second commit, so any ©️ ®️ kind of relative path work as expected.

##### Bad excuses

Part of the issue were due to the following consideration: When user tries to mount to path D:\\", which is illegal (in WinFsp), should it be reported as an error to inform the user that this is illegal, or should rclone just assume the intention was to mount as a drive letter and fix it to "D:"? And then the other part was not understanding correctly how the filepath.Clean function, implicitely called from filepath.Join, manipulates the path (which is, by the way, the reason for using internal regex methods to classify the path) There *could* still be some remaining corner cases, depending on how os.Stat vs filepath.Clean etc handles different crazy variants...

#### Was the change discussed in an issue or in the forum before?

https://forum.rclone.org/t/fatal-error-failed-to-mount-fuse/22119

#### Checklist

- [X] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] I have added tests for all changes in this PR if appropriate.
- [X] I have added documentation for the changes if appropriate.
- [X] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [X] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ncw** [comment]
OK that looks good to me - I will merge it now - thank you :-)

> Bad excuses

No excuses necessary! I appreciate your help :-)

In fact you've made loads of great contributions to rclone - do you want to join the project? If so I'll send you an invite.

**Comment by albertony** [comment]
> do you want to join the project? If so I'll send you an invite.

It would be an honour... I think - I don't really know what that means, if there are suddenly super high expectations and a ton of responsibilities? :)

**Comment by ncw** [comment]
> > do you want to join the project? If so I'll send you an invite.
> 
> It would be an honour... I think - I don't really know what that means, if there are suddenly super high expectations and a ton of responsibilities? :)

It is mainly so you can be part of the rclone team. You also get the shiny rclone badge on your github profile!

I made a list of things maintainers might do in the [MAINTAINERS](https://github.com/rclone/rclone/blob/master/MAINTAINERS.md) doc.

But it is an open source project so it is completely up to you how much work you put in - no expectations at all :-)

I'll send you a link for the rclone organisation which is the first step if you want to carry on. That will give you membership of the rclone org and rights to do stuff to tickets and code on rclone/rclone. I'd expect you to send PRs for code changes for the moment. It will probably barrage you with notifications too, which I expect you'll want to disable!

**Comment by fxzxmic** [comment]
Why did I fail in this situation: `rclone mount remote: C:\MyMount`
```
rclone mount remote: "D:/Storage"
Fatal error: failed to mount FUSE fs: mountpoint directory is at root: D:\
```

**Comment by albertony** [comment]
I don't think this has been released yet. It will be in 1.55 due in a few days: https://github.com/rclone/rclone/issues/5162.

**Comment by fxzxmic** [comment]
> I don't think this has been released yet. It will be in 1.55 due in a few days: #5162.

Sorry, I just found that it hasn't been released yet. Now I use beta version. Everything is normal.

**Comment by albertony** [comment]
Great. Sorry for the inconvenience.

**Pull request merged**
