### PR TITLE
Grammar/readability: 2 messages now in 2 sentences

### PR DESCRIPTION
**Pull request by Jonta**
#### What is the purpose of this change?

Grammar. Readability

#### Was the change discussed in an issue or in the forum before?

Don't know

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by albertony** [comment]
Looks better. 👍 

But this section is an example session showing output from the `rclone config` command, so its best if we also do the change where this text originates:

https://github.com/rclone/rclone/blob/1409b89f6c07d80bdfa880ad018a4a7771c049f1/backend/crypt/crypt.go#L42

**Comment by Jonta** [comment]
@albertony Thanks

1st time doing a multi-commit PR iirc

I _think_ I've done it right now

**Comment by Jonta** [comment]
Ah: "Do not edit" mentioned in docs/Readme.md: https://github.com/rclone/rclone/commit/c8683fc9161bc0140ceaa740a36f081c228d0d50#diff-0b5ca119d2be595aa307d34512d9679e49186307ef94201e4b3dfa079aa89938R8

And "do not edit"-marker in docs/content/crypt.md: https://github.com/rclone/rclone/commit/78b9bd77f55ee117f1427ce684190c959f8d8dd6#diff-da1a38a9b467086478db9424de14890fbd77a6a209f2df2441d712bcfa15e869R42

**Comment by albertony** [comment]
Correct: The option docs are autogenerated. So you must change help strings in the go code, like you have done now, and it will (at some point near release) be inserted into the .md file and deployed on docs pages.

Your original change was in the [example](https://github.com/rclone/rclone/blob/master/docs/content/crypt.md#configuration) section, *above* the "do not edit" marker, though, wasn't it? This text will not be automatically fixed, so you *could* update that as well.

**Comment by Jonta** [comment]
@albertony _Reasonably_ certain that my patch-1 is correct now. :p

**Comment by ncw** [comment]
Thanks for reviewing this @albertony - please merge (or squash and merge) this when you are happy :-)

**Comment by albertony** [comment]
> @albertony _Reasonably_ certain that my patch-1 is correct now. :p

Perfect 👍 Thank you. Will merge it now.

**Pull request merged**
