### PR TITLE
vfs: add flag --vfs-case-insensitive for windows mounts

### PR DESCRIPTION
**Pull request by ivandeex**
#### What is the purpose of this change?

This change solves a particular problem with rclone mount.
I use rclone on windows to mount a cloud file archive and need an automated scriptable way to verify file consistency. Windows provides `fciv` for that, a functional equivalent of `sha1sum` / `md5sum` Linux utilties but with a different format of directory checksums. Linux utilities use hex-encoded one-file-per-line format and `fciv` uses base64 encoded xml based format. `fciv ` is used daily by many windows devops to verify large archives for consistency. I use automated powershell scripts to run it against the archive.

However, there is a gotcha: fciv brings file names to lower case for compatibility with previous windows versions. This is not a problem if I mount archive using such programs as WebDrive or NetDrive but breaks with rclone. I tried to tweak a case-insensitivity option in WinFSP, the rclone mount layer for Windows, but to no avail. This patch fixed the problem for me and did not introduce problems with the mount. I believe it can solve other similar use cases, eg. with video or dlna players.

How to reproduce: 
- create a test webdav remote
- open powershell cli window on windows
```
choco install -y fciv
rclone mount webdav_test: m:
cd m:
ls
echo "abc" > TestCase1.txt
fciv.exe TestCase1.txt
```
- fciv fails trying to open `testcase1.txt\*`.
- stop rclone and proceed:
```
rclone mount webdav_test: m: --vfs-case-insensitive
cd m:
fciv.exe TestCase1.txt
```
Now fciv can successfully calculate checksum.

Note: I have not yet added documentation or unit tests for the flag as I think we need to discuss the hack first.

#### Was the change discussed in an issue or in the forum before?

Probably yes, but I cannot find.

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ncw** [comment]
This looks like a useful fix to me - thank you :-)

Some thoughts...
- Do you think the flag should default to `true` on windows?
- a linear search through d.items could be slow, but the way you've written it is that this is only called as a fallback so that is probably OK
- I'm not sure about returning ENOENT if the file is duplicated, maybe that should return EIO or maybe just return the first match?  What do you think?
- I did a quick review and I couldn't see any other places in the vfs that would need to be changed, but I could be wrong!

Docs and a test would be great!

**Comment by ivandeex** [comment]
All my windows mounts have this flag for three months. No harm, runs good.
The question is - how to define "Windows"? An .exe build of rclone?
Will think about EIO (or EINVAL?)
Will do docs and a test.

**Comment by ncw** [comment]
runtime.GOOS == "windows" is a pretty good test and it is also a constant.

**Comment by ivandeex** [comment]
A note on error code.
I can't find a specification for stat() call on Windows. POSIX can be found here https://pubs.opengroup.org/onlinepubs/9699919799/ and concretely for stat() family here https://pubs.opengroup.org/onlinepubs/9699919799/functions/stat.html.
EIO seems like a good match but it is not yet defined in rclone/vfs/errors.go
EBADF is another candidate, its error message matches our case, it is already present in vfs/errors.go, but POSIX defines it only for fstatat(), not for stat(). I'd prefer EBADF.

**Comment by ivandeex** [comment]
As we are going to make --vfs-case-insenstive=true the default on Windows and thus Windows diverges from Linux/Mac, I'll add racequicktest in Appveyor script.
```
test_script:
- make GOTAGS=cmount quicktest
- make GOTAGS=cmount **racequicktest**
```
Hope it includes full VFS tests too.

**Comment by ncw** [comment]
> A note on error code.
> I can't find a specification for stat() call on Windows. POSIX can be found here https://pubs.opengroup.org/onlinepubs/9699919799/ and concretely for stat() family here https://pubs.opengroup.org/onlinepubs/9699919799/functions/stat.html.
> EIO seems like a good match but it is not yet defined in rclone/vfs/errors.go

I think if you just return a plain go error, then the FUSE layer will translate it to EIO.

> EBADF is another candidate, its error message matches our case, it is already present in vfs/errors.go, but POSIX defines it only for fstatat(), not for stat(). I can use EBADF or add EIO in errors.go if you like or if testing with WinFSP detects any problems.

Let's try just returning a nice go error `errors.Errorf("duplicate filename %q detected with --vfs-case-insensitive set", fileName)` - I'm pretty sure that will return EIO to userspace and make an ERROR log on linux & windows.

> As we are going to make --vfs-case-insenstive=true the default on Windows and thus Windows diverges from Linux/Mac, I'll add racequicktest in **Appveyor** script.

Good idea.

You could add it to Azure pipelines too with

```diff
diff --git a/azure-pipelines.yml b/azure-pipelines.yml
index 42a0cd138..512a7e0af 100644
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -49,6 +49,7 @@ strategy:
       GO_VERSION: latest
       BUILD_FLAGS: '-include "^windows/amd64" -cgo'
       MAKE_QUICKTEST: true
+      MAKE_RACEQUICKTEST: true
       DEPLOY: true
     windows_386:
       imageName: windows-2019
```

**Comment by ivandeex** [comment]
The unit test creates test files whose names differ only by case. This pre-condition is expected to fail on Windows and I skip the test there. But it also fails on MacOS. Is MacOS filesystem case-insensitive-case preserving too? Can I skip the test on MacOS? Here is the log https://travis-ci.org/rclone/rclone/jobs/580412958

**Comment by ivandeex** [comment]
TestVFSCaseInsensitive fails for Mailru backend. This means that Mailru cloud is case-insensitive. Thus, we need to identify all case-insensitive backends and ignore this test for them.

**Comment by ivandeex** [comment]
Now case sensitivity test detects whether underlying remote file system is case-sensitive. If not, the test skips itself (on Windows, MacOS and some cloud providers).
The CaseInsensitive flag is by default set on Windows.
Though MacOS file system is not fully case-sensitive the CaseInsensitive flag is not set by default, as per documentation.
All test suites now pass OK. Please review.

**Comment by ncw** [comment]
> The unit test creates test files whose names differ only by case. This pre-condition is expected to fail on Windows and I skip the test there. But it also fails on MacOS. Here is the log https://travis-ci.org/rclone/rclone/jobs/580412958
> Is MacOS filesystem case-insensitive-case preserving too? (I don't know this OS, I though it is based on case-sensitive BSD)

I had forgotten about macOS... The usual file systems for macOS are case-insensitive.  It is possible to make macOS file systems case-sensitive but that isn't the default and I understand it isn't very common.

See local backend setting of case insensitive flag

https://github.com/rclone/rclone/blob/b3db38ae3150aad2764a50728e9fddaa3a17ce31/backend/local/local.go#L252-L264

> Can I skip the test on MacOS?

Yes

> Do you think we should set CaseInsensitive to true on "darwin" as well?

I think we probably should, yes.

In which case the code and docs need a small tweak.

> TestVFSCaseInsensitive fails for Mailru backend. This means that Mailru cloud is case-insensitive on its own. I will mention this in documentation.

You should set the `Features` flag `CaseInsensitive` also.

> Thus, we need to identify all case-insensitive backends and ignore this test for them and for all overlay test remotes that use underlying case-insensitive backends for integration tests. :O

You can read the `f.Features().CaseInsensitive` flag to determine whether a remote is CaseInsensitive or not.

It isn't 100% reliable (see macOS discussion above!) but it works elsewhere in the tests.

> A simpler way is to skip the test if precondition fails. I have added a comment on the line that fails on case-insensitive backends (see https://github.com/rclone/rclone/pull/3504/files#diff-6cb1692bd88d435baf2c05ce9f4702d7R328):

That is another way too :-)

It might be easier to skip on the feature flag though.

**Comment by ivandeex** [comment]
The f.Features().CaseInsensitive for Mailru will be updated by relevant PR.
The case sensitivity test passes using auto-detection.
--vfs-case-insensitive will be set by default on MacOS too, the docs have been updated.
All review comments have been addressed.

**Comment by ncw** [comment]
That is great - thank you very much :-)

I'll merge this now.

Check https://pub.rclone.org/integration-tests/current/ tomorrow to see if any backends got broken!

**Comment by ncw** [comment]
Grrr, palm clicked the submit button before I finished editing the commit message!

All merged now :-)

**Comment by ncw** [comment]
It looks like [all the new tests passed](https://pub.rclone.org/integration-tests/current/) except for box

image

```
"./vfs.test -test.v -test.timeout 30m0s -remote TestBox: -verbose -test.run '^TestCaseSensitivity$'" - Starting (try 5/5)
=== RUN   TestCaseSensitivity
--- FAIL: TestCaseSensitivity (6.99s)
    run.go:175: Remote "box root 'rclone-test-nawawup8sufawaw1sawoxur3'", Local "Local file system at /tmp/rclone040288654", Modify Window "1s"
    run.go:269: Failed to put "FilEb" to "box root 'rclone-test-nawawup8sufawaw1sawoxur3'": Error "item_name_in_use" (409): Item with the same name already exists
FAIL
2019/09/05 11:13:23 DEBUG : box root 'rclone-test-nawawup8sufawaw1sawoxur3': Purge remote
"./vfs.test -test.v -test.timeout 30m0s -remote TestBox: -verbose -test.run '^TestCaseSensitivity$'" - Finished ERROR in 8.554789525s (try 5/5): exit status 1: Failed [TestCaseSensitivity]
```

So it looks like box didn't allow the file to be overwritten by a file of the new name.

Perhaps this is a bug in the box backend?

**Comment by ivandeex** [comment]
The error happens here: https://github.com/rclone/rclone/blob/master/vfs/vfs_case_test.go#L27
We should either fix it or ignore it.

**Comment by ivandeex** [comment]
I propose to return to your original poposal to skip this test if `f.Features().CaseInsensitive == true`.
Let's add this check and do `t.Skipf(...)` at the very top of TestCaseSensitivity, before test file creation.

**Pull request merged**
