### PR TITLE
protondrive: add SkipSignatureVerifications to option

### PR DESCRIPTION
**Pull request by henrybear327**
#### What is the purpose of this change?

To address signature verification-related issues mentioned in #6072, esp. [this](https://github.com/rclone/rclone/issues/6072#issuecomment-1657884837)

The main changes are
- adding an advanced option to set if we want to verify the signature or not during decryption 
- if the option is set to true, we will not perform signature verification during decryption, e.g. obtaining keyring 

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by henrybear327** [comment]
Hi @ncw, 

Is there a way to build a beta version from this branch directly without merging? :) 

I remember you mentioning somewhere but I can't find it now :( Sorry.

**Comment by henrybear327** [comment]
Hello @ncw, 

Is it possible that you can help me make a build for this PR :) 

I am not able to push to this repo for some reason, and I am troubleshooting a the moment. 

Thank you!

**Comment by ncw** [comment]
Done here

[v1.64.0-beta.7200.2ea8b3db4.protondrive-fix_signature_verification_error](https://beta.rclone.org/branch/protondrive-fix_signature_verification_error/v1.64.0-beta.7200.2ea8b3db4.protondrive-fix_signature_verification_error/) on branch [protondrive-fix_signature_verification_error](https://github.com/rclone/rclone/tree/protondrive-fix_signature_verification_error) (uploaded in 15-30 mins)

(I don't think the beta builder deals with `/` in the branch names - that may be the problem?)

**Comment by henrybear327** [comment]
> Done here
> 
> [v1.64.0-beta.7200.2ea8b3db4.protondrive-fix_signature_verification_error](https://beta.rclone.org/branch/protondrive-fix_signature_verification_error/v1.64.0-beta.7200.2ea8b3db4.protondrive-fix_signature_verification_error/) on branch [protondrive-fix_signature_verification_error](https://github.com/rclone/rclone/tree/protondrive-fix_signature_verification_error) (uploaded in 15-30 mins)
> 
> (I don't think the beta builder deals with `/` in the branch names - that may be the problem?)

Thank you @ncw! I will keep this in mind!

**Comment by henrybear327** [comment]
> Is this ready for merging?
> 
> I think you should rebase it off master first though as I put some fixes for lint stuff in master.

This PR is more like a workaround, and will be superseded by another PR that I am working on now! 

With the user feedback (the community of rclone is really great!), I am now able to identify the root cause the properly fix it.

**Comment by henrybear327** [comment]
The superseding PR is https://github.com/rclone/rclone/pull/7278

**Pull request closed without merging**
