### PR TITLE
mailru: fix uploads and range requests

### PR DESCRIPTION
**Pull request by ivandeex**
#### What is the purpose of this change?

Recently mail.ru changed their protocol. First, now clients should book upload server via a request to https://dispatcher.cloud.mail.ru/u instead of shard info dispatcher requests to meta server. Next, starting from June 2020 download servers ignore range requests from clients and return response 200 instead of 206. This PR adds logic to detect this behavior. Since upload functionality is critical, I suggest publishing this fix with the next point release.

#### Was the change discussed in an issue or in the forum before?

This PR fixes issues https://github.com/rclone/rclone/issues/4584, https://github.com/rclone/rclone/issues/4376 and reverts commit https://github.com/rclone/rclone/commit/9d3d397f50fe94df0f723a571507e2ce72428ab6

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ivandeex** [comment]
Integration tests passed.

**Comment by ivandeex** [comment]
@ncw
How can we make VFS layer prefer full object downloads vs ranges?

**Comment by ncw** [comment]
Thanks for fixing this :-)

> Recently mail.ru changed their protocol. First, now clients should book upload server via a request to https://dispatcher.cloud.mail.ru/u instead of shard info dispatcher requests to meta server. Next, starting from June 2020 download servers ignore range requests from clients and return response 200 instead of 206. This PR adds logic to detect this behavior.

Hmm, this is a bit unfortunate. So I understand this to mean that no partial requests are possible at all?

If so then this is the first backend where this hasn't been possible :-(

> Since upload functionality is critical, I suggest publishing this fix with the next point release.

So put commit "mailru: fix uploads after recent changes on server ￼…" into the stable release - sounds OK to me.

> Integration tests passed.

:-)

I gave the code a once over and it looks fine to me.

> How can we make VFS layer prefer full object downloads vs ranges?

I think we'd need 
- a backend flag to announce that it can't do range requests
- we'd use this flag to then force --vfs-cache-mode full and download the entire objects...

I guess we can still download from the start and close the connection when done.

Note that range requests are used with multi stream downloads so these should be disabled too. Range requests are also used for resumes when downloads fail, for `rclone cat --head --tail` and probably lots of other places I've forgotten.

I see your workaround in the code which is OK provided you've got bandwidth to burn...

Is there no chance of getting some sort of partial download working?

**Comment by ivandeex** [comment]
> Hmm, this is a bit unfortunate. So I understand this to mean that no partial requests are possible at all?
> If so then this is the first backend where this hasn't been possible :-(
> I see your workaround in the code which is OK provided you've got bandwidth to burn...
> Is there no chance of getting some sort of partial download working?

I tried several methods I could imagine. Sent "Content-Range", "Accept-Ranges" and various "Content-Type" with requests to no avail. I will come up with new ideas when there is one.

I also played with another mature OSS project related to MailRu.Cloud,
https://github.com/yar229/WebDavMailRuCloud (WDMRC) which semi-transparently converts between MRC and WebDAV.
I created a dockerfile with WDMRC https://github.com/ivandeex/ivadocker/tree/master/wdmrc and ran it as a daemon.
I used it as a black-box since I'm not a .NET guru, so I created a test WebDAV remote [wdmrc] and ran integration tests against it.
TestCat failed on range requests in the same way.
This means WDMRC also suffers from disappeared support of partial downloads and has no cure currently.

We could discuss this with https://github.com/yar229 and try to find a solution together.
Alas, c'est la vie, and I've got unlimited home plan to burn.

**Comment by ivandeex** [comment]
> > Since upload functionality is critical, I suggest publishing this fix with the next point release.
> So put commit "mailru: fix uploads after recent changes on server ￼…" into the stable release - sounds OK to me.

Added to the 1.54 milestone. Having it in 1.53.2 would be fine too.

**Comment by ivandeex** [comment]
> > How can we make VFS layer prefer full object downloads vs ranges?
> 
> I think we'd need
>     * a backend flag to announce that it can't do range requests
>     * we'd use this flag to then force --vfs-cache-mode full and download the entire objects...
> I guess we can still download from the start and close the connection when done.
> 
> Note that range requests are used with multi stream downloads so these should be disabled too. Range requests are also used for resumes when downloads fail, for `rclone cat --head --tail` and probably lots of other places I've forgotten.

I suggest to open another issue or PR to implement that backend flag (fs.Features flag? option?)

**Comment by ivandeex** [comment]
Do you agree to merge this PR? Squash or not to squash?

If we don't find a proper solution, I will submit a change to the mail.ru documentation with --vfs-cache-xxx notes
and stating this backend is bandwidth hungry.

**Comment by ncw** [comment]
> I tried several methods I could imagine. Sent "Content-Range", "Accept-Ranges" and various "Content-Type" with requests to no avail. I will come up with new ideas when there is one.

:-)

> I also played with another mature OSS project related to MailRu.Cloud,
[snip]
> TestCat failed on range requests in the same way.
> This means WDMRC also suffers from disappeared support of partial downloads and has no cure currently.

OK it was worth a try!
 
> We could discuss this with https://github.com/yar229 and try to find a solution together.

Is there an official client? The web client? That probably doesn't do range requests unless it lets you do stuff like play videos.

> > I think we'd need
> > * a backend flag to announce that it can't do range requests
> > * we'd use this flag to then force --vfs-cache-mode full and download the entire objects...
> > I guess we can still download from the start and close the connection when done.
> > Note that range requests are used with multi stream downloads so these should be disabled too. Range requests are also used for resumes when downloads fail, for `rclone cat --head --tail` and probably lots of other places I've forgotten.
> 
> I suggest to open another issue or PR to implement that backend flag (fs.Features flag? option?)

Yes what we need is a Feature flag

https://github.com/rclone/rclone/blob/f3cf6fcdd7a7cd4952ed1c2043b97106d4750a2f/fs/fs.go#L504-L507

These are quite easy to create

Do you fancy opening an issue, then we can make notes on things which need fixing?

@creativeprojects - I just remembered that encrypted seafile backends don't support seek too - is that right? We should probably set the flag there too.

> Do you agree to merge this PR? Squash or not to squash?

Yes - LGTM to merge. I think I prefer the separate commits.

Any commits you want in the stable release can you `git cherry-pick` them into the v1.53-stable branch. Or send me the commit numbers and I'll do it.

I'm beginning to think we need a better workflow for the stable branch but I haven't figured it out yet - any suggestions welcome :-)

> If we don't find a proper solution by 1.54, I will submit a change to the mail.ru documentation with --vfs-cache-xxx notes
> and stating this backend is bandwidth hungry.

OK seems reasonable.

**Comment by ivandeex** [comment]
Unsquashed merge (as 3 commits) is "Not enabled for this repository"

**Comment by creativeprojects** [comment]
>  I just remembered that encrypted seafile backends don't support seek too - is that right? We should probably set the flag there too.
> 

This is right, we could add it there as well 👍

**Comment by ivandeex** [comment]
> Is there an official client? The web client? That probably doesn't do range requests unless it lets you do stuff like play videos.
There are both, and web UI can play clips AFAIK. That's a good catch, I'll give it a try.

**Pull request merged**
