### PR TITLE
improve cleanup of temp files in rclone test info, fix for issue 7209

### LINKED ISSUE #5572: Why not use copyBuffer?
https://github.com/rclone/rclone/blob/aa0ceb6c5c66cfeb0c90f024cc3f66f6d69be1cd/backend/local/local.go#L1176

### PR DESCRIPTION
**Pull request by KDreynolds**
#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Review by ncw — COMMENTED** [review]
Thank you for tackling this - its been on my get around to it one-day list for a long time!

Unfortunately we have a function `operations.Purge` which does what a lot of this change does already. I did write that in [my original message](https://github.com/rclone/rclone/issues/7209#issuecomment-2016483112) but I didn't make it clear enough - I should have linked to the function I think.

Please see the other notes inline.

---- 

Can you fix-up the commit message please?

Instead of

     improve cleanup of temp files in rclone test info, fix for issue 7209

We should have something like

    test info: improve cleanup of temp files - fixes #7209

Using the prefix `test info` will make the changelog generators life easier and writing `fixes #7209` will cause GitHub to link the PR to the issue and to close the issue once it is merged.

See [commit message guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages) for more info.

I suggest you `git commit --amend` this commit then force push the branch to overwrite the commit with a new one.

Thank you and sorry to put so many comments on your PR, however it is very useful and I'm keen we get it right!

**Comment by KDreynolds** [comment]
Thanks @ncw ! You were clear enough, i'm just slow haha, I'll get this cleaned up.

**Comment by KDreynolds** [comment]
Ok i think I have properly addressed the issues you laid out @ncw , LMK if there is anything else I need to fix. Thanks for the help and patience!

**Review by ncw — COMMENTED** [review]
I think this is looking great now - thank you.

The CI has flagged up that this file is not `go fmt`-ed - can you `go fmt` it please?

**Comment by KDreynolds** [comment]
Sounds good! I go fmt-ed the file and amended my commit. Should be all good to go now but just let me know if I goofed something up and I will fix it. Thanks as always for the help and feedback.

**Review by ncw — APPROVED** [review]
Looks great now - thank you :-)

**Pull request merged**
