### PR TITLE
Go deps: update golang.org/x/net for better performance

### PR DESCRIPTION
**Pull request by teran**
In some cases such as using rclone from [restic](https://github.com/restic/restic) the fresh new golang.org/x/net/http2 provides better performance on higher amount of connections. For better network utilization with rclone it's required to set `-o rclone.connections=N` in restic and add `--transfers=N` to rclone options.

#### Checklist

- [X] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [X] I have added tests for all changes in this PR if appropriate.
- [X] I have added documentation for the changes if appropriate.
- [X] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [X] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Review by ncw — APPROVED** [review]
I normally update all the deps early in the new version cycle, usually after making the first patch release!

However I'll merge this when the CI goes green as you've written some interesting things in the commit message :-)

**Comment by Skylion007** [comment]
@ncw Any reason this isn't merged?

**Comment by ncw** [comment]
Sorry I forgot to merge this.

I recently updated the dependencies. Can you check if these cover your changes? If not please rebase this and force push - thank you.

**Comment by teran** [comment]
@ncw golang.org/x/net is updated to 0.12.0 at master, so this change is no longer needed

**Comment by ncw** [comment]
@teran thanks for checking and apologies for not merging your change.

**Comment by teran** [comment]
@ncw no worries :)

**Pull request closed without merging**
