### PR TITLE
Update README to reflect state with ACD

### PR DESCRIPTION
**Pull request by gingerlime**
Looks like ACD isn't really an option for most people, and I think documentation should reflect that.

### CODE REVIEW

**Comment by ncw** [comment]
The state of amazon cloud drive is spelt out in the amazon cloud drive page: https://rclone.org/amazonclouddrive/

This is linked to off the front page of rclone.org

Did you come to rclone through the github page?

**Comment by gingerlime** [comment]
Respectfully, I found all the info on this page and the linked forum utterly confusing. The TL;DR is painfully missing in my opinion. It’s basically unusable, and I think even you stated that you have no way of testing it. I find it misleading to claim that recline supports acd, even if it’s technically correct and it does support it (amazon doesn’t support rclone basically). I personally spent a good chunk of time just going through docs and coming to this rather grim realization, which was most succinctly described on the linked GitHub issue.

I think people deserve the simple truth in the most concise way. I think my PR reflects this simply and honestly.

Please forgive me if I misunderstood or misinterpreted anything. I came to rclone specifically for its acd integration.

**Comment by ncw** [comment]
I'm sorry that the rclone docs caused you to waste time, they aren't as clear as they could be.

Yes you are right ACD is technically supported, but only if you have your own keys which is unlikely.

What I'd like to do is come up with a clear statement of the current situation at the start of https://github.com/ncw/rclone/blob/master/docs/content/amazonclouddrive.md - something like this

> **Important:** Rclone supports Amazon Cloud Drive **only** if you have your own set of keys.  Unfortunately the amazon cloud drive developer program is now closed to new entries (link to page) so if you don't already have your own set of keys you will not be able to use rclone with amazon cloud drive.

Then link to that statement it in the README.md and https://github.com/ncw/rclone/blob/master/docs/content/about.md (which becomes the rclone.org front page)  with the text "[important note]" or something like that?

What do you think about that?

**Comment by gingerlime** [comment]
@ncw it all sounds great overall. It would be a huge improvement to clarity in my opinion. Thanks for being so open about it.

A couple of questions / suggestions though:

* I wonder if the google apps proxy is run/maintained by you(?) then is it really still helpful in any way right now? Or could it be deactivated? If it's not run by you, then I would probably remove references to it, unless it's in some kind of historic archive... Otherwise, most of the docs around it might be confusing right now (and a potential leak of credential, even though I trust that it's not storing them anyway, but it still exposes exposure).
* Linking to this note/page with `[important note]`, sounds like a good idea too. 👍 

I totally understand the natural urge to stick to documentation and code that was definitely useful, and these have some value to show the work and effort that's gone into them. At the same time, that's one of the beauties of version control. History is still there if you go looking :)

Besides that, perhaps the documentation could also focus on some kind of a petition / call-to-action to encourage Amazon to relax those restrictions. I think it would serve the community and rclone better. But that's entirely up to you. I don't know how strongly you feel about this or whether you want to prompt more action in this direction.

(sorry again if this all sounds like [couch coaching](https://www.urbandictionary.com/define.php?term=couch%20coach). I'm a complete outsider and my opinion shouldn't count in any serious way. I sincerely appreciate your openness to have this discussion in the first place)

**Comment by gingerlime** [comment]
@ncw perfect! I think things are much(!) clearer now, and I think the call-to-action is very helpeful, and I really hope it leads somewhere.

Just one thing unrelated to this change that I spotted

> Since rclone doesn't ~~not~~ currently have its own Amazon Drive credentials...

Thank you so much! I hope to use and contribute to rclone in future, even though my primary use case is not supported (yet!) ;-)

**Comment by gingerlime** [comment]
Thanks @ncw. I really appreciate it, and I hope other users would too, despite the fact that ACD isn't very useable for most people (yet!).

**Comment by gingerlime** [comment]
@ncw just checked the link from the readme, and the ACD page doesn't seem to show the new updates for me. Maybe it's still not "deployed/compiled" yet?

**Comment by ncw** [comment]
The website updates at the release time normally, however I'll change it now...

**Pull request closed without merging**
