### PR TITLE
Make ncdu more robust in case of errors

### PR DESCRIPTION
**Pull request by rockdreamer**
#### What is the purpose of this change?

* Make ncdu command handle errors reading directories.
* Highlight directories with errors in UI.

#### Was the change discussed in an issue or in the forum before?

Yes, issue #4014 

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ ] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by rockdreamer** [comment]
Output sample of a directory with unreadable subdirectories
Screenshot_20200426_140654
Output sample of an unreadable directory
Screenshot_20200426_140746

**Comment by rockdreamer** [comment]
I'd like to add tests but the area has none I'm afraid. I'd appreciate a pointer to something I could use to fake a remote with an error.
One thing that I notice is that this now works for remotes, but keeps the previous suboptimal behaviour on local directories (errors fill the screen and are not calculated in the output)

**Comment by ncw** [comment]
This is a very nice change - thank you :-)

> I'd like to add tests but the area has none I'm afraid. I'd appreciate a pointer to something I could use to fake a remote with an error.

Err, yes....

Some parts of `ncdu` should be easy enough to test. Rclone has a framework for running tests against real backends, and also against mock ones.

We don't currently have a backend which could return errors though....

> One thing that I notice is that this now works for remotes, but keeps the previous suboptimal behaviour on local directories (errors fill the screen and are not calculated in the output)

The local backend is a bit noisy about logging stuff it doesn't understand. What exactly are the logs you are seeing?

I thought your code looked good. The only thing that made me think was the extreme number of things returned from `AttrI`! Any ideas here?

**Comment by rockdreamer** [comment]
Hi, thanks for reaching back!
This is the first time I've ever written a possibly useful piece of code in go. I've only read go code and played around with some examples up to now. I'm sure you're trying to get me to think what's the most idiomatic way and reasonable way of moving the data around and my biggest worry is that I'll approach this from a C++/Python perspective that's a poor fit for Go :)

With that said, it feels to me that AttrI is essentially returning most of cmd/ncdu/scan/Dir's attributes.
So I'm thinking that something like renaming Dir to NcduDirEntry (dropping the idea that it's a general 'Dir' class) and making it's contents more visible would make a bit more sense to me, but it also feels smelly to my C++ jarred nose that I'd be exposing such innards around between scan and ncdu.
I'd definitely accept some guidance on how you'd approach this and will work with that in mind :).

Regarding error messages, here's a sample. It's jumbled up exactly like it's on the bottom of the screen
`Total usage: 784.389M, Objects: 163 [listing in progress]2020/04/27 13:43:27 ERROR : ncdu-bad/d3: failed to open directory "ncdu-bad/d3": open /home/rdfm/code/ncdu-bad/d3: permission denied
              95 840            292020/04/27 13:43:27 NOTICE: puddletag/puddletag-docs/changelog: Can't follow symlink without -L/--copy-links
2020/04/27 13:43:27 NOTICE: conan/.tox/full/bin/python: Can't follow symlink without -L/--copy-links
               7 099            3442020/04/27 13:43:27 NOTICE: conan/.tox/full/bin/python3: Can't follow symlink without -L/--copy-links
2020/04/27 13:43:27 NOTICE: conan/.tox/full/bin/python3.8: Can't follow symlink without -L/--copy-links
                 807            4262020/04/27 13:43:27 NOTICE: puddletag/source/README: Can't follow symlink without -L/--copy-links
             4.335G, Objects: 60802020/04/27 13:43:27 NOTICE: chdkptpconversions/chdkptp-git/extlibs/built/lua52/lib/liblua52.a: Can't follow symlink without -L/--copy-links
             6 061            47632   `

What I'm missing is a high level picture of what would happen if those errors were bubbled up just like with other fs backends instead of relying in a workaround. What makes the local fs so special? That's missing from the workaround commit message :(
I'll probably have time to look at existing tests later in the week. Quite a bit of code to go through!

**Comment by ncw** [comment]
> This is the first time I've ever written a possibly useful piece of code in go. I've only read go code and played around with some examples up to now. I'm sure you're trying to get me to think what's the most idiomatic way and reasonable way of moving the data around and my biggest worry is that I'll approach this from a C++/Python perspective that's a poor fit for Go :)

:-)  I think what you've done is great!
 
> With that said, it feels to me that AttrI is essentially returning most of cmd/ncdu/scan/Dir's attributes.

It is, but it is also doing locking which is important

> So I'm thinking that something like renaming Dir to NcduDirEntry (dropping the idea that it's a general 'Dir' class) and making it's contents more visible would make a bit more sense to me, but it also feels smelly to my C++ jarred nose that I'd be exposing such innards around between scan and ncdu.

I'm not big on the idea of renaming it, since it is already quite specialised! Making the innards more open would be nice, but the scan runs concurrently with the displaying (you can use rclone ncdu while it is scanning) so it needs that locking...

> I'd definitely accept some guidance on how you'd approach this and will work with that in mind :).

After thinking about it a bit, how about this

```go
// AttrI returns the size, count and flags for the i-th directory entry
//
// if the entry is a directory isDir will be set and if the sub directory
// has been read it will be returned in subDir.
func (d *Dir) AttrI(i int) (size int64, count int64, isDir bool, subDir *Dir) {
	d.mu.Lock()
	defer d.mu.Unlock()
	subDir, isDir = d.getDir(i)
	if !isDir {
		size = d.entries[i].Size()
	} else if subDir != nil {
		size, count = subDir.Attr()
	}
	return size, count, isDir, subDir
}
```

Then make individual accessor methods (with locking!) for entriesHaveErrors and readError.  Note that readable is just `subDir != nil`

> Regarding error messages, here's a sample. It's jumbled up exactly like it's on the bottom of the screen
> `Total usage: 784.389M, Objects: 163 [listing in progress]2020/04/27 13:43:27 ERROR : ncdu-bad/d3: failed to open directory "ncdu-bad/d3": open /home/rdfm/code/ncdu-bad/d3: permission denied 95 840 292020/04/27 13:43:27 NOTICE: puddletag/puddletag-docs/changelog: Can't follow symlink without -L/--copy-links 2020/04/27 13:43:27 NOTICE: conan/.tox/full/bin/python: Can't follow symlink without -L/--copy-links 7 099 3442020/04/27 13:43:27 NOTICE: conan/.tox/full/bin/python3: Can't follow symlink without -L/--copy-links 2020/04/27 13:43:27 NOTICE: conan/.tox/full/bin/python3.8: Can't follow symlink without -L/--copy-links 807 4262020/04/27 13:43:27 NOTICE: puddletag/source/README: Can't follow symlink without -L/--copy-links 4.335G, Objects: 60802020/04/27 13:43:27 NOTICE: chdkptpconversions/chdkptp-git/extlibs/built/lua52/lib/liblua52.a: Can't follow symlink without -L/--copy-links 6 061 47632 `
> 
> What I'm missing is a high level picture of what would happen if those errors were bubbled up just like with other fs backends instead of relying in a workaround. What makes the local fs so special? That's missing from the workaround commit message :(

The trouble is that there is no method for rclone to return a directory entry with a note that there was a problem reading it attached. So if let's say there is a permission denied error for reading a single file in a directory, rclone would ditch the entire directory and return an error.

Maybe rclone should change the List() convention so that it returns as many valid entries as it can, and it returns an error if there was an error reading some of it... That is probably quite a big change though...

The treatment in the local backend is a bodge that I'm not really happy with!

For the other backends, reading directories either works or it doesn't - they don't ever work half way...

> I'll probably have time to look at existing tests later in the week. Quite a bit of code to go through!

Given that we don't have a testing framework for ncdu at the moment, building one would be a lot of work... I'd be inclined to get this PR in without tests then we can have a think whether there are parts of ncdu which should be tested and if so what would the best way of doing it be.

**Comment by Zirro** [comment]
As an alternative suggestion for a UI that matches the original ncdu, this could be a great opportunity to implement the first and second flags shown here: https://github.com/rclone/rclone/issues/3369#issuecomment-524086860

**Comment by ivandeex** [comment]
> As an alternative suggestion for a UI that matches the original ncdu, this could be a great opportunity to implement the first and second flags shown here: [#3369 (comment)](https://github.com/rclone/rclone/issues/3369#issuecomment-524086860)

@Zirro feel free to send a PR

**Comment by ivandeex** [comment]
@adamplansky could you please have a peer review of this pr?

**Comment by ivandeex** [comment]
> Given that we don't have a testing framework for ncdu at the moment, building one would be a lot of work...

@rockdreamer 
Could you please post here your manual test procedure as a comment. That way we can all be on the same page. Future ncdu PR would have a place to link, too.

**Comment by ivandeex** [comment]
Rebased on current master.
@rockdreamer Please save undone commits and pull to your workdir.

**Comment by ivandeex** [comment]
> The treatment in the local backend is a bodge that I'm not really happy with!

@ncw
Is it in scope for this PR?
Maybe a new comment in code or new issue would be enough?

**Comment by ncw** [comment]
I've just read through the code one more time, and I think it is sound.

What I'm gong to do is merge it as-is.

I think the ncdu could do with some refactoring - maybe on the lines I suggested above, but that can be a job for another day/PR.

Thank you for a very useful feature :-)

**Pull request merged**
