### PR TITLE
add subresource delete to s3 v2sign

### PR DESCRIPTION
**Pull request by shvc**
#### What is the purpose of this change?
The delete query string parameter must be included when you create the CanonicalizedResource for a multi-object Delete request.

Per https://docs.aws.amazon.com/AmazonS3/latest/userguide/RESTAuthentication.html

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Review by ncw — COMMENTED** [review]
This change looks reasonable at first glance.

What did it fix for you? That is what users normally want to know for the changelog!

**Comment by shvc** [comment]
> This change looks reasonable at first glance.
> 
> What did it fix for you? That is what users normally want to know for the changelog!

Without `delete` subresource, DeleteObjects API (https://github.com/aws/aws-sdk-go/blob/a68bf01b26e94db857730f77090d8b60f2360598/service/s3/api.go#L2434)does not work.

But rclone seems not use DeleteObjects at this moment.

**Comment by ncw** [comment]
> > This change looks reasonable at first glance.
> > What did it fix for you? That is what users normally want to know for the changelog!
> 
> Without `delete` subresource, DeleteObjects API (https://github.com/aws/aws-sdk-go/blob/a68bf01b26e94db857730f77090d8b60f2360598/service/s3/api.go#L2434) does not work.
> 
> But rclone seems not use DeleteObjects at this moment.

It doesn't! That is why I'm wondering why you made the pull request?

**Comment by shvc** [comment]
Just want to make things perfect.

**Comment by ncw** [comment]
:-)

I'll merge this now. Maybe it will be useful in the future - thanks!

**Pull request merged**
