### PR TITLE
Add additional FAQ item for port opening issues on Windows

### PR DESCRIPTION
**Pull request by mariusz-suchodolski**
Add solution to an issue on Windows 10 / Windows 11

#### What is the purpose of this change?

Add a solution to an issue I've noticed multiple times on various forums.
In my case it fixes the issues every time it had happened in my case.

#### Was the change discussed in an issue or in the forum before?

n/a

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ncw** [comment]
Looks useful - thank you.

What do you think @albertony ?

**Comment by albertony** [comment]
I'm not familiar with this specific issue.. But if it does in fact fix a real issue, I'm fine with including this into the faq.

Out of curiosity: Is it related to running in a container, wsl or other Hyper-V based guest system? Or does this fix issue also when running entirely on "native" windows host?

**Comment by mariusz-suchodolski** [comment]
Dear @albertony,

This fixes this issue when running natively on Win11 in my case, and eg. this looks like a forum post where this might have helped
https://forum.rclone.org/t/config-failed-to-start-auth-server-on-win10/12840

This is probably caused by one of the many VPN clients I have to use. But in my case this fixes whatever the underlying issue was.

**Comment by albertony** [comment]
Alright, thanks. I think we can merge it as it is, unless you intended to add something more (since its still a draft)?

**Comment by ncw** [comment]
Shall we merge this as-is @albertony ?

**Comment by albertony** [comment]
> Shall we merge this as-is @albertony ?

I think that's ok, yes. 👍

**Comment by ncw** [comment]
Thank you :-)

**Pull request merged**
