### PR TITLE
[Docs] Updated OneDrive max file size

### PR DESCRIPTION
**Pull request by Dibbyo456**
#### What is the purpose of this change?

OneDrive now supports up to 100 GB for both OneDrive Personal and OneDrive for Business.

chrome_2020-06-17_06-17-52

#### Was the change discussed in an issue or in the forum before?

No

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [ ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ ] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by Cnly** [comment]
Thanks! They're finally doing this. But it seems they haven't updated the docs yet, so it may be a good idea to wait a little bit more until the end of June.

**Comment by Dibbyo456** [comment]
> haven't updated the docs yet

https://support.microsoft.com/en-us/office/invalid-file-names-and-file-types-in-onedrive-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa?ui=en-us&rs=en-us&ad=us#individualfilesize

**Comment by Cnly** [comment]
@Dibbyo456 Yes, from that link it sounds like they're still rolling out the feature:

> new 100 GB limit is rolling out now, and will be everywhere by the end of June 2020

**Comment by ncw** [comment]
I'll merge this now then. I don't think 1.53 will be out before the end of June 2020 and that is when this would go on the website.

**Pull request merged**
