### PR TITLE
swift: Avoid unnecessary container versioning check

### PR DESCRIPTION
**Pull request by joec4i**
#### What is the purpose of this change?

This optimizes the Swift backend by avoiding unnecessary container versioning checks during the update process. The check is only required for large objects with a non-empty list of segments, which could be a rare case depending on scenarios.

#### Was the change discussed in an issue or in the forum before?

N/A

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by joec4i** [comment]
@ncw do you mind having a look at this one? It's a small change that'll save many unneeded requests if the number of objects is high. Sorry I didn't add new test cases because it doesn't seem necessary. But please let me know :)

**Comment by ncw** [comment]
Can you check the integration tests run OK with this change? (As in `cd backend/swift` then `go test -v -remote yourswiftremote:`)

If so I'm happy to merge - thank you!

**Comment by joec4i** [comment]
Thanks @ncw . Integration tests against `TestSwiftAIO:` still look good. Please find the output below. I've also rebased my branch since there were unrelated linting errors from the github workflow. Hopefully the next run will be green.

```
$ go test -v -remote TestSwiftAIO:
=== RUN   TestInternalUrlEncode
--- PASS: TestInternalUrlEncode (0.00s)
=== RUN   TestInternalShouldRetryHeaders
--- PASS: TestInternalShouldRetryHeaders (1.00s)
=== RUN   TestIntegration
    fstests.go:446: Using remote "TestSwiftAIO:"
2024/02/18 19:45:06 NOTICE: TestSwiftAIO: Starting server
2024/02/18 19:45:12 NOTICE: Config file "/home/joe.cai/.config/rclone/rclone.conf" not found - using defaults
=== RUN   TestIntegration/FsCheckWrap
    fstests.go:487: Not a wrapping Fs
=== RUN   TestIntegration/FsCommand
    fstests.go:515: No commands in this remote
=== RUN   TestIntegration/FsRmdirNotFound
=== RUN   TestIntegration/FsString
=== RUN   TestIntegration/FsName
=== RUN   TestIntegration/FsRoot
=== RUN   TestIntegration/FsRmdirEmpty
=== RUN   TestIntegration/FsMkdir
=== RUN   TestIntegration/FsMkdir/FsMkdirRmdirSubdir
    fstest.go:243: Filtering empty directory "dir"
    fstest.go:243: Filtering empty directory "dir/subdir"
    fstest.go:243: Filtering empty directory "dir"
=== RUN   TestIntegration/FsMkdir/FsListEmpty
=== RUN   TestIntegration/FsMkdir/FsListDirEmpty
=== RUN   TestIntegration/FsMkdir/FsListRDirEmpty
=== RUN   TestIntegration/FsMkdir/FsListDirNotFound
=== RUN   TestIntegration/FsMkdir/FsListRDirNotFound
=== RUN   TestIntegration/FsMkdir/FsEncoding
=== RUN   TestIntegration/FsMkdir/FsEncoding/control_chars
    fstests.go:712: testing "␀␁␂␃␄␅␆␇␈␉␊␋␌␍␎␏␐␑␒␓␔␕␖␗␘␙␚␛␜␝␞␟␡"
=== RUN   TestIntegration/FsMkdir/FsEncoding/dot
    fstests.go:712: testing "．"
=== RUN   TestIntegration/FsMkdir/FsEncoding/dot_dot
    fstests.go:712: testing "．．"
=== RUN   TestIntegration/FsMkdir/FsEncoding/punctuation
    fstests.go:712: testing "!\"#$%&'()*+,-.／:;<=>?@[\\]^_`{|}~"
=== RUN   TestIntegration/FsMkdir/FsEncoding/leading_space
    fstests.go:712: testing " leading space"
=== RUN   TestIntegration/FsMkdir/FsEncoding/leading_tilde
    fstests.go:712: testing "~leading tilde"
=== RUN   TestIntegration/FsMkdir/FsEncoding/leading_CR
    fstests.go:712: testing "␍leading CR"
=== RUN   TestIntegration/FsMkdir/FsEncoding/leading_LF
    fstests.go:712: testing "␊leading LF"
=== RUN   TestIntegration/FsMkdir/FsEncoding/leading_HT
    fstests.go:712: testing "␉leading HT"
=== RUN   TestIntegration/FsMkdir/FsEncoding/leading_VT
    fstests.go:712: testing "␋leading VT"
=== RUN   TestIntegration/FsMkdir/FsEncoding/leading_dot
    fstests.go:712: testing ".leading dot"
=== RUN   TestIntegration/FsMkdir/FsEncoding/trailing_space
    fstests.go:712: testing "trailing space "
=== RUN   TestIntegration/FsMkdir/FsEncoding/trailing_CR
    fstests.go:712: testing "trailing CR␍"
=== RUN   TestIntegration/FsMkdir/FsEncoding/trailing_LF
    fstests.go:712: testing "trailing LF␊"
=== RUN   TestIntegration/FsMkdir/FsEncoding/trailing_HT
    fstests.go:712: testing "trailing HT␉"
=== RUN   TestIntegration/FsMkdir/FsEncoding/trailing_VT
    fstests.go:712: testing "trailing VT␋"
=== RUN   TestIntegration/FsMkdir/FsEncoding/trailing_dot
    fstests.go:712: testing "trailing dot."
=== RUN   TestIntegration/FsMkdir/FsEncoding/invalid_UTF-8
    fstests.go:712: testing "invalid utf-8\xfe"
=== RUN   TestIntegration/FsMkdir/FsEncoding/URL_encoding
    fstests.go:712: testing "test%46.txt"
=== RUN   TestIntegration/FsMkdir/FsNewObjectNotFound
=== RUN   TestIntegration/FsMkdir/FsPutError
=== RUN   TestIntegration/FsMkdir/FsPutZeroLength
=== RUN   TestIntegration/FsMkdir/FsOpenWriterAt
    fstests.go:785: FS has no OpenWriterAt interface
=== RUN   TestIntegration/FsMkdir/FsOpenChunkWriter
    fstests.go:818: FS has no OpenChunkWriter interface
=== RUN   TestIntegration/FsMkdir/FsChangeNotify
    fstests.go:867: FS has no ChangeNotify interface
=== RUN   TestIntegration/FsMkdir/FsPutFiles
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsListDirFile2
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsListRDirFile2
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsListR
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsListRSubdir
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsListDirRoot
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsListRDirRoot
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsListSubdir
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsListRSubdir#01
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsListLevel2
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsListRLevel2
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsListFile1
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsNewObject
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsNewObjectCaseInsensitive
    fstests.go:1120: Not Case Insensitive
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsListFile1and2
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsNewObjectDir
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsPurge
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsPurgeRoot
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsCopy
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsMove
    fstests.go:1265: FS has no Mover interface
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsDirMove
    fstests.go:1336: FS has no DirMover interface
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsRmdirFull
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsPrecision
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectString
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectFs
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectRemote
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectHashes
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectModTime
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectMimeType
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectMetadata
    fstests.go:1500: Metadata method not supported
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectSetModTime
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectSize
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectOpen
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectOpenSeek
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectOpenRange
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectPartialRead
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectUpdate
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectStorable
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsIsFile
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsIsFile/FsRoot
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsIsFileNotFound
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FromRoot
    fstests.go:1727: Opening root remote "TestSwiftAIO:" path "rclone-test-viwojey9xenaxiy4hanaxok2" from "TestSwiftAIO:rclone-test-viwojey9xenaxiy4hanaxok2"
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FromRoot/List
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FromRoot/ListEntries
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FromRoot/ListR
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FromRoot/Put
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FromRoot/Put/Remove
=== RUN   TestIntegration/FsMkdir/FsPutFiles/PublicLink
    fstests.go:1820: FS has no PublicLinker interface
=== RUN   TestIntegration/FsMkdir/FsPutFiles/SetTier
    fstests.go:420: FS has no SetTier & GetTier interfaces
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectCheckWrap
    fstests.go:1925: Not a wrapping Fs
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectRemove
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectAbout
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsPutStream
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsPutStream/0
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsPutStream/100
=== RUN   TestIntegration/FsMkdir/FsPutFiles/Internal
=== RUN   TestIntegration/FsMkdir/FsPutFiles/Internal/NoChunk
=== RUN   TestIntegration/FsMkdir/FsPutFiles/Internal/WithChunk
=== RUN   TestIntegration/FsMkdir/FsPutFiles/Internal/WithChunkFail
=== RUN   TestIntegration/FsMkdir/FsPutFiles/Internal/CopyLargeObject
=== RUN   TestIntegration/FsMkdir/FsPutChunked
=== RUN   TestIntegration/FsMkdir/FsPutChunked/100
=== RUN   TestIntegration/FsMkdir/FsPutChunked/100/99
=== RUN   TestIntegration/FsMkdir/FsPutChunked/100/99/Streamed
=== RUN   TestIntegration/FsMkdir/FsPutChunked/100/100
=== RUN   TestIntegration/FsMkdir/FsPutChunked/100/100/Streamed
=== RUN   TestIntegration/FsMkdir/FsPutChunked/100/201
=== RUN   TestIntegration/FsMkdir/FsPutChunked/100/201/Streamed
=== RUN   TestIntegration/FsMkdir/FsPutChunked/128
=== RUN   TestIntegration/FsMkdir/FsPutChunked/128/127
=== RUN   TestIntegration/FsMkdir/FsPutChunked/128/127/Streamed
=== RUN   TestIntegration/FsMkdir/FsPutChunked/128/128
=== RUN   TestIntegration/FsMkdir/FsPutChunked/128/128/Streamed
=== RUN   TestIntegration/FsMkdir/FsPutChunked/128/257
=== RUN   TestIntegration/FsMkdir/FsPutChunked/128/257/Streamed
=== RUN   TestIntegration/FsMkdir/FsPutChunked/97.656Ki
=== RUN   TestIntegration/FsMkdir/FsPutChunked/97.656Ki/99999
=== RUN   TestIntegration/FsMkdir/FsPutChunked/97.656Ki/99999/Streamed
=== RUN   TestIntegration/FsMkdir/FsPutChunked/97.656Ki/100000
=== RUN   TestIntegration/FsMkdir/FsPutChunked/97.656Ki/100000/Streamed
=== RUN   TestIntegration/FsMkdir/FsPutChunked/97.656Ki/200001
=== RUN   TestIntegration/FsMkdir/FsPutChunked/97.656Ki/200001/Streamed
=== RUN   TestIntegration/FsMkdir/FsPutChunked/97.657Ki
=== RUN   TestIntegration/FsMkdir/FsPutChunked/97.657Ki/100000
=== RUN   TestIntegration/FsMkdir/FsPutChunked/97.657Ki/100000/Streamed
=== RUN   TestIntegration/FsMkdir/FsPutChunked/97.657Ki/100001
=== RUN   TestIntegration/FsMkdir/FsPutChunked/97.657Ki/100001/Streamed
=== RUN   TestIntegration/FsMkdir/FsPutChunked/97.657Ki/200003
=== RUN   TestIntegration/FsMkdir/FsPutChunked/97.657Ki/200003/Streamed
=== RUN   TestIntegration/FsMkdir/FsPutChunked/682.731Ki
=== RUN   TestIntegration/FsMkdir/FsPutChunked/682.731Ki/699116
=== RUN   TestIntegration/FsMkdir/FsPutChunked/682.731Ki/699116/Streamed
=== RUN   TestIntegration/FsMkdir/FsPutChunked/682.731Ki/699117
=== RUN   TestIntegration/FsMkdir/FsPutChunked/682.731Ki/699117/Streamed
=== RUN   TestIntegration/FsMkdir/FsPutChunked/682.731Ki/1398235
=== RUN   TestIntegration/FsMkdir/FsPutChunked/682.731Ki/1398235/Streamed
=== RUN   TestIntegration/FsMkdir/FsPutChunked/2Mi
=== RUN   TestIntegration/FsMkdir/FsPutChunked/2Mi/2097151
=== RUN   TestIntegration/FsMkdir/FsPutChunked/2Mi/2097151/Streamed
=== RUN   TestIntegration/FsMkdir/FsPutChunked/2Mi/2097152
=== RUN   TestIntegration/FsMkdir/FsPutChunked/2Mi/2097152/Streamed
=== RUN   TestIntegration/FsMkdir/FsPutChunked/2Mi/4194305
=== RUN   TestIntegration/FsMkdir/FsPutChunked/2Mi/4194305/Streamed
=== RUN   TestIntegration/FsMkdir/FsCopyChunked
    fstests.go:2173: *swift.Fs does not implement SetCopyCutoff
=== RUN   TestIntegration/FsMkdir/FsUploadUnknownSize
=== RUN   TestIntegration/FsMkdir/FsUploadUnknownSize/FsPutUnknownSize
=== RUN   TestIntegration/FsMkdir/FsUploadUnknownSize/FsUpdateUnknownSize
=== RUN   TestIntegration/FsMkdir/FsRootCollapse
=== RUN   TestIntegration/FsShutdown
    fstests.go:2331: Shutdown method not supported
2024/02/18 19:45:48 NOTICE: TestSwiftAIO: Stopped server
--- PASS: TestIntegration (42.57s)
    --- SKIP: TestIntegration/FsCheckWrap (0.00s)
    --- SKIP: TestIntegration/FsCommand (0.00s)
    --- PASS: TestIntegration/FsRmdirNotFound (0.01s)
    --- PASS: TestIntegration/FsString (0.00s)
    --- PASS: TestIntegration/FsName (0.00s)
    --- PASS: TestIntegration/FsRoot (0.00s)
    --- PASS: TestIntegration/FsRmdirEmpty (0.02s)
    --- PASS: TestIntegration/FsMkdir (25.56s)
        --- PASS: TestIntegration/FsMkdir/FsMkdirRmdirSubdir (0.03s)
        --- PASS: TestIntegration/FsMkdir/FsListEmpty (0.01s)
        --- PASS: TestIntegration/FsMkdir/FsListDirEmpty (0.01s)
        --- PASS: TestIntegration/FsMkdir/FsListRDirEmpty (0.01s)
        --- PASS: TestIntegration/FsMkdir/FsListDirNotFound (0.01s)
        --- PASS: TestIntegration/FsMkdir/FsListRDirNotFound (0.01s)
        --- PASS: TestIntegration/FsMkdir/FsEncoding (4.73s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/control_chars (0.35s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/dot (0.20s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/dot_dot (0.21s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/punctuation (0.27s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/leading_space (0.24s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/leading_tilde (0.23s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/leading_CR (0.25s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/leading_LF (0.25s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/leading_HT (0.25s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/leading_VT (0.23s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/leading_dot (0.24s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/trailing_space (0.25s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/trailing_CR (0.29s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/trailing_LF (0.30s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/trailing_HT (0.27s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/trailing_VT (0.31s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/trailing_dot (0.22s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/invalid_UTF-8 (0.21s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/URL_encoding (0.16s)
        --- PASS: TestIntegration/FsMkdir/FsNewObjectNotFound (0.02s)
        --- PASS: TestIntegration/FsMkdir/FsPutError (0.03s)
        --- PASS: TestIntegration/FsMkdir/FsPutZeroLength (0.06s)
        --- SKIP: TestIntegration/FsMkdir/FsOpenWriterAt (0.00s)
        --- SKIP: TestIntegration/FsMkdir/FsOpenChunkWriter (0.00s)
        --- SKIP: TestIntegration/FsMkdir/FsChangeNotify (0.00s)
        --- PASS: TestIntegration/FsMkdir/FsPutFiles (14.14s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsListDirFile2 (0.09s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsListRDirFile2 (0.06s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsListR (0.01s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsListRSubdir (0.01s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsListDirRoot (0.03s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsListRDirRoot (0.02s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsListSubdir (0.02s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsListRSubdir#01 (0.02s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsListLevel2 (0.02s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsListRLevel2 (0.01s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsListFile1 (0.03s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsNewObject (0.01s)
            --- SKIP: TestIntegration/FsMkdir/FsPutFiles/FsNewObjectCaseInsensitive (0.00s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsListFile1and2 (0.02s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsNewObjectDir (0.01s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsPurge (0.11s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsPurgeRoot (0.11s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsCopy (0.07s)
            --- SKIP: TestIntegration/FsMkdir/FsPutFiles/FsMove (0.00s)
            --- SKIP: TestIntegration/FsMkdir/FsPutFiles/FsDirMove (0.00s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsRmdirFull (2.58s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsPrecision (0.00s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/ObjectString (2.00s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/ObjectFs (2.00s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/ObjectRemote (1.50s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/ObjectHashes (1.13s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/ObjectModTime (0.84s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/ObjectMimeType (0.63s)
            --- SKIP: TestIntegration/FsMkdir/FsPutFiles/ObjectMetadata (0.48s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/ObjectSetModTime (0.82s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/ObjectSize (0.15s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/ObjectOpen (0.20s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/ObjectOpenSeek (0.11s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/ObjectOpenRange (0.11s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/ObjectPartialRead (0.01s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/ObjectUpdate (0.05s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/ObjectStorable (0.01s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsIsFile (0.03s)
                --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsIsFile/FsRoot (0.00s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsIsFileNotFound (0.02s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FromRoot (0.13s)
                --- PASS: TestIntegration/FsMkdir/FsPutFiles/FromRoot/List (0.02s)
                --- PASS: TestIntegration/FsMkdir/FsPutFiles/FromRoot/ListEntries (0.01s)
                --- PASS: TestIntegration/FsMkdir/FsPutFiles/FromRoot/ListR (0.02s)
                --- PASS: TestIntegration/FsMkdir/FsPutFiles/FromRoot/Put (0.08s)
                    --- PASS: TestIntegration/FsMkdir/FsPutFiles/FromRoot/Put/Remove (0.03s)
            --- SKIP: TestIntegration/FsMkdir/FsPutFiles/PublicLink (0.00s)
            --- SKIP: TestIntegration/FsMkdir/FsPutFiles/SetTier (0.00s)
            --- SKIP: TestIntegration/FsMkdir/FsPutFiles/ObjectCheckWrap (0.00s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/ObjectRemove (0.03s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/ObjectAbout (0.01s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsPutStream (0.21s)
                --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsPutStream/0 (0.10s)
                --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsPutStream/100 (0.11s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/Internal (0.33s)
                --- PASS: TestIntegration/FsMkdir/FsPutFiles/Internal/NoChunk (0.03s)
                --- PASS: TestIntegration/FsMkdir/FsPutFiles/Internal/WithChunk (0.07s)
                --- PASS: TestIntegration/FsMkdir/FsPutFiles/Internal/WithChunkFail (0.09s)
                --- PASS: TestIntegration/FsMkdir/FsPutFiles/Internal/CopyLargeObject (0.15s)
        --- PASS: TestIntegration/FsMkdir/FsPutChunked (5.99s)
            --- PASS: TestIntegration/FsMkdir/FsPutChunked/100 (0.71s)
                --- PASS: TestIntegration/FsMkdir/FsPutChunked/100/99 (0.17s)
                    --- PASS: TestIntegration/FsMkdir/FsPutChunked/100/99/Streamed (0.14s)
                --- PASS: TestIntegration/FsMkdir/FsPutChunked/100/100 (0.17s)
                    --- PASS: TestIntegration/FsMkdir/FsPutChunked/100/100/Streamed (0.13s)
                --- PASS: TestIntegration/FsMkdir/FsPutChunked/100/201 (0.37s)
                    --- PASS: TestIntegration/FsMkdir/FsPutChunked/100/201/Streamed (0.19s)
            --- PASS: TestIntegration/FsMkdir/FsPutChunked/128 (0.72s)
                --- PASS: TestIntegration/FsMkdir/FsPutChunked/128/127 (0.17s)
                    --- PASS: TestIntegration/FsMkdir/FsPutChunked/128/127/Streamed (0.13s)
                --- PASS: TestIntegration/FsMkdir/FsPutChunked/128/128 (0.18s)
                    --- PASS: TestIntegration/FsMkdir/FsPutChunked/128/128/Streamed (0.14s)
                --- PASS: TestIntegration/FsMkdir/FsPutChunked/128/257 (0.37s)
                    --- PASS: TestIntegration/FsMkdir/FsPutChunked/128/257/Streamed (0.19s)
            --- PASS: TestIntegration/FsMkdir/FsPutChunked/97.656Ki (0.81s)
                --- PASS: TestIntegration/FsMkdir/FsPutChunked/97.656Ki/99999 (0.20s)
                    --- PASS: TestIntegration/FsMkdir/FsPutChunked/97.656Ki/99999/Streamed (0.15s)
                --- PASS: TestIntegration/FsMkdir/FsPutChunked/97.656Ki/100000 (0.19s)
                    --- PASS: TestIntegration/FsMkdir/FsPutChunked/97.656Ki/100000/Streamed (0.15s)
                --- PASS: TestIntegration/FsMkdir/FsPutChunked/97.656Ki/200001 (0.42s)
                    --- PASS: TestIntegration/FsMkdir/FsPutChunked/97.656Ki/200001/Streamed (0.20s)
            --- PASS: TestIntegration/FsMkdir/FsPutChunked/97.657Ki (0.78s)
                --- PASS: TestIntegration/FsMkdir/FsPutChunked/97.657Ki/100000 (0.18s)
                    --- PASS: TestIntegration/FsMkdir/FsPutChunked/97.657Ki/100000/Streamed (0.14s)
                --- PASS: TestIntegration/FsMkdir/FsPutChunked/97.657Ki/100001 (0.18s)
                    --- PASS: TestIntegration/FsMkdir/FsPutChunked/97.657Ki/100001/Streamed (0.14s)
                --- PASS: TestIntegration/FsMkdir/FsPutChunked/97.657Ki/200003 (0.41s)
                    --- PASS: TestIntegration/FsMkdir/FsPutChunked/97.657Ki/200003/Streamed (0.20s)
            --- PASS: TestIntegration/FsMkdir/FsPutChunked/682.731Ki (1.10s)
                --- PASS: TestIntegration/FsMkdir/FsPutChunked/682.731Ki/699116 (0.27s)
                    --- PASS: TestIntegration/FsMkdir/FsPutChunked/682.731Ki/699116/Streamed (0.19s)
                --- PASS: TestIntegration/FsMkdir/FsPutChunked/682.731Ki/699117 (0.27s)
                    --- PASS: TestIntegration/FsMkdir/FsPutChunked/682.731Ki/699117/Streamed (0.18s)
                --- PASS: TestIntegration/FsMkdir/FsPutChunked/682.731Ki/1398235 (0.56s)
                    --- PASS: TestIntegration/FsMkdir/FsPutChunked/682.731Ki/1398235/Streamed (0.28s)
            --- PASS: TestIntegration/FsMkdir/FsPutChunked/2Mi (1.88s)
                --- PASS: TestIntegration/FsMkdir/FsPutChunked/2Mi/2097151 (0.46s)
                    --- PASS: TestIntegration/FsMkdir/FsPutChunked/2Mi/2097151/Streamed (0.28s)
                --- PASS: TestIntegration/FsMkdir/FsPutChunked/2Mi/2097152 (0.46s)
                    --- PASS: TestIntegration/FsMkdir/FsPutChunked/2Mi/2097152/Streamed (0.29s)
                --- PASS: TestIntegration/FsMkdir/FsPutChunked/2Mi/4194305 (0.95s)
                    --- PASS: TestIntegration/FsMkdir/FsPutChunked/2Mi/4194305/Streamed (0.48s)
        --- SKIP: TestIntegration/FsMkdir/FsCopyChunked (0.00s)
        --- PASS: TestIntegration/FsMkdir/FsUploadUnknownSize (0.23s)
            --- PASS: TestIntegration/FsMkdir/FsUploadUnknownSize/FsPutUnknownSize (0.10s)
            --- PASS: TestIntegration/FsMkdir/FsUploadUnknownSize/FsUpdateUnknownSize (0.13s)
        --- PASS: TestIntegration/FsMkdir/FsRootCollapse (0.01s)
    --- SKIP: TestIntegration/FsShutdown (0.00s)
PASS
ok  	github.com/rclone/rclone/backend/swift	43.579s
```

**Review by ncw — APPROVED** [review]
This is great - thank you :-)

**Pull request merged**
