### PR TITLE
Description field for remotes

### PR DESCRIPTION
**Pull request by Paul-Stern**
#### What is the purpose of this change?
The task was to add description fields for remotes.

#### Was the change discussed in an issue or in the forum before?
Fixes the issue: https://github.com/rclone/rclone/issues/4391

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [ ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Review by ncw — COMMENTED** [review]
I think instead of adding `fs.OptDescription` to every backend, I would add it once in the backend registration code. How does that sound?

https://github.com/rclone/rclone/blob/2f5685b40562cf764da673543245ddb13c049a4a/fs/registry.go#L281

**Comment by Paul-Stern** [comment]
> I think instead of adding `fs.OptDescription` to every backend, I would add it once in the backend registration code. How does that sound?
> 
> https://github.com/rclone/rclone/blob/2f5685b40562cf764da673543245ddb13c049a4a/fs/registry.go#L281

That sound great! I didn't know that was possible. Thanks! I will try to fix it.

**Comment by ncw** [comment]
> It seems to be easier to start a new branch and open new PR instead of making changes to this branch (though I guess I know how to do that). Shall I do it this way?

You can make the changes locally then use `git commit --amend` to alter the commit. Then use `git push --force` to overwrite the commit in this branch.

That would be my preferred way of working and if we find anything else which needs changing you'll then know how to adjust your commit.

**Comment by Paul-Stern** [comment]
Changes have been made. Any feedback is welcome again =)

**Review by ncw — COMMENTED** [review]
I think this is looking great now :-)

I think I'd like the `rclone listremotes --long` to be all one one line though as I bet people are parsing its output...

You can find the max length of the type field in the same way is it finds the max remote length, then line up all the descriptions. I think that would look neat.

What do you think?

**Comment by Paul-Stern** [comment]
Well, sorry, I didn't quite catch your idea. What do you mean by 'line up' all the descriptions? Do you mean they should be on the same line as remotes and their types and that's why remote types length should be taken into account? And so as people are parsing this that is why it all should be on one line. Something like that?

**Comment by Paul-Stern** [comment]
I tried to introduce your idea in this comment: https://github.com/Paul-Stern/rclone/commit/8504c1fa709997e128bfb90df384fe8b72829aad . Did I get it right? Is it better now? If this commit is fine, I will merge it to the PR branch.

**Comment by ncw** [comment]
Yes that looks like the right idea.

So before you'd have something like

```
remote1    drive
secret     crypt
longername onedrive
something  s3
iforgot    union
```

And afterwards something like this

```
remote1    drive    work google drive for stuff
secret     crypt    secrets stored on work google drive
longername onedrive my home office 365 account
something  s3       test for project XYZ
iforgot    union    union of work google drive and onedrive
```

**Comment by Paul-Stern** [comment]
Introduced commits to the branch. Please, have a look. Just let me know if any actions are needed =)

**Comment by ncw** [comment]
> BTW, having a closer look at you example, I realised there is no word 'Description' so I removed it in one of the commits: [Paul-Stern@ab2524a](https://github.com/Paul-Stern/rclone/commit/ab2524a7eeeb833a7890f0b8da3d176e9d95d3c6) Shall I introduce this commit to PR branch too?

Yes I think I prefer no `Description: ` - the other columns don't have signifiers either.

Yes please add it to this PR and I'll squash the commits at the end.

**Comment by Paul-Stern** [comment]
Done! Hope it can be merged now =)

**Comment by Paul-Stern** [comment]
@ncw Any news on this PR? The work seems complete, is there still anything to be done so the branch could be merged?

**Review by ncw — APPROVED** [review]
This looks great now - thank you.

Sorry for the delay - I'll merge now :-)

**Comment by ncw** [comment]
PS I have fixed up the test that was failing - hopefully this goes green and we can merge.

**Comment by ncw** [comment]
Thank you :-)

**Pull request merged**
