### PR TITLE
#5319 add ghcr option for docker images, and use the upstream build actions

### PR DESCRIPTION
**Pull request by RichardoC**
#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by RichardoC** [comment]
I'm only changing the beta workflow with this PR so that we can confirm everything works as expected. If it does then we can also change the release workflow too.

**Comment by ncw** [comment]
I'd like a bit more discussion of this please?

I'm not sure I understand the reason for the change.

Will the images still end up in docker hub as they do currently?

Thanks

**Comment by RichardoC** [comment]
Of course!

This will push images to both Dockerhub and GHCR, the section starting on line 53 is how this configured. If a registry is defined, it'll push to there and if there isn't (eg rclone/rclone:beta) it'll be pushed to dockerhub.


If you'd prefer this can we re-scoped to only change the workflow to the upstream actions and then discussions about dockerhub (or not) can take place in #5219

**Comment by ncw** [comment]
I see!

It seems like a good idea to upload packages in both places.

Using the github supported actions is a good idea also I think.

I don't think that is the right issue number though? I think you meant #5319

I'll run the CI on this and see what happens!

**Comment by RichardoC** [comment]
Thanks, I've just updated the issue reference. Would you prefer this as 2 PRs? One for the github actions, and one for the ghcr one?
I'm then planning to follow up with the equivalents but for the release steps

**Comment by RichardoC** [comment]
Is that windows failure a known issue?

**Comment by albertony** [comment]
> Is that windows failure a known issue?

I triggered a rebuild, and its gone.

**Comment by RichardoC** [comment]
Yeah, I don't think you'll be able to run this from a test branch but I'll change this to be manually triggered after merging for testing if that suits?

**Comment by ncw** [comment]
How do you manually trigger it? Does it have to be on master first, or can I do it somehow from this PR?

**Comment by RichardoC** [comment]
Unfortunately I don't think we can run the workflow on this PR since it's a branch outside this project. 

I had hoped you'd have the option to manually trigger it somehow when I added the `on: workflow_dispatch` section but I don't know where that would show as an option. If you can't find that I guess we'll have to merge it?
If that's the case I could add this as a separate workflow, and you could keep both old and new version until you're confident and then we remove the old one?
Sorry I can't give an easy answer on this!

**Comment by ncw** [comment]
Hi @RichardoC - apologies for the delay on this.

Now I have 1.62 out of the door I can experiment with this. Do you agree merging it is the right thing to do and we can see if it works properly?

Do I need to set up GHCR for use with rclone?

Thanks

**Comment by RichardoC** [comment]
Yeah, I think this is still worth trying as it gives you users multiple options for obtaining the container images. I believe this PR should be all that is needed. 
On one of my personal [projects](https://github.com/RichardoC/kube-audit-rest) this was all that was needed to make the images available via github

**Review by ncw — APPROVED** [review]
That is great - thank you :-)

I'll merge this now and we can see how well it works. If it works OK then can you do a PR for the release build too?

I'll probably have a 1.63.3 to do in a week or two so it can get tested for real then.

**Comment by RichardoC** [comment]
Sounds good, happy to raise that when we're happy with this on the beta image!

**Comment by ncw** [comment]
I put the correct credentials in, and this one got a bit further

https://github.com/rclone/rclone/actions/runs/4448657379/jobs/7811754107

```
#2 [internal] load build definition from Dockerfile-alpine
#2 transferring dockerfile: 2B done
#2 DONE 0.0s
ERROR: failed to solve: failed to read dockerfile: open /tmp/buildkit-mount3670878127/Dockerfile-alpine: no such file or directory
Error: buildx failed with: ERROR: failed to solve: failed to read dockerfile: open /tmp/buildkit-mount3670878127/Dockerfile-alpine: no such file or directory
```

I'll leave it broken over the weekend - that isn't a problem.

**Pull request merged**
