### PR TITLE
Box: Refresh token when using jwt auth - Fixes #4901 

### PR DESCRIPTION
**Pull request by dbramwell**
#### What is the purpose of this change?

Refresh the auth token when using box, jwt and box config.json file

#### Was the change discussed in an issue or in the forum before?

[#4091 ](https://github.com/rclone/rclone/issues/4091)

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by dbramwell** [comment]
@ncw I wanted to just use the Renewer from oauthutil, passing a different function to do the renew. But then I realised that the renewer in there only runs when [uploads are pending](https://github.com/rclone/rclone/blob/master/lib/oauthutil/renew.go#L41), so when running a simple `ls`, rclone still failed to refresh the token. So I created a new renewer that does it whether there are uploads pending or not. I'm not sure that this is the correct thing to do but it works.

I'm unsure where the token currently get's refreshed in `ls` cases (seemed to be somewhere in the `pacer` calls [here](https://github.com/rclone/rclone/blob/master/backend/box/box.go#L547). Maybe it's better for that to be altered for jwt and the `jwtutil.Renew` to be removed? I'm unsure about how it all works though.

**Comment by ncw** [comment]
Apologies for the delay in looking at this.

> I'm unsure where the token currently get's refreshed in `ls` cases (seemed to be somewhere in the `pacer` calls [here](https://github.com/rclone/rclone/blob/master/backend/box/box.go#L547). Maybe it's better for that to be altered for jwt and the `jwtutil.Renew` to be removed? I'm unsure about how it all works though.

The token gets renewed by the oauth library golang.org/x/oauth2 - you use its http Transport and it magically refreshes the token when it expires.

The oauth library may be able to help you directly - it understands JWTs (unlike me :-)

> So I created a new renewer that does it whether there are uploads pending or not. I'm not sure that this is the correct thing to do but it works.

That will only work for uploads though as that is the only place we call the token renewer at the moment.

You could hook it into the Signer call for the rest library which is called before every HTTP transaction

https://github.com/rclone/rclone/blob/6893ce0bbf81f9d4264f12af3e62f21ae7ba5ced/backend/sugarsync/sugarsync.go#L422 (uploaded in 15-30 mins)

You have to be a little careful about recursion - I should probably add a "NoSigner" option to `rest.Opts`.

The most efficient hook might be to add a timer on refresh of the token to when it next needs refreshing since we know exactly when it expires. We should examine the expiry on startup and refresh if necessary then or set the timer, then set it again on every refresh.

**Comment by dbramwell** [comment]
No problem, thanks for taking a look.

> That will only work for uploads though as that is the only place we call the token renewer at the moment.

I removed the check for whether uploads are taking place in the jwt renewer [here](https://github.com/rclone/rclone/pull/4107/files#diff-e57f15e014bec6db19b4be39ba7eff78R41). It does work, but I don't like the idea of kicking off an async process to renew the token when running one short command like `ls` or whatever.

I'm still looking at this when I get time, currently hoping to use `golang.org/x/oauth2` like you said. I think I tried this last time but hit an issue with it [not supporting keys with a passphrase](https://github.com/rclone/rclone/blob/master/vendor/golang.org/x/oauth2/jwt/jwt.go#L42). Will see where I get to and hopefully have changes by the weekend.

**Comment by ncw** [comment]
> > That will only work for uploads though as that is the only place we call the token renewer at the moment.
> 
> I removed the check for whether uploads are taking place in the jwt renewer [here](https://github.com/rclone/rclone/pull/4107/files#diff-e57f15e014bec6db19b4be39ba7eff78R41), compared to the oauthutil one [here](https://github.com/rclone/rclone/blob/master/lib/oauthutil/renew.go#L41). It does work, but I don't like the idea of kicking off an async process to renew the token when running one short command like `ls` or whatever.

You are right. I missed the fact that we kick off a go routine to received the expired notification so ignore what I said above, sorry!

Maybe the neatest thing to do would be to add a mode to the existing token renewer so that it always renews the token when it expires. That could be as simple as calling `Start()` as part of the initialisation (so uploads is always > 0) with no code changes needed which should simplify the code and mean that we don't need to duplicate the token renewer code.

> I'm still looking at this when I get time, currently hoping to use `golang.org/x/oauth2` like you said. I think I tried this last time but hit an issue with it [not supporting keys with a passphrase](https://github.com/rclone/rclone/blob/master/vendor/golang.org/x/oauth2/jwt/jwt.go#L42). Will see where I get to and hopefully have changes by the weekend.

Thanks

**Comment by dbramwell** [comment]
> Maybe the neatest thing to do would be to add a mode to the existing token renewer so that it always renews the token when it expires. That could be as simple as calling Start() as part of the initialisation (so uploads is always > 0) with no code changes needed which should simplify the code and mean that we don't need to duplicate the token renewer code.

Cool, I've taken that approach.

I took a look into using the jwt stuff in the oauth2 package and eventually hit the issue of not being able to set query params which will be solved by [this](https://github.com/golang/oauth2/pull/390/files), which once I saw I realised I'd definitely seen when I was trying to add the jwt stuff in the first place, I should have taken note! Once that's merged I think a lot my code from the Config function in jwtutil can be removed, and the renewer stuff could possibly be simplified too.

**Comment by ncw** [comment]
> Cool, I've taken that approach.

Rather than changing the interface of the token renewer, I'd I've just called `Start()` from the box backend. I'm sorry about my stream of consciousness ramble above - I should have been more explicit!

> I took a look into using the jwt stuff in the oauth2 package and eventually hit the issue of not being able to set query params which will be solved by [this](https://github.com/golang/oauth2/pull/390/files), which once I saw I realised I'd definitely seen when I was trying to add the jwt stuff in the first place, I should have taken note! Once that's merged I think a lot my code from the Config function in jwtutil can be removed, and the renewer stuff could possibly be simplified too.

That is good news! I put a note on the PR asking for a status check.

**Comment by dbramwell** [comment]
> Rather than changing the interface of the token renewer, I'd I've just called Start() from the box backend. I'm sorry about my stream of consciousness ramble above - I should have been more explicit!

No problem. Done!

I'm not sure why the two actions are failing, running on my local I don't seem to get errors.

**Comment by ncw** [comment]
> I'm not sure why the two actions are failing, running on my local I don't seem to get errors.

Unfortunately they are tests which fail occasionally that I haven't had time to fix :-( 

Your changes look great now - thank you :-)

I'll merge them now.

**Pull request merged**
