### PR TITLE
cmd: Enable SIGINFO handler on FreeBSD, NetBSD, OpenBSD and Dragonfly BSD

### LINKED ISSUE #6536: cmd: Enable SIGINFO handler on FreeBSD
#### The associated forum post URL from `https://forum.rclone.org`
N/A

#### What is your current rclone version (output from `rclone version`)?
rclone v1.59.2-DEV
- os/version: freebsd 13.1-release-p2 (64 bit)                         - os/kernel: 13.1-release-p2 (amd64)                                   - os/type: freebsd                                                     
- os/arch: amd64                                                       
- go/version: go1.19.2                                                 
- go/linking: dynamic                                                  
- go/tags: none

(Installed from FreeBSD Ports/Quarterly)

#### What problem are you are trying to solve?
The SIGINFO handler (which is triggered when Ctrl-T is pressed) is currently only enabled for builds on Darwin. This should be enabled on FreeBSD as well (as it follows the same semantics as Darwin).

#### How do you think rclone should be changed to solve that?
The proposed enhancement requires 2 minor changes, namely:

In file https://github.com/rclone/rclone/blob/master/cmd/siginfo_darwin.go

From
`//go:build darwin`
`// +build darwin`
to
`//go:build darwin || freebsd`
`// +build darwin freebsd`

and in file https://github.com/rclone/rclone/blob/master/cmd/siginfo_others.go

From
`//go:build !darwin`
`// +build !darwin`
to
`//go:build !darwin && !freebsd`
`// +build !darwin !freebsd`

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

### PR DESCRIPTION
**Pull request by x3-apptech**
#### Was the change discussed in an issue or in the forum before?

resolves #6536

#### Checklist

- [X] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by x3-apptech** [comment]
With the 2nd commit the build should work.

**Comment by x3-apptech** [comment]
Renamed siginfo_darwin.go to generic siginfo_bsd.go. "bsd" is not a listed as a known GOOS (see cmd/siginfo_darwin.go), so build should now succeed on both Darwin and FreeBSD.

**Comment by x3-apptech** [comment]
For the sake of completeness, also enable it on NetBSD and Dragonfly BSD (on OpenBSD, Ctrl-T is disabled by default).

**Review by ncw — APPROVED** [review]
This looks great now - thank you.

I'll merge it now.

**Pull request merged**
