### PR TITLE
Reduce S3 mounts memory consumption by 75%

### PR DESCRIPTION
**Pull request by agterdenbos**
#### What is the purpose of this change?

The purpose is to reduce the amount of memory for S3 mounts to prevent the system going out of memory. This is my first step. Maybe we need some further optimizations for buckets with many objects.

The [type Object struct](https://github.com/rclone/rclone/blob/85eb9776bd5b700e0be0cdd23dab280f0d2d946d/backend/s3/s3.go#L2186) contains a string pointer `storageClass`. The existing function newObjectWithInfo on [line 2805](https://github.com/rclone/rclone/blob/85eb9776bd5b700e0be0cdd23dab280f0d2d946d/backend/s3/s3.go#L2805) sets this pointer to a string created by xmlutil.XMLToStruct full of references. As a result, many gigabytes of XMLNode stay in memory. Copying this string reduces the memory consumption.

To observe the difference, I mounted an S3 bucket and listed a folder with 77438 files. Afterwards I analyzed the heap with pprof. For this example it shows 75% memory reduction. With more files the difference can be (much) larger. 

Pprof before applying this change:
```
[ec2-user@ip-10-64-56-184 ~]$ go tool pprof -text http://localhost:5572/debug/pprof/heap
Fetching profile over HTTP from http://localhost:5572/debug/pprof/heap
Saved profile in /home/ec2-user/pprof/pprof.rclone.alloc_objects.alloc_space.inuse_objects.inuse_space.125.pb.gz
File: rclone
Type: inuse_space
Time: Aug 18, 2022 at 10:03pm (UTC)
Showing nodes accounting for 233.39MB, 97.24% of 240.03MB total
Dropped 59 nodes (cum <= 1.20MB)
      flat  flat%   sum%        cum   cum%
  118.02MB 49.17% 49.17%   166.54MB 69.38%  github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil.XMLToStruct
   41.50MB 17.29% 66.46%    41.50MB 17.29%  github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil.(*XMLNode).findNamespaces (inline)
   34.50MB 14.37% 80.83%    34.50MB 14.37%  path.Join
   12.50MB  5.21% 86.04%    12.50MB  5.21%  github.com/rclone/rclone/vfs.newFile
      10MB  4.17% 90.21%       10MB  4.17%  github.com/rclone/rclone/backend/s3.(*Fs).newObjectWithInfo
    5.35MB  2.23% 92.44%    20.86MB  8.69%  github.com/rclone/rclone/vfs.(*Dir)._readDirFromEntries
    4.50MB  1.87% 94.31%     5.02MB  2.09%  encoding/xml.(*Decoder).name
       3MB  1.25% 95.56%        3MB  1.25%  github.com/rclone/rclone/vfs.newDir
       2MB  0.83% 96.39%        2MB  0.83%  encoding/xml.CharData.Copy (inline)
    1.52MB  0.63% 97.03%   228.56MB 95.22%  github.com/rclone/rclone/vfs.(*Dir).ReadDirAll
    0.50MB  0.21% 97.24%     4.54MB  1.89%  runtime.main
         0     0% 97.24%   233.39MB 97.24%  bazil.org/fuse/fs.(*Server).Serve.func1
         0     0% 97.24%   233.39MB 97.24%  bazil.org/fuse/fs.(*Server).handleRequest
         0     0% 97.24%   233.39MB 97.24%  bazil.org/fuse/fs.(*Server).serve
         0     0% 97.24%     5.02MB  2.09%  encoding/xml.(*Decoder).Token
         0     0% 97.24%     5.02MB  2.09%  encoding/xml.(*Decoder).nsname
         0     0% 97.24%     5.02MB  2.09%  encoding/xml.(*Decoder).rawToken
         0     0% 97.24%   166.54MB 69.38%  github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run
         0     0% 97.24%   166.02MB 69.16%  github.com/aws/aws-sdk-go/aws/request.(*Request).Send
         0     0% 97.24%   166.02MB 69.16%  github.com/aws/aws-sdk-go/aws/request.(*Request).sendRequest
         0     0% 97.24%   166.54MB 69.38%  github.com/aws/aws-sdk-go/private/protocol/restxml.Unmarshal
         0     0% 97.24%   166.54MB 69.38%  github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil.UnmarshalXML
         0     0% 97.24%   166.02MB 69.16%  github.com/aws/aws-sdk-go/service/s3.(*S3).ListObjectsV2WithContext
         0     0% 97.24%   176.52MB 73.54%  github.com/rclone/rclone/backend/s3.(*Fs).List
         0     0% 97.24%    10.50MB  4.38%  github.com/rclone/rclone/backend/s3.(*Fs).itemToDirEntry
         0     0% 97.24%   176.52MB 73.54%  github.com/rclone/rclone/backend/s3.(*Fs).list
         0     0% 97.24%   166.02MB 69.16%  github.com/rclone/rclone/backend/s3.(*Fs).list.func1
         0     0% 97.24%   176.52MB 73.54%  github.com/rclone/rclone/backend/s3.(*Fs).listDir
         0     0% 97.24%    10.50MB  4.38%  github.com/rclone/rclone/backend/s3.(*Fs).listDir.func1
         0     0% 97.24%     4.84MB  2.02%  github.com/rclone/rclone/cmd/mount.(*Dir).Lookup
         0     0% 97.24%   228.56MB 95.22%  github.com/rclone/rclone/cmd/mount.(*Dir).ReadDirAll
         0     0% 97.24%   166.02MB 69.16%  github.com/rclone/rclone/fs.pacerInvoker
         0     0% 97.24%   176.52MB 73.54%  github.com/rclone/rclone/fs/list.DirSorted
         0     0% 97.24%   166.02MB 69.16%  github.com/rclone/rclone/lib/pacer.(*Pacer).Call
         0     0% 97.24%   166.02MB 69.16%  github.com/rclone/rclone/lib/pacer.(*Pacer).call
         0     0% 97.24%     4.84MB  2.02%  github.com/rclone/rclone/vfs.(*Dir).Stat
         0     0% 97.24%   197.38MB 82.23%  github.com/rclone/rclone/vfs.(*Dir)._readDir
         0     0% 97.24%     4.84MB  2.02%  github.com/rclone/rclone/vfs.(*Dir).stat
         0     0% 97.24%    34.50MB 14.37%  github.com/rclone/rclone/vfs.(*File).Path
         0     0% 97.24%    34.50MB 14.37%  github.com/rclone/rclone/vfs.Nodes.Less
         0     0% 97.24%     4.04MB  1.68%  runtime.doInit
         0     0% 97.24%    34.50MB 14.37%  sort.Sort
         0     0% 97.24%       31MB 12.92%  sort.doPivot
         0     0% 97.24%        3MB  1.25%  sort.insertionSort
         0     0% 97.24%     1.50MB  0.62%  sort.medianOfThree
         0     0% 97.24%    34.50MB 14.37%  sort.quickSort
```

Pprof after applying this change:
```
[ec2-user@ip-10-64-56-184 ~]$ go tool pprof -text http://localhost:5572/debug/pprof/heap
Fetching profile over HTTP from http://localhost:5572/debug/pprof/heap
Saved profile in /home/ec2-user/pprof/pprof.rclone.alloc_objects.alloc_space.inuse_objects.inuse_space.127.pb.gz
File: rclone
Build ID: f746d148c55fec0790fa283bcbf33ff7ee9a0d9d
Type: inuse_space
Time: Aug 18, 2022 at 10:08pm (UTC)
Showing nodes accounting for 55.06MB, 100% of 55.06MB total
      flat  flat%   sum%        cum   cum%
      16MB 29.07% 29.07%       16MB 29.07%  github.com/rclone/rclone/vfs.newFile
    9.50MB 17.26% 46.32%     9.50MB 17.26%  github.com/rclone/rclone/backend/s3.(*Fs).newObjectWithInfo
    5.15MB  9.35% 55.68%     5.15MB  9.35%  bazil.org/fuse.AppendDirent (inline)
       5MB  9.08% 64.76%        5MB  9.08%  github.com/rclone/rclone/vfs.newDir
    4.52MB  8.20% 72.96%    25.52MB 46.35%  github.com/rclone/rclone/vfs.(*Dir)._readDirFromEntries
    4.50MB  8.17% 81.13%     4.50MB  8.17%  github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil.XMLToStruct
    2.28MB  4.15% 85.28%     2.28MB  4.15%  bazil.org/fuse/fs.(*Server).saveNode
    1.50MB  2.72% 88.01%     1.50MB  2.72%  github.com/rclone/rclone/fs.NewDir (inline)
    0.57MB  1.03% 89.03%     0.57MB  1.03%  google.golang.org/protobuf/internal/strs.(*Builder).AppendFullName
    0.53MB  0.96% 89.99%     0.53MB  0.96%  github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_hdfs.init
    0.50MB  0.92% 90.91%     0.50MB  0.92%  google.golang.org/protobuf/types/descriptorpb.init
    0.50MB  0.91% 91.82%     0.50MB  0.91%  regexp/syntax.(*compiler).inst (inline)
    0.50MB  0.91% 92.73%     0.50MB  0.91%  github.com/rclone/rclone/cmd/ncdu.init
    0.50MB  0.91% 93.64%     0.50MB  0.91%  net/http.(*Transport).queueForIdleConn
    0.50MB  0.91% 94.55%     0.50MB  0.91%  net/http.(*ServeMux).Handle
    0.50MB  0.91% 95.46%     0.50MB  0.91%  encoding/pem.Decode
    0.50MB  0.91% 96.37%     0.50MB  0.91%  github.com/spf13/cobra.(*Command).initDefaultCompletionCmd
    0.50MB  0.91% 97.28%     0.50MB  0.91%  runtime.malg
    0.50MB  0.91% 98.18%     0.50MB  0.91%  github.com/spf13/pflag.NewFlagSet (inline)
    0.50MB  0.91% 99.09%     0.50MB  0.91%  runtime.(*scavengerState).init
    0.50MB  0.91%   100%        7MB 12.72%  github.com/rclone/rclone/cmd/mount.(*Dir).Lookup
         0     0%   100%    48.95MB 88.91%  bazil.org/fuse/fs.(*Server).Serve.func1
         0     0%   100%    48.95MB 88.91%  bazil.org/fuse/fs.(*Server).handleRequest
         0     0%   100%     2.28MB  4.15%  bazil.org/fuse/fs.(*Server).saveLookup
         0     0%   100%    48.95MB 88.91%  bazil.org/fuse/fs.(*Server).serve
         0     0%   100%     0.50MB  0.91%  crypto/tls.(*Conn).HandshakeContext (inline)
         0     0%   100%     0.50MB  0.91%  crypto/tls.(*Conn).clientHandshake
         0     0%   100%     0.50MB  0.91%  crypto/tls.(*Conn).handshakeContext
         0     0%   100%     0.50MB  0.91%  crypto/tls.(*Conn).verifyServerCertificate
         0     0%   100%     0.50MB  0.91%  crypto/tls.(*clientHandshakeState).doFullHandshake
         0     0%   100%     0.50MB  0.91%  crypto/tls.(*clientHandshakeState).handshake
         0     0%   100%     0.50MB  0.91%  crypto/x509.(*CertPool).AppendCertsFromPEM
         0     0%   100%     0.50MB  0.91%  crypto/x509.(*Certificate).Verify
         0     0%   100%     0.50MB  0.91%  crypto/x509.initSystemRoots
         0     0%   100%     0.50MB  0.91%  crypto/x509.loadSystemRoots
         0     0%   100%     0.50MB  0.91%  crypto/x509.systemRootsPool (inline)
         0     0%   100%     0.50MB  0.91%  github.com/aws/aws-sdk-go/aws/corehandlers.glob..func3
         0     0%   100%     0.50MB  0.91%  github.com/aws/aws-sdk-go/aws/corehandlers.sendFollowRedirects
         0     0%   100%     0.50MB  0.91%  github.com/aws/aws-sdk-go/aws/credentials.(*ChainProvider).Retrieve
         0     0%   100%     0.50MB  0.91%  github.com/aws/aws-sdk-go/aws/credentials.(*Credentials).GetWithContext.func1
         0     0%   100%     0.50MB  0.91%  github.com/aws/aws-sdk-go/aws/credentials.(*Credentials).singleRetrieve
         0     0%   100%     0.50MB  0.91%  github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds.(*EC2RoleProvider).Retrieve
         0     0%   100%     0.50MB  0.91%  github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds.(*EC2RoleProvider).RetrieveWithContext
         0     0%   100%     0.50MB  0.91%  github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds.requestCredList
         0     0%   100%     0.50MB  0.91%  github.com/aws/aws-sdk-go/aws/ec2metadata.(*EC2Metadata).GetMetadataWithContext
         0     0%   100%     0.50MB  0.91%  github.com/aws/aws-sdk-go/aws/ec2metadata.(*EC2Metadata).getToken
         0     0%   100%     0.50MB  0.91%  github.com/aws/aws-sdk-go/aws/ec2metadata.(*tokenProvider).fetchTokenHandler
         0     0%   100%        5MB  9.08%  github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run
         0     0%   100%        5MB  9.08%  github.com/aws/aws-sdk-go/aws/request.(*Request).Send
         0     0%   100%     0.50MB  0.91%  github.com/aws/aws-sdk-go/aws/request.(*Request).Sign
         0     0%   100%        5MB  9.08%  github.com/aws/aws-sdk-go/aws/request.(*Request).sendRequest
         0     0%   100%     0.50MB  0.91%  github.com/aws/aws-sdk-go/internal/sync/singleflight.(*Group).doCall
         0     0%   100%     4.50MB  8.17%  github.com/aws/aws-sdk-go/private/protocol/restxml.Unmarshal
         0     0%   100%     4.50MB  8.17%  github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil.UnmarshalXML
         0     0%   100%     4.50MB  8.17%  github.com/aws/aws-sdk-go/service/s3.(*S3).ListObjectsV2WithContext
         0     0%   100%     0.57MB  1.03%  github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_hdfs.file_ClientNamenodeProtocol_proto_init
         0     0%   100%     0.57MB  1.03%  github.com/colinmarc/hdfs/v2/internal/protocol/hadoop_hdfs.init.2
         0     0%   100%    15.50MB 28.16%  github.com/rclone/rclone/backend/s3.(*Fs).List
         0     0%   100%       11MB 19.98%  github.com/rclone/rclone/backend/s3.(*Fs).itemToDirEntry
         0     0%   100%    15.50MB 28.16%  github.com/rclone/rclone/backend/s3.(*Fs).list
         0     0%   100%     4.50MB  8.17%  github.com/rclone/rclone/backend/s3.(*Fs).list.func1
         0     0%   100%    15.50MB 28.16%  github.com/rclone/rclone/backend/s3.(*Fs).listDir
         0     0%   100%       11MB 19.98%  github.com/rclone/rclone/backend/s3.(*Fs).listDir.func1
         0     0%   100%     4.50MB  8.17%  github.com/rclone/rclone/backend/s3.(*v2List).List
         0     0%   100%        1MB  1.82%  github.com/rclone/rclone/cmd.Main
         0     0%   100%     0.50MB  0.91%  github.com/rclone/rclone/cmd.initConfig
         0     0%   100%    34.52MB 62.70%  github.com/rclone/rclone/cmd/mount.(*Dir).ReadDirAll
         0     0%   100%     0.50MB  0.91%  github.com/rclone/rclone/cmd/test/info.init.0
         0     0%   100%     4.50MB  8.17%  github.com/rclone/rclone/fs.pacerInvoker
         0     0%   100%     0.50MB  0.91%  github.com/rclone/rclone/fs/fshttp.(*Transport).RoundTrip
         0     0%   100%    15.50MB 28.16%  github.com/rclone/rclone/fs/list.DirSorted
         0     0%   100%     0.50MB  0.91%  github.com/rclone/rclone/fs/rc/rcserver.Start
         0     0%   100%     0.50MB  0.91%  github.com/rclone/rclone/fs/rc/rcserver.newServer
         0     0%   100%     4.50MB  8.17%  github.com/rclone/rclone/lib/pacer.(*Pacer).Call
         0     0%   100%     4.50MB  8.17%  github.com/rclone/rclone/lib/pacer.(*Pacer).call
         0     0%   100%    34.52MB 62.70%  github.com/rclone/rclone/vfs.(*Dir).ReadDirAll
         0     0%   100%     6.50MB 11.81%  github.com/rclone/rclone/vfs.(*Dir).Stat
         0     0%   100%    41.02MB 74.51%  github.com/rclone/rclone/vfs.(*Dir)._readDir
         0     0%   100%     6.50MB 11.81%  github.com/rclone/rclone/vfs.(*Dir).stat
         0     0%   100%        1MB  1.82%  github.com/spf13/cobra.(*Command).Execute (inline)
         0     0%   100%        1MB  1.82%  github.com/spf13/cobra.(*Command).ExecuteC
         0     0%   100%     0.50MB  0.91%  github.com/spf13/cobra.(*Command).Flags
         0     0%   100%     0.50MB  0.91%  github.com/spf13/cobra.(*Command).execute
         0     0%   100%     0.50MB  0.91%  github.com/spf13/cobra.(*Command).preRun (inline)
         0     0%   100%     0.57MB  1.03%  google.golang.org/protobuf/internal/filedesc.(*File).unmarshalSeed
         0     0%   100%     0.57MB  1.03%  google.golang.org/protobuf/internal/filedesc.(*Message).unmarshalSeed
         0     0%   100%     0.57MB  1.03%  google.golang.org/protobuf/internal/filedesc.Builder.Build
         0     0%   100%     0.57MB  1.03%  google.golang.org/protobuf/internal/filedesc.appendFullName
         0     0%   100%     0.57MB  1.03%  google.golang.org/protobuf/internal/filedesc.newRawFile
         0     0%   100%     0.57MB  1.03%  google.golang.org/protobuf/internal/filetype.Builder.Build
         0     0%   100%        1MB  1.82%  main.main
         0     0%   100%     0.50MB  0.91%  net/http.(*Client).Do (inline)
         0     0%   100%     0.50MB  0.91%  net/http.(*Client).do
         0     0%   100%     0.50MB  0.91%  net/http.(*Client).send
         0     0%   100%     0.50MB  0.91%  net/http.(*ServeMux).HandleFunc (inline)
         0     0%   100%     0.50MB  0.91%  net/http.(*Transport).RoundTrip (inline)
         0     0%   100%     0.50MB  0.91%  net/http.(*Transport).getConn
         0     0%   100%     0.50MB  0.91%  net/http.(*Transport).roundTrip
         0     0%   100%     0.50MB  0.91%  net/http.(*persistConn).addTLS.func2
         0     0%   100%     0.50MB  0.91%  net/http.send
         0     0%   100%     0.50MB  0.91%  regexp/syntax.(*compiler).compile
         0     0%   100%     0.50MB  0.91%  regexp/syntax.(*compiler).rune
         0     0%   100%     0.50MB  0.91%  runtime.bgscavenge
         0     0%   100%     2.60MB  4.72%  runtime.doInit
         0     0%   100%     3.60MB  6.54%  runtime.main
         0     0%   100%     0.50MB  0.91%  runtime.newproc.func1
         0     0%   100%     0.50MB  0.91%  runtime.newproc1
         0     0%   100%     0.50MB  0.91%  runtime.systemstack
         0     0%   100%     0.50MB  0.91%  sync.(*Once).Do (inline)
         0     0%   100%     0.50MB  0.91%  sync.(*Once).doSlow
```

#### Was the change discussed in an issue or in the forum before?
Yes, see
https://forum.rclone.org/t/rclone-mount-s3-bucket-runs-out-of-memory-after-many-directory-listings/32441/5

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by agterdenbos** [comment]
I replaced strings.Clone in my commit by a normal assignment, which is already good enough to get rid of the original string.

**Comment by ncw** [comment]
Sorry I missed this PR - it looks really useful.

I'm going to merge this for 1.61 - it might need updating since there are more things that rclone pulls out of the info now (to do with metadata).

Have you got time to update it?

If not I will do it.

Thank you for finding this.

**Comment by ncw** [comment]
@agterdenbos ready for me to merge?

**Comment by aaaaaaajsjsjjsjxhhb2** [comment]
bro..seriouly...
-------- Original message --------From: Nick Craig-Wood ***@***.***> Date: 12/5/22  15:17  (GMT-06:00) To: rclone/rclone ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [rclone/rclone] Reduce S3 mounts memory consumption by 75% (PR #6393) 
@agterdenbos ready for me to merge?

**Comment by agterdenbos** [comment]
> @agterdenbos ready for me to merge?

Yes, would be great! Thanks :)

**Comment by ncw** [comment]
Thank you!

I'll see if this idea has more to give for 1.61

**Comment by aaaaaaajsjsjjsjxhhb2** [comment]
bro...seriously....your r like fucking up the vibe...lol

**Pull request merged**
