### PR TITLE
docs: cleanup header levels

### PR DESCRIPTION
**Pull request by albertony**
#### What is the purpose of this change?

Some cleanup in the usage, install and download docs. Mainly related to headers.

Ensure each page starts with a level 1 header (`# header`), and then only use level 2 or higher for sections below. E.g. existing install doc uses header level 1 for "Autostart", above [Autostart on Windows](https://rclone.org/install/#autostart-on-windows), but then this does not get a anchor on hover-over and also is not listed in the contents box to the right. And existing downloads doc have several level 1 headers but only one level 2 header, and then only the level 2 header "Script download and install" is shown in the contents box to the right.

The [usage](https://rclone.org/docs/) docs started with level 2 header called "Configure". So for consistency I introduced a level 1 header with the page name, "Usage", and *tried* to come up with something short to write there to avoid having an empty level 1 header followed only by a level 2 header.
Edit: I see that existing Changelog and Privacy Policy pages does have an empty level 1 header followed by a level 2 header. It does not look too bad, so I can just do the same in Usage. One thing is that the usage site is at the /docs url, so feels like som sort of main/entry point for documentation. So I tried to write a short, generic intro to rclone doc. But open for suggestions to do this differently.

#### Checklist

- [X] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] ~I have added tests for all changes in this PR if appropriate.~
- [X] I have added documentation for the changes if appropriate.
- [X] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [X] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ncw** [comment]
... I presume you've noticed that level 2 and 3 headers go in the contents box on the RHS of the web page?

**Comment by albertony** [comment]
> ... I presume you've noticed that level 2 and 3 headers go in the contents box on the RHS of the web page?

Yes, exactly. Take existing https://rclone.org/downloads/ page for example: It contains several headers in the page, but only one entry in the RHS box: `Script download and install`. Because the headers are level 1. I changed that to have only one level 1 header at the top, and made the rest level 2++.

**Review by ncw — APPROVED** [review]
This looks great - thank you - please merge :-)

I imagine there is more of this to come!

**Comment by albertony** [comment]
> I imagine there is more of this to come!

By the way: Do you @ncw have an idea why there are no contents box at all on this page: https://rclone.org/bugs/

**Pull request merged**
