### PR TITLE
Update onedrive.go 修改高级配置用以支持世纪互联onedrive支持

### PR DESCRIPTION
**Pull request by 742481030**
修改高级配置用以支持世纪互联onedrive支持,

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [ ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by Cnly** [comment]
@742481030 Thanks for your interest and effort in enhancing this part of rclone. However, the features this PR implements look like a subset of #3973. What do you think? Also, there seem to be large chunks of unclarified code deletion and behaviour changes. Do you have any comments on that? My suggestion is that we'll keep our focus on the previous PR and close this one for now.

P.S. You might have accidentally included the endpoint of the Sharepoint instance that you're using; you may want to do a force push to delete that.

**Comment by 742481030** [comment]
> @ 742481030感谢您对增强rclone的这一部分的关注和投入。但是，此PR实现的功能看起来像[＃3973](https://github.com/rclone/rclone/pull/3973)的子集。你怎么看？另外，似乎还有大量未澄清的代码删除和行为更改。您对此有何评论？我的建议是，我们将继续关注先前的PR，并暂时关闭此PR。
> 
> PS：您可能不小心包含了您正在使用的Sharepoint实例的端点。您可能需要强行将其删除。

我没留留意过那么久远的pr,在chaina 目前流传的pr 是更加古老的,并且无法正常上传文件和无法支持sharepoint
我是给予1.51版本修改而来,可能1.54增加了一些新特性,  由于我不是一个优秀的go程序员,我大量的工作是php
Sharepoint实例的端点是注释是因为 世纪互联并不支持 /sharepoint的driveid api  形式的api,可能由于权限不足,大量的中国同胞找我修改rclone 让以支持世纪互联,所有我提交了此pr,我删除了大量的可能对我来说毫无意义的注释,如果可以我希望官方予以支持他,可能由于非中国大陆用户并没有测试账户.
目前改补丁我已经给我的大陆小伙伴用上了,

**Comment by 742481030** [comment]
> @ 742481030感谢您对增强rclone的这一部分的关注和投入。但是，此PR实现的功能看起来像[＃3973](https://github.com/rclone/rclone/pull/3973)的子集。你怎么看？另外，似乎还有大量未澄清的代码删除和行为更改。您对此有何评论？我的建议是，我们将继续关注先前的PR，并暂时关闭此PR。
> 
> PS：您可能不小心包含了您正在使用的Sharepoint实例的端点。您可能需要强行将其删除。

我将尝试3974是否适用于中国大陆.,原谅我是个php程序员,不喜欢代码中大量注释,可能给其他人带来困然

**Comment by 742481030** [comment]
> @742481030 Thanks for your interest and effort in enhancing this part of rclone. However, the features this PR implements look like a subset of #3973. What do you think? Also, there seem to be large chunks of unclarified code deletion and behaviour changes. Do you have any comments on that? My suggestion is that we'll keep our focus on the previous PR and close this one for now.
> 
> P.S. You might have accidentally included the endpoint of the Sharepoint instance that you're using; you may want to do a force push to delete that.

感觉代码要重构 太混乱了,无用注释实在太多

**Comment by NyaMisty** [comment]
Maybe you should use English instead of Chinese in a international project which requires cooperation with people from various countries 👎 
Note: You've also posted bunches of Chinese comment in other PR/issues

**Pull request closed without merging**
