### PR TITLE
s3: limit upload concurrency

### PR DESCRIPTION
**Pull request by ajankovic**
To allow concurrent FS operations, limiter is moved from function
to the file system object level so it can limit all concurrency for
the fs.

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ncw** [comment]
This is the way the b2 backend works, but uses `fs.Config.Transfers` as the limit.

The s3 backend uploader evolved from the s3manager in the SDK so allows `--transfers` * `--s3-concurrency` uploads at once. Your change will limit that to `--s3-concurrency` transfers....

Why do you want to reduce the concurrency?

**Comment by ivandeex** [comment]
@ajankovic ping

**Comment by ivandeex** [comment]
@ajankovic ?

**Comment by ajankovic** [comment]
@ncw It is needed to limit concurrency for the single backend instance. When limiting concurrency of the operations usually you want more global limit that provides exact maximum that you don't want to go over. For example this is important for the buffer allocation since each new concurrent upload allocates it's own buffer. When you have `transfers * limit` calculation then each new transfer could potentially span new concurrent uploads which hog resources.

**Comment by ivandeex** [comment]
For note: a.t.m. we have pending https://github.com/rclone/rclone/pull/4821 that seeks to adds more concurrency using `--checkers` and https://github.com/rclone/rclone/pull/4172 that limits concurrency stronger using `--s3-concurrency`.

**Comment by ncw** [comment]
On reading the code again, I think that this will change the behaviour of the s3 backend too much.

By default we have

      --s3-upload-concurrency int       Concurrency for multipart uploads. (default 4)

This change makes that the total number of uploads possible, so setting `--transfers` bigger than 4 will have no effect.

I'm going to close this PR, but I would accept one which introduces an new config variable which defaulted to off, which limited the overall concurrency.

**Pull request closed without merging**
