### PR TITLE
Free Space Column

### PR DESCRIPTION
**Pull request by zero77**
Add an extra column showing how much free space is given for each cloud storage system.

#### What is the purpose of this change?

To let people know how much free space is given for each cloud storage system.

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by zero77** [comment]
@ncw
> I think that is useful info, but I don't think the rclone docs is the right place for it as we try not to keep provider information that can change quickly in.

> You could make a wiki page with that info in - that is very easy for anyone to update.

That makes sense though, i was trying to provide people with a complete overview. 
Which shows functionality and space all in one place so they can best decide what suits their needs.

**Comment by ncw** [comment]
What we could do is put a link to a new wiki page in the overview doc?

**Comment by ivandeex** [comment]
@zero77 
Do not underestimate the wiki. It already contains tons of useful stuff (well, centi-tons just yet).
See the right side of https://github.com/rclone/rclone/wiki

**Comment by ncw** [comment]
Thank you for your contribution @zero77 . I think our decision is not to merge this as-is. However we would appreciate the same info in [the rclone wiki](https://github.com/ncw/rclone/wiki).

**Pull request closed without merging**
