### PR TITLE
build: replace xgo with NDK for Android builds

### PR DESCRIPTION
**Pull request by x0b**
#### What is the purpose of this change?

Replace xgo (unmaintained) with a standalone NDK-based compiler toolchain for Android builds. Everything works, but I obviously couldn't test the upload step. Binaries for all 4 architectures are written to a `build` folder.

#### Was the change discussed in an issue or in the forum before?

Request: https://github.com/x0b/rcx/issues/123

Related (xgo iOS): https://github.com/rclone/rclone/issues/5124

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ncw** [comment]
That is brilliant - thank you :-)

I'm going to push this to a branch build-ndk to see if the releasing of binaries works.

**Comment by ncw** [comment]
I'm going to merge this now - thank you very much @x0b :-)

You wrote in the commit about the NDK:

> Upgrade together with Go version.

What is the procedure for that?

And how did you choose which androidabi to target for each architecture?

Thank you

**Comment by x0b** [comment]
> What is the procedure for that?

There isn't a fixed procedure - it basically depends on which versions of Go and the NDK toolchain work together. This can sometimes also depend on the specific linker or compiler flags. I mostly wrote that to justify why I'm not using NDK r22 and Go 1.16 - when I tested it, there was a build-breaking incompatibility between those two. IIRC that should be resolved soon.


> And how did you choose which androidabi to target for each architecture?

Do you mean the set of architectures? By popularity of android devices with compatible CPUs.

**Comment by ncw** [comment]
> > What is the procedure for that?
> 
> There isn't a fixed procedure - it basically depends on which versions of Go and the NDK toolchain work together. This can sometimes also depend on the specific linker or compiler flags. I mostly wrote that to justify why I'm not using NDK r22 and Go 1.16 - when I tested it, there was a build-breaking incompatibility between those two. IIRC that should be resolved soon.

Ah OK
 
> > And how did you choose which androidabi to target for each architecture?
> 
> Do you mean the set of architectures? By popularity of android devices with compatible CPUs.

I meant some of the builds are androideabi16 and some are android21 - I was wondering why that was.

**Comment by x0b** [comment]
Well, I just used the maximum possible range, which means API level 16 ("Android 4.1 Jelly Bean") for the 32 bit architectures (armv7, x86) and API level 21 ("Android 5.0 Lollipop") for the 64 bit variants (aarch64/armv8, x64). I think Android only supports 64 bits since API 21.

**Pull request merged**
