### PR TITLE
mailru: accept special folders eg camera-upload (fixes #4025)

### LINKED ISSUE #4025: mail.ru cloud Unknown resource type "camera-upload"
Image 121
Hi,

I get blank list:
```
C:\rclone>rclone --log-file=rclone.log --log-level DEBUG lsd test-mail:/

C:\\rclone>
````
log-file:
```
2020/03/02 12:35:37 DEBUG : rclone: Version "v1.51.0" starting with parameters ["rclone" "--log-file=rclone.log" "--log-level" "DEBUG" "lsd" "test-mail:/"]
2020/03/02 12:35:37 DEBUG : Using config file from "C:\\rclone\\rclone.conf"
2020/03/02 12:35:38 DEBUG : []: Excluding path "/Camera Uploads" from list: Unknown resource type "camera-upload"
2020/03/02 12:35:38 DEBUG : 5 go routines active
2020/03/02 12:35:38 DEBUG : rclone: Version "v1.51.0" finishing with parameters ["rclone" "--log-file=rclone.log" "--log-level" "DEBUG" "lsd" "test-mail:/"]
```

### PR DESCRIPTION
**Pull request by ivandeex**
#### What is the purpose of this change?

When mailru requests contents of a mailru folder, server returns _kind_ field for resource items. Currently the mailru backend supports only two kinds: _file_ and _folder_. As users report in https://github.com/rclone/rclone/issues/4025, mailru can return other kinds, and this makes such operations as _ls_ or _size_ fail even if unknown resource lies deep below requested directory.

Further investigation shows (see manual test procedure in a comment below) that all currently known kinds mark special types of folders: _camera-upload_ is a directory created by the mailru mobile application for automatically synchronized photos, _shared_ is a directory that was shared by owner with other mailru cloud users. The sister open-source project [WebDavMailRuCloud](https://github.com/yar229/WebDavMailRuCloud) (WDMRC) also supports the _mounted_ kind (I guess it means a folder shared by another user with you) as can be seen from its sources (see [Api/Base/Repos/MailRuCloud/DtoImport.cs](https://github.com/yar229/WebDavMailRuCloud/blob/caa028725e16c05c04663dfb44f05afa55a3dbd1/MailRuCloud/MailRuCloudApi/Base/Repos/MailRuCloud/DtoImport.cs#L188)).

This patch makes rclone treat all special kinds as a directory. Cloud resources with empty or unknown _kind_ will still result in a error. However, the backend will support a _quirk_ (hidden backend option intended for debugging known and future issues) `unkowndirs` to make rclone accept unknown/future kinds of folders but print a log message. Like other quirks, this one will be removed if connected problem is not reported for a year.

#### Was the change discussed in an issue or in the forum before?

Yes. See https://github.com/rclone/rclone/issues/4025 and https://github.com/yar229/WebDavMailRuCloud/issues/58

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

#### Notes

* testing this change involves manual operations (see procedure below) and cannot be included into rclone test suite
* this change is a bugfix and needs no documentation

### CODE REVIEW

**Comment by ivandeex** [comment]
Quick integration test suite passed for me:
https://github.com/ivandeex/rclone/runs/1266357910?check_suite_focus=true

Here follows the **manual unit test** procedure:

Download beta version of rclone with this fix applied from https://beta.rclone.org or from the fork repository https://github.com/ivandeex/rclone/releases/tag/v1.53-mailru-camera-4:
```
curl -sLo rclone.test https://github.com/ivandeex/rclone/releases/download/v1.53-mailru-camera-4/rclone-linux-amd64
chmod +x rclone.test
./rclone.test version
```

Register a cloud.mail.ru account and create a mailru remote.

Upload a test file to mailru:
```
./rclone.test copy ./test.bin TestMailru:test
```

Login to mailru, open your test folder https://cloud.mail.ru/home/test/ and share it with another mailru user as shown in the attached screenshot.

Install mailru mobile application (eg  https://play.google.com/store/apps/details?id=ru.mail.cloud) on your smartphone, login to your account and give it access to files and gallery.

Listing your mailru files or getting their size with rclone should work without errors:
```
./rclone.test ls -vvv TestMailru:

2020/10/17 00:50:52 DEBUG : []: [Camera Uploads]: folder has type "camera-upload"
2020/10/17 00:50:52 DEBUG : []: [test]: folder has type "shared"
2020/10/17 00:50:52 DEBUG : []: [/test]: folder has type "shared"
1562941440 test/test.bin
2020/10/17 00:50:52 DEBUG : []: [/Camera Uploads]: folder has type "camera-upload"
  1974340 Camera Uploads/IMG_20200701_005905.jpg
   120630 Camera Uploads/IMG_20200701_035702.jpg
   103083 Camera Uploads/IMG_20200701_035733.jpg

./rclone.test size -vvv TestMailru:

2020/10/17 01:09:46 DEBUG : []: [Camera Uploads]: folder has type "camera-upload"
2020/10/17 01:09:46 DEBUG : []: [test]: folder has type "shared"
2020/10/17 01:09:46 DEBUG : []: [/test]: folder has type "shared"
2020/10/17 01:09:46 DEBUG : []: [/Camera Uploads]: folder has type "camera-upload"
Total objects: 14
Total size: 1.476 GBytes (1585245207 Bytes)
```

@ncw Please review

**Comment by ivandeex** [comment]
A user reported that this patch fixes their issue https://github.com/rclone/rclone/issues/4025#issuecomment-711240304

**Review by ncw — APPROVED** [review]
This change looks good to me - thanks for your comprehensive writeup @ivandeex :-)

Please merge :-)

I think it is probably too big for the stable branch unless you desperately think it is affecting users.

**Comment by ivandeex** [comment]
Will merge on master only (I'm not that desperate 🤓 )

**Pull request merged**
