### PR TITLE
Implement --auth-proxy for 'rclone serve http'

### PR DESCRIPTION
**Pull request by baurmatt**
#### What is the purpose of this change?

Implement --auth-proxy for 'rclone serve http'. Mostly copied from the implementation of `rclone serve webdav`.

#### Was the change discussed in an issue or in the forum before?
https://github.com/rclone/rclone/issues/6779
https://forum.rclone.org/t/make-backend-configuration-configurable-per-http-request-on-serve-http/36202/3

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [ ] I have added tests for all changes in this PR if appropriate.
  - I've copied it from `serve webdav`. Couldn't find any tests to copy 🙈 
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ncw** [comment]
This is the line which does the auth proxy tests for webdav

https://github.com/rclone/rclone/blob/5bd6e3d1e9cbdc9e71a9c075bc6efa872f73753e/cmd/serve/webdav/webdav_test.go#L80

However this test framework relies on the server being able to write files so it can run the corresponding rclone backend tests against it.

The HTTP backend, being read only (this should be specified in the VFS options) makes this particular framework useless.

You can take a look to see how the proxy tests work - they are fairly complicated as they involve running the test binary itself as the proxy so it will work on all platforms.

**Comment by baurmatt** [comment]
@ncw Thanks for taking a look! :) I've fixed the linting issues. However, it's unclear to me how I'm supposed to implemented tests for this specific feature. I can't figure what part of the webdav tests are responsible for testing the auth proxy feature there. To best of my knowledge, none of the commands implemeting AuthProxy (ftp, sftp, webdav) do actual testing of it in their corresponding *_test.go files.

**Comment by ncw** [comment]
> Thanks for taking a look! :) I've fixed the linting issues. However, it's unclear to me how I'm supposed to implemented tests for this specific feature. I can't figure what part of the webdav tests are responsible for testing the auth proxy feature there. To best of my knowledge, none of the commands implemeting AuthProxy (ftp, sftp, webdav) do actual testing of it in their corresponding *_test.go files.

The proxy tests are implemented in this package

https://github.com/rclone/rclone/tree/master/cmd/serve/servetest

Which is called from here

https://github.com/rclone/rclone/blob/5bd6e3d1e9cbdc9e71a9c075bc6efa872f73753e/cmd/serve/webdav/webdav_test.go#L80

Here is how the proxy gets configured

https://github.com/rclone/rclone/blob/5bd6e3d1e9cbdc9e71a9c075bc6efa872f73753e/cmd/serve/servetest/servetest.go#L48-L56

And here is the actual proxy

https://github.com/rclone/rclone/blob/master/cmd/serve/servetest/proxy_code.go

You can't use the `servetest` framework directly, but with a small amount of factoring you could use it to insert the `proxy_code.go` as a proxy and test that this is called properly in a single test in `http_test.go`.

**Comment by baurmatt** [comment]
@ncw Thanks! :) My Go skills aren't good enough for this, sorry!

**Comment by baurmatt** [comment]
Thank you ❤️

**Comment by ncw** [comment]
Tests done in 2dabbe83ac61cd9a70434ef1192270b3c62faaf0 - I took the time to modernise the tests here so it was time well spent!

**Pull request merged**
