### PR TITLE
Add examples for Azure Blob Access Tier to documentation

### PR DESCRIPTION
**Pull request by BobPusateri**
#### What is the purpose of this change?

Improve documentation. Azure Blob access tier values are case-sensitive, though this is not indicated anywhere in the documentation. Adding examples with proper casing.

#### Was the change discussed in an issue or in the forum before?

Not that I can see.

#### Checklist

- [X] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [X] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ncw** [comment]
Can you provide a link to an Azure doc showing the tier names are case sensitive?

The azureblob backend should maybe normalise the case - what do you think?

**Comment by ivandeex** [comment]
@BobPusateri friendly ping

**Comment by ivandeex** [comment]
@ncw

> Can you provide a link to an Azure doc showing the tier names are case sensitive?

I did not find such a document. What I found:
- REST API docs:
  https://docs.microsoft.com/en-us/rest/api/storageservices/set-blob-tier#request-headers
- AccessTier type generated from API description:
  https://github.com/Azure/azure-storage-blob-go/blob/master/azblob/zz_generated_models.go#L96
- SetTier function generated from API description:
  https://github.com/Azure/azure-storage-blob-go/blob/master/azblob/zz_generated_blob.go#L1939

The code never modifies passed value, just hands it over to API server.

> The azureblob backend should maybe normalise the case - what do you think?

I can conclude that even if case normalization works in practice, it is not formally guaranteed.

I suggest that rclone just pass user provided value without modifications.

**Review by ncw — APPROVED** [review]
Thanks for the explanation.

That looks great.

I will merge it now - thank you :-)

**Pull request merged**
