### PR TITLE
backend/tardigrade: backend renamed to storj (tardigrade still works)

### PR DESCRIPTION
**Pull request by elek**
#### What is the purpose of this change?

Tardigrade was [renamed](https://storj.io/blog/introducing-storj-dcs-decentralized-cloud-storage-for-developers) to Storj (or Storj DCS) recently. This change applies the renaming to the rclone backend.

Old `tardigrade` backend is kept, but the existing code (which is moved to `backend/storj`) is reused, the existing `tardigrade` becomes to a shortcut for the code. 

I tested it with both an existing `tardigrade` backend and a new `storj` backend. 

The only code change is making the configurations/options public in `storj` package to make it possible to reuse from `tardigrade` 

#### Was the change discussed in an issue or in the forum before?

Some discussion has been started here:

https://forum.rclone.org/t/backward-compatibility-rules/26569

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ncw** [comment]
@elek - I was hoping for an issue to discuss this on rather than a pull request!

@calebcase - ignoring the backwards compatibility issue for the moment - do you think this is a good idea?

**Comment by olefrost** [comment]
@elek - I was hoping to see some analysis, investigation, and feedback on the proposed 4th option before seeing a pull request!

I was also hoping for an answer to [my forum questions and](https://forum.rclone.org/t/backward-compatibility-rules/26569/5) and some convincing performance data to support your choice.

**Comment by elek** [comment]
> I was hoping to see some analysis, investigation, and feedback on the proposed 4th option before seeing a pull request!

Sure, let's continue the discussion on the forum. I changed the PR to draft to make this state clear.

I was interested if it's possible to organize the code in a way to maintain only in one place but -- for compatibility reasons -- keep the tardigrade backend, too. And when I realized that it's possible, I just uploaded it.

But let's call it as an illustration of one of the potential option.

**Comment by calebcase** [comment]
> @elek - I was hoping for an issue to discuss this on rather than a pull request!
> 
> @calebcase - ignoring the backwards compatibility issue for the moment - do you think this is a good idea?

:+1: This is a great idea

**Comment by ivandeex** [comment]
Great idea and perfect code reuse!

**Comment by elek** [comment]
Closing the PR as @ncw had a better approach (with directly supporting aliases for each backend).

**Pull request closed without merging**
