### PR TITLE
protondrive: improves 2fa and draft error messages

### PR DESCRIPTION
**Pull request by henrybear327**
#### What is the purpose of this change?

The error message during file upload regarding the draft is unclear (e.g. one example is when an upload failed midway, and the upload was re-attempted right after). Though the design was there to deal with this exact situation, it's not well-known to the users (https://github.com/rclone/rclone/issues/6072#issuecomment-1688589547). 

This PR modified the error message to guide the user to use a temporary flag to activate the designed feature. 

The PR also modified the error message for 2FA.

#### Was the change discussed in an issue or in the forum before?

#7251 

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by henrybear327** [comment]
@ncw please correct me if I am wrong - the command line value has priority over the configurator values. This PR is based on this assumption! 

Thank you!

**Comment by Chippit** [comment]
Thanks so much @henrybear327 for your quick work on improving the Proton backend and all its associated features! It's enormously appreciated!

**Comment by ncw** [comment]
> please correct me if I am wrong - the command line value has priority over the configurator values (based on my reading of the function `Overridden` in `registry.go`). This PR is based on this assumption!

It does, yes.

The priority order is specified here https://rclone.org/docs/#precedence

**Review by ncw — APPROVED** [review]
Looks good to me :-)

Please merge!

**Pull request merged**
