### PR TITLE
protondrive: fix xattr parsing

### PR DESCRIPTION
**Pull request by henrybear327**
#### What is the purpose of this change?

Address bug reported [here](https://github.com/rclone/rclone/issues/6072#issuecomment-1660491780).

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Review by ncw — APPROVED** [review]
LGTM :-)

You can ignore the lint error - this is a security problem I'll fix in master shortly.

**Comment by ncw** [comment]
Ready to merge?

You probably want to rebase off master first.

**Comment by henrybear327** [comment]
> Ready to merge?
> 
> You probably want to rebase off master first.

Yes, a rebase will be needed! I will rebase and run the test suite again!

**Comment by henrybear327** [comment]
Pending user [neobrain](https://github.com/neobrain) from the original thread for testing, since I don't have a file with this issue :(

**Comment by neobrain** [comment]
Awesome, thanks for looking into it!

Are there any binaries I can use for testing?

**Comment by henrybear327** [comment]
> Awesome, thanks for looking into it!
> 
> Are there any binaries I can use for testing?

Hi @neobrain,

I will try to build one using the pipeline tomorrow!

Or, you can pull this branch and run `make`!

**Comment by ncw** [comment]
@henrybear327 (I may have told you this before - apologies if I have) if you push to a branch say `pr-7205-protondrive-xattrss` then github actions will build binaries for it. I'd like this to happen for PRs submitted by project members too but I haven't figured out how to do that yet!

**Comment by henrybear327** [comment]
> pr-7205-protondrive-xattrss

Hi @ncw, 

I have tried to push to `pr-7205-protondrive-xattrs` branch. Let's see if it works! :) 

Thank you!

**Comment by henrybear327** [comment]
Gentle ping @neobrain

**Comment by henrybear327** [comment]
The bridge library already merged and fixed this issue! The code changes are already in the master branch.

**Comment by neobrain** [comment]
Took me a bit longer to get around testing this 😅

Happy to report I can `rclone ls` all folders on my proton drive now though, including the ones created back in 2021! 🥳

**Comment by henrybear327** [comment]
> Took me a bit longer to get around testing this 😅
> 
> Happy to report I can `rclone ls` all folders on my proton drive now though, including the ones created back in 2021! 🥳

Hello @neobrain, 

Thank you for the help! :)

**Pull request closed without merging**
