### PR TITLE
Add SeaweedFS

### PR DESCRIPTION
**Pull request by chrislusf**
#### What is the purpose of this change?

Add support for SeaweedFS S3.

#### Was the change discussed in an issue or in the forum before?

Not.

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by chrislusf** [comment]
The `build / windows_386 (pull_request)` failure seems strange and unrelated.

**Review by ncw — COMMENTED** [review]
I think that looks good - thank you :-)

Can you drop the MANUAL.md changes from the commit? That file is auto generated and we generally only updated it on release.

Otherwise looks perfect!

**Comment by chrislusf** [comment]
@ncw Thanks for your review! Updated the PR.

**Review by ncw — APPROVED** [review]
Looks super - thanks :-)

Will merge now.

**Pull request merged**
