### PR TITLE
docs: dynamic architecture selection for rclone pre signed binaries

### PR DESCRIPTION
**Pull request by raxpd**
#### What is the purpose of this change?

Enhance the rclone setup process by introducing dynamic architecture selection. This ensures that users can easily obtain and install the correct package for their specific system architecture without the need for manual intervention and limits architecture incompatibility. 

```bash

# validation test for linux arm64 architecture
pd@mba ~ % curl -O https://downloads.rclone.org/rclone-current-linux-$(uname -m).zip; unzip rclone-current-linux-$(uname -m).zip; cd rclone-*-linux-$(uname -m); file rclone
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15.7M  100 15.7M    0     0  5439k      0  0:00:02  0:00:02 --:--:-- 5448k
Archive:  rclone-current-linux-arm64.zip
   creating: rclone-v1.63.0-linux-arm64/
  inflating: rclone-v1.63.0-linux-arm64/rclone  
  inflating: rclone-v1.63.0-linux-arm64/README.txt  
  inflating: rclone-v1.63.0-linux-arm64/git-log.txt  
  inflating: rclone-v1.63.0-linux-arm64/rclone.1  
  inflating: rclone-v1.63.0-linux-arm64/README.html  
rclone: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=KM7H-McBUrrT-ruR8Ij5/IsAy5pZeQyGLSp4yh2T4/_Bouq4UwpvCq5_Xb_bVU/OP0tAnH2VPMJyRV0630G, stripped

# validation test for osx arm64 architecture
pd@mba ~ % cd && curl -O https://downloads.rclone.org/rclone-current-osx-$(uname -m).zip; unzip -a rclone-current-osx-$(uname -m).zip && cd rclone-*-osx-$(uname -m); file rclone
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19.3M  100 19.3M    0     0  3018k      0  0:00:06  0:00:06 --:--:-- 4075k
Archive:  rclone-current-osx-arm64.zip
   creating: rclone-v1.63.0-osx-arm64/
  inflating: rclone-v1.63.0-osx-arm64/git-log.txt  [text]  
  inflating: rclone-v1.63.0-osx-arm64/rclone  [binary]
  inflating: rclone-v1.63.0-osx-arm64/rclone.1  [text]  
  inflating: rclone-v1.63.0-osx-arm64/README.html  [text]  
  inflating: rclone-v1.63.0-osx-arm64/README.txt  [text]  
rclone: Mach-O 64-bit executable arm64

```

#### Was the change discussed in an issue or in the forum before?

No

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Review by ncw — COMMENTED** [review]
This is a nice idea, but it doesn't work on my linux laptop - this needs to be `amd64` which is what Go calls the arch.

```
$ uname -m
x86_64
```

Also does `uname -m` work on macOS?

**Comment by raxpd** [comment]
ah! that's right, yeah somehow missed that part. my bad. I'll close this. 

`uname` does work on macOS

```bash
pd@mba ~ % uname   
Darwin
pd@mba ~ % uname -m
arm64
pd@mba ~ % 
```

**Comment by kapitainsky** [comment]
FYI - on macOS Intel:

```
uname -m
x86_64
```

so the same issue as with Arch Linux

**Comment by ncw** [comment]
Maybe we can think of another way of calling this out to the user?

We could use a bit of shell magic to set an env var to the correct value then use ${ARCH} in the docs? I don't know if that will be too confusing though.

**Comment by raxpd** [comment]
perhaps urls can be defined statically for each architecture, and handle the cd, unzip etc with wildcard? Static URLs and wildcard are already being used in the `install.md` at different places.

towards your second point, we could even have a single script, curl and then piped to bash,  for mac and linux, which identifies the OS and Architecture, downloads and works towards installation and cleanup. I'd like to take a stab at it, if you guys feel this option fits well.

**Comment by ncw** [comment]
> perhaps urls can be defined statically for each architecture, and handle the cd, unzip etc with wildcard? Static URLs and wildcard are already being used in the `install.md` at different places.

Perhaps listing a selection of URLs would make that clear.

> towards your second point, we could even have a single script, curl and then piped to bash, for mac and linux, which identifies the OS and Architecture, downloads and works towards installation and cleanup. I'd like to take a stab at it, if you guys feel this option fits well.

We have this already - see https://rclone.org/install/#script-installation or did you mean something different?

**Comment by raxpd** [comment]
yes, that is exactly what I had in mind :)

**Comment by ncw** [comment]
Yes maybe there should be a link in those sections. Good idea. Want to make a PR for it?

**Comment by raxpd** [comment]
thanks, I'll send one out

**Pull request closed without merging**
