### PR TITLE
Remove github.com/pkg/errors and replace with std library version

### PR DESCRIPTION
**Pull request by ncw**
This is possible now that we no longer support go1.12 and brings
rclone into line with standard practices in the Go world.
#### What is the purpose of this change?

Update rclone code to Go best practices

#### Was the change discussed in an issue or in the forum before?

No
#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

@ivandeex or @albertony have you got time to a) comment and b) review this very long PR?

Most of it was generated by a series of regular expressions, then it needed a fair amount of fixing up by hand.

### CODE REVIEW

**Comment by ncw** [comment]
Ah, a conflict - so soon! Fixed.

**Comment by albertony** [comment]
Wow, where to begin... 😅 

Great work. I'm not sure I want to go through every single line... but I am checking some here and some there to see if there is anything that your regex/fixup might have tripped on. Also building the branch and doing some quick tests to verify output. So far have not spotted anything.

You obviously prefer use of built-in `errors.New` and `fmt.Errorf` over the wrapper functions `New` and `Errorf` in rclone/lib/errors. Are the wrapper functions kept mostly to not break existing code that was not changed? Also, you seem to prefer importing  `rclone/lib/errors`, but quite a few places `errors` are imported directly instead. Is there a reason, what is the rule to follow here?

**Comment by ncw** [comment]
> Wow, where to begin... sweat_smile

:-)

> Great work. I'm not sure I want to go through every single line... but I am checking some here and some there to see if there is anything that your regex/fixup might have tripped on. Also building the branch and doing some quick tests to verify output. So far have not spotted anything.

Great!

> You obviously prefer use of built-in `errors.New` and `fmt.Errorf` over the wrapper functions `New` and `Errorf` in rclone/lib/errors. Are the wrapper functions kept mostly to not break existing code that was not changed? Also, you seem to prefer importing `rclone/lib/errors`, but quite a few places `errors` are imported directly instead. Is there a reason, what is the rule to follow here?

That is a good spot.

I've pushed an update which removes `errors.New` and `errors.Errorf` from `lib/errors` - there is no need for them any more and makes all the code use the stdlib "errors" package for `errors.New` or `fmt.Errorf`.

> Edit: Is it the use of `fmt.Errorf` that warrants `rclone/lib/errors`, otherwise its enough with `errors`? Edit 2: But if so, it is not entirely consistent; mountpoint_other.go imports both `rclone/lib/errors` and `fmt`, and mountpoint_windows.go imports both `fmt` and `errors`.

I think I've fixed that all up now - would be grateful if you'd have another look :-)

**Comment by albertony** [comment]
Good, now it makes perfect sense.

**Review by albertony — APPROVED** [review]

**Comment by ncw** [comment]
Thanks for the review @albertony 

I'm going to merge this now, early in the release cycle, in time for fallout to be fixed for the next release!

**Pull request merged**
