### PR TITLE
docs: Small improvements

### PR DESCRIPTION
**Pull request by KaspianDev**
#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by KaspianDev** [comment]
i have noticed the same thing as in [this](https://github.com/rclone/rclone/pull/6168/commits/faf0a411c42b21dd0093d757d739aae4c29a64dc) on other pages too.
Should I modify them too the same way?

**Comment by albertony** [comment]
> Should I modify them too the same way?

Yes, that would be great.... is my opinion 👍

**Comment by ncw** [comment]
@albertony happy for you to merge all doc fix PRs as you see fit :-)

**Comment by KaspianDev** [comment]
That's it I guess, hope you don't mind the commit spam (didn't realize how many had that line lol)

**Comment by ncw** [comment]
That looks great. I'll squash these to one commit before merging - thank you.

**Pull request merged**
