### PR TITLE
DOC: "OS X" -> "macOS"

### PR DESCRIPTION
**Pull request by partev**
#### Checklist

- [ ] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [ ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ ] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ivandeex** [comment]
Fair enough.
One question: why "macOS" and not "MacOS"?

It would be great if you could search all instances of "OS X", "MacOS X", "osx" and replace by "MacOS".

**Comment by Masamune3210** [comment]
Because macOS is a proper name and is capitalized like that on purpose. Dumb but technically correct in this case

**Comment by partev** [comment]
Apple spells it like "macOS" see https://www.apple.com/macos

**Comment by ivandeex** [comment]
Merging.
Thank you.

**Pull request merged**
