### PR TITLE
cmd/rcd: Fix command docs to include command specific prefix (#6675)

### PR DESCRIPTION
**Pull request by Zacho2**
#### What is the purpose of this change?
This change addresses two issues with commands that re-used flags from common packages:

1) cobra.Command definitions did not include the command specific
   prefix in doc strings.
2) Command specific flag prefixes were added after generating
   command doc strings.

#### Was the change discussed in an issue or in the forum before?
#6675 

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by Zacho2** [comment]
@ncw could you please give this a review when time allows?

**Review by ncw — APPROVED** [review]
This looks great - thank you :-)

Apologies for the delay reviewing.

Can you rebase it and fix the merge conflict and then I will merge.

**Comment by Zacho2** [comment]
@ncw I've rebased and fixed the conflict. Looks like there are lint failures for existing code this fix hasn't touched. Please let me know if there's something I need to do to address that.

**Comment by ncw** [comment]
The linter went bonkers! Can you rebase this on master and force push - you should pick up the new linter config then and we can see if it runs clean - thanks :-)

Let me know when you've done that and I'll take another look.

**Comment by Zacho2** [comment]
@ncw I rebased and all the checks look good now.

**Comment by ncw** [comment]
Thank you for doing this :-) All merged for v1.63 now.

**Comment by ncw** [comment]
@Zacho2 - don't worry - I will fix this :-)

**Pull request merged**
