### PR TITLE
Support max pages

### PR DESCRIPTION
**Pull request by darthShadow**
#### What is the purpose of this change?

Added support for Max Pages

#### Was the change discussed in an issue or in the forum before?

https://forum.rclone.org/t/max-pages-on-linux-with-rclone-mergerfs/12724

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [ ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ ] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by darthShadow** [comment]
The vendor changes will be removed once the upstream [PR](https://github.com/bazil/fuse/pull/237) is merged.

**Comment by ncw** [comment]
> The vendor changes will be removed once the upstream [PR](https://github.com/bazil/fuse/pull/237) is merged.

Unfortunately doing vendor patches like this is not supported by go modules :-(

My preference would be to wait for the upstream merge before merging this - what do you think?

**Comment by darthShadow** [comment]
> My preference would be to wait for the upstream merge before merging this - what do you think?

Yeah, definitely. That's why I didn't mark it as ready for merging. I just wanted to create the PR for a review and possibly automated builds from it for testing.

**Comment by ncw** [comment]
> > My preference would be to wait for the upstream merge before merging this - what do you think?
> 
> Yeah, definitely. That's why I didn't mark it as ready for merging. I just wanted to create the PR for a review and possibly automated builds from it for testing.

The modules thing is why the modules build and the xgo build are failing :-(

I pushed this PR to a branch which will build a binary here:

https://beta.rclone.org/branch/v1.51.0-014-g6a86ec70-pr-3949-max-pages-beta/

**Comment by ncw** [comment]
@darthShadow It looks like the build is failing
```
# github.com/rclone/rclone/vfs/vfsflags
##[error]vfs/vfsflags/vfsflags.go:38:2: undefined: platformFlags
```
Did something not get committed?

**Comment by darthShadow** [comment]
Should be fixed now. Separating the commits for easier removal after the upstream changes are merged resulted in a file getting missed. Sorry for the trouble.

**Comment by ivandeex** [comment]
@darthShadow 
- This PR should be updated for go modules.
- Did upstream include your patches?
- Does `billziss-gh/cgofuse` support maxpages?

**Comment by darthShadow** [comment]
Thanks for taking a look since this had completely slipped my mind.

> This PR should be updated for go modules.

Will take care of this once the respective packages are merged upstream or if we have alternate ways of handling it.


> Did upstream include your patches?

I do need to add tests for the go-fuse PR but the bazil/fuse PR has been open since May with no further activity.

> Does `billziss-gh/cgofuse` support max-pages?

That's a good question. I will have to take a more in-depth look later but a brief GitHub search doesn't give any results.

---

This whole process may take time so if you want me to close this PR and submit a new one later, that's fine with me.

**Comment by ivandeex** [comment]
> This whole process may take time so if you want me to close this PR and submit a new one later, that's fine with me.

I don't see reasons for close/reopen.

What I did last 3 days was rather rclone backlog refinement with intent to make technical debt more navigable and transparent (via enriched pr/issue labeling and cross-item links aka "related to") and _pinpoint stale items_. Hopefully the number of new labels is minimal to avoid rippled picture.
The pinpointing goal was based on the created navigation and few specific labels: `waiting for [issue/pr submitter] reply` for items that need chasing folks, `help wanted` for stuck PRs and for low-prio/forgotten issues ideal for outsourcing, `needs rebase` for where full review is premature but a quick advice would help, `needs retest` for ancient fossil PRs and for issues solved (probably) as byproduct of unrelated issues.
I'm not striving for force-closing pr/issues. I'm mostly done with this stuff 🤾 and hope the process to roll on ⚽  more or less on its own. I'm switching to assigned issues.

**Comment by ivandeex** [comment]
> Unfortunately doing vendor patches like this is not supported by go modules

But `replace` is supported, e.g. the directive https://github.com/ivandeex/rclone/blob/stream-reset/go.mod#L6 redirects to patched https://github.com/ivandeex/golang-net/commits/stream-reset

**Comment by ivandeex** [comment]
@ncw @darthShadow 
Offtopic. The new `regional` label marks issues susceptible hampered investigation: provider registration requiring a _national_ sim card or 2FA (e.g. some continental cn), possibly poor or no english (cn,ru) in reports, etc.

**Comment by ncw** [comment]
> > Unfortunately doing vendor patches like this is not supported by go modules
> 
> But `replace` is supported, e.g. the directive https://github.com/ivandeex/rclone/blob/stream-reset/go.mod#L6 redirects to patched https://github.com/ivandeex/golang-net/commits/stream-reset
> 
> Whether we want to maintain that stuff is another story 

I generally try not to merge stuff that needs a vendor patch or a replace. There is enough work maintaining one open source project rather than two!

If it comes to it then the way to go is to fork the upstream and use that directly I think. I've only had to do that once with github.com/ncw/go-acd

> Upd: when upstream accepts the patch, just comment out a _single_ line.

I'd prefer it in a branch until that moment.

**Comment by ivandeex** [comment]
The upstream PR https://github.com/bazil/fuse/pull/239 by @felixbuenemann (Support time_gran and max_pages fuse options) has been stalled since March 2020, right after taking over https://github.com/bazil/fuse/pull/237 by @darthShadow :smile:

**Comment by ivandeex** [comment]
I glanced at the frontpage of https://github.com/bazil/fuse
The last commit dates back to May 2020 :coffin:

**Comment by ivandeex** [comment]
@darthShadow @ncw
Apparently upstream repository has not any development for a year. Marking this PR as draft until upstream shows any signs of life.

**Comment by ivandeex** [comment]
@ncw @darthShadow 

This PR is stalled for 1 year and 4 months.
I think we can close it.

**Pull request closed without merging**
