### PR TITLE
cache: Clear chunks when info changes

### PR DESCRIPTION
**Pull request by dcpu**
#### What is the purpose of this change?

If the file is modified from another instance, the cached chunks are not cleared. Cache serves old cached chunks even after info has been updated. 
This patch will clear chunks when info(size, date) changes.

#### Checklist

- [X] I have read the [contribution guidelines](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [X] All commit messages are in [house style](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [X] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ncw** [comment]
I have rebased this, fixed the conflicts and pushed it back to your branch for another CI run.

**Comment by ncw** [comment]
This seems to break this test

```
2019/07/01 13:27:15 Running with the following params: 
 remote: TestInternalCache, 
 mount: false
2019/07/01 13:27:15 Mount Dir: /tmp/rclonecache-mount806083552
2019/07/01 13:27:15 Temp Upload Dir: /tmp/rclonecache-tmp124027839
2019/07/01 13:27:15 NOTICE: Config file "/notfound" not found - using defaults
2019/07/01 13:27:15 NOTICE: Config file "/notfound" not found - using defaults
2019/07/01 13:27:15 NOTICE: Config file "/notfound" not found - using defaults
2019/07/01 13:27:15 NOTICE: Config file "/notfound" not found - using defaults
2019/07/01 13:27:19 ERROR : ticwcm1561987635/data.bin: unexpected conditions during reading. current position: 2621440, current chunk position: 0, current chunk size: 1323008, offset: 2621440, chunk size: 5M, file size: 23592960
```

Any ideas?

**Comment by ivandeex** [comment]
@dcpu 
This PR is 2 years old.
Could you fix failing tests, please?

**Comment by ivandeex** [comment]
This PR is probably superseded by recent VFS improvements.

**Comment by ivandeex** [comment]
@ncw I am going to close this as @dcpu has no github activity for two years.

**Pull request closed without merging**
