### PR TITLE
Implements #6290 enhancement (azureblob)

### PR DESCRIPTION
**Pull request by maiorfi**
#### What is the purpose of this change?

Allow usage of remote azurite emulator.
Just add Endpoint parameter in advanced settings when defining/editing remote with something like:
http://10.254.2.5:10000/devstoreaccount1

#### Checklist

- [ ] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [ ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [X] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Review by ncw — COMMENTED** [review]
This change looks great!

Fancy putting a bit in the docs about it?

https://github.com/rclone/rclone/blob/master/docs/content/azureblob.md#azure-storage-emulator-support

**Comment by maiorfi** [comment]
Docs updated, but without specifying that new feature PR enables will be available since one of upcoming releases.

**Review by ncw — APPROVED** [review]
Looks perfect - thank you :-)

**Comment by ncw** [comment]
Thank you :-)

**Pull request merged**
