### PR TITLE
feat: add teambition backend

### PR DESCRIPTION
**Pull request by K265**
#### What is the purpose of this change?

add teambition pan backend

#### Was the change discussed in an issue or in the forum before?

<https://github.com/rclone/rclone/issues/4790>

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ncw** [comment]
This is looking nice - well done :-)

I have some questions

- do you have a test account I can use for the integration tester? This runs daily
- I think there are some things missing from the [writing a new backend](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#writing-a-new-backend) checklist, most obviously the docs
- Does this pass the integration tests in the checklist above?
- The interface assertions are missing, eg the [ones from dropbox](https://github.com/rclone/rclone/blob/4b5fe3adad013b5e0bbf107e560968ea94d2772d/backend/dropbox/dropbox.go#L1543-L1555) - these are important to know the correct interfaces got implemented
- This doesn't implement quite a lot of the extra interfaces like Move/DirMove/Copy? Are these possible?
- There are some things to fix from the CI test


```
backend/teambition/teambition.go:5: File is not `goimports`-ed (goimports)
	"fmt"
backend/teambition/teambition_test.go:4: File is not `goimports`-ed (goimports)
	"github.com/rclone/rclone/fstest/fstests"
backend/teambition/teambition.go:111:1: comment on exported method `Fs.Hashes` should be of the form `Hashes ...` (golint)
// Returns the supported hash types of the filesystem
^
backend/teambition/teambition.go:278:1: comment on exported method `Object.Remove` should be of the form `Remove ...` (golint)
// Removes this object
^
```

**Comment by K265** [comment]
> This is looking nice - well done :-)
> 
> I have some questions
> 
> * do you have a test account I can use for the integration tester? This runs daily
> * I think there are some things missing from the [writing a new backend](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#writing-a-new-backend) checklist, most obviously the docs
> * Does this pass the integration tests in the checklist above?
> * The interface assertions are missing, eg the [ones from dropbox](https://github.com/rclone/rclone/blob/4b5fe3adad013b5e0bbf107e560968ea94d2772d/backend/dropbox/dropbox.go#L1543-L1555) - these are important to know the correct interfaces got implemented
> * This doesn't implement quite a lot of the extra interfaces like Move/DirMove/Copy? Are these possible?
> * There are some things to fix from the CI test
> 
> ```
> backend/teambition/teambition.go:5: File is not `goimports`-ed (goimports)
> 	"fmt"
> backend/teambition/teambition_test.go:4: File is not `goimports`-ed (goimports)
> 	"github.com/rclone/rclone/fstest/fstests"
> backend/teambition/teambition.go:111:1: comment on exported method `Fs.Hashes` should be of the form `Hashes ...` (golint)
> // Returns the supported hash types of the filesystem
> ^
> backend/teambition/teambition.go:278:1: comment on exported method `Object.Remove` should be of the form `Remove ...` (golint)
> // Removes this object
> ^
> ```

Sorry, I don't have extra account currently
I've tried to apply a new account but with no luck, I have no idea when it will open registration again.
Maybe it's too early to create this PR, there are still may things to do.
I'm going to close this pull request
Thank you :-)

**Comment by ncw** [comment]
No problems! Hopefully the above notes will help when you send the PR back the next time :-)

**Comment by K265** [comment]
> No problems! Hopefully the above notes will help when you send the PR back the next time :-)

ok :-)

**Comment by fxzxmic** [comment]
Waiting😊

**Comment by K265** [comment]
> Waiting😊

Sorry, teambition have closed registration.
I won't open this PR. 

If your want to use teambition, you may see:
 <https://github.com/K265/rclone/tree/teambition-backend>

But it's not maintained.

**Pull request closed without merging**
