### PR TITLE
compress: fix remotes without PutStream & ObjectInfo wrapping.

### PR DESCRIPTION
**Pull request by buengese**
Quick postmortem here: #4928 was caused by the wrapped ObjectInfo actually returning the checksum & size of the uncompressed object which obviously differs from the compressed object actually upload (duh!). Since we cannot know the checksum & size of the compressed object beforehand there is really no useful information that can be returned here.

While wondering how I didn't catch that beforehand I found a second bug.  Prior to https://github.com/rclone/rclone/commit/886b3abac17404910d89192fae74cdec47515702 I was using operations.Rcat() instead of put when uploading compressed files which had the side effect of masking this bug since it didn't make use of the ObjectInfo wrapping. Well, turns out there was a reason I was using operations.Rcat() there since we cannot know the size of the compressed file beforehand (second duh!) this was required to be able to support underlying remotes without put stream. I've now implemented a Jottacloud-MD5 style workaround for this that spools the file to ram or disk to determine it's size and uploads using normal Put.

I'd also strongly suggest adding additional integration tests for this remote similar chunker. At least one non-local file-based & one bucket based remote would probably be a good idea here @ncw.

### CODE REVIEW

**Comment by ncw** [comment]
> Quick postmortem here: #4928 was caused by the wrapped ObjectInfo actually returning the checksum & size of the uncompressed object which obviously differs from the compressed object actually upload (duh!). Since we cannot know the checksum & size of the compressed object beforehand there is really no useful information that can be returned here.

OK
 
> While wondering how I didn't catch that beforehand I found a second bug. Prior to [886b3ab](https://github.com/rclone/rclone/commit/886b3abac17404910d89192fae74cdec47515702) I was using operations.Rcat() instead of put when uploading compressed files which had the side effect of masking this bug since it didn't make use of the ObjectInfo wrapping. Well, turns out there was a reason I was using operations.Rcat() there since we cannot know the size of the compressed file beforehand (second duh!) this was required to be able to support underlying remotes without put stream. I've now implemented a Jottacloud-MD5 style workaround for this that spools the file to ram or disk to determine it's size and uploads using normal Put.

That seems like a reasonable work around :-)

I wonder whether we should factor the streaming to disk part of

- jottacloud backend
- rcat
- this new code

into `lib/readers`?
 
> I'd also strongly suggest adding additional integration tests for this remote similar chunker. At least one non-local file-based & one bucket based remote would probably be a good idea here @ncw.

Can you add the suggested remotes to `fstest/test_all/config.yaml` and paste the definitions here and I'll make sure they get into the integration test machine.

**Review by ncw — COMMENTED** [review]
Code looks great! Please merge when you are ready.

**Comment by buengese** [comment]
These are my compress test remotes. All with different underlying remote.

```
[TestCompress]
type = compress
remote = /tmp/rclone-compress-test
mode = gzip

[TestCompressSwift]
type = compress
remote = TestSwift:rclone-compress-test
mode = gzip

[TestCompressDrive]
type = compress
remote = TestDrive:rclone-compress-test
mode = gzip

[TestCompressS3]
type = compress
remote = TestS3:rclone-compress-test
mode = gzip
```

**Comment by ncw** [comment]
> These are my compress test remotes. All with different underlying remote

Thanks. I've stuck those in the integration tester now.

**Pull request merged**
