### PR TITLE
Add symlink support to mount command for #2975

### PR DESCRIPTION
**Pull request by dinoboy197**
#### What is the purpose of this change?

Adds symbolic link support for `mount` command.

#### Checklist

- [ ] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [ ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ ] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ncw** [comment]
As discussed on the issue https://github.com/rclone/rclone/issues/2975#issuecomment-763021028 I'd like this support to go in the VFS layer if possible.

**Comment by dinoboy197** [comment]
Yes, I'll be getting as much as I can into the VFS layer as I re-work for `mount` and `cmount` support.

**Comment by ncw** [comment]
> Yes, I'll be getting as much as I can into the VFS layer as I re-work for `mount` and `cmount` support.

Let me know on the original issue if you need any pointers :-)

**Comment by ivandeex** [comment]
@dinoboy197 Are you still working on this?

**Comment by dinoboy197** [comment]
@ivandeex I am not at the moment; please see [my comment on this effort in the issue for this one](https://github.com/rclone/rclone/issues/2975#issuecomment-773802639).

**Comment by ivandeex** [comment]
@dinoboy197 I see

**Comment by ivandeex** [comment]
This PR needs a maintainer.

cc @ncw

**Comment by ivandeex** [comment]
This PR was last updated this january, 6 months ago.
Fortunately links to this thread and patch are kept in the original issue
so a new developrt can pick it at wish and use as a basis.
Closing

**Pull request closed without merging**
