### PR TITLE
b2: link sharing

### PR DESCRIPTION
**Pull request by yparitcher**
#### What is the purpose of this change?
fix the regression caused by #3377
move the directory check from the list function to the link function

**please run the integration test before merging**

this only fixes the symptoms, not the underlying problem, as noted in my email.

#### Was the change discussed in an issue or in the forum before?

discussed in private email exchange

#### Checklist

- [X] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [X] I have added tests for all changes in this PR if appropriate.
- [X] I have added documentation for the changes if appropriate.
- [X] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [X] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ncw** [comment]
I had to fix the integration tests as they were broken by 53a1a0e3efb2cf04 so I pushed an extra commit on your branch.

The tests now run fine for me, so I'll wait for the CI to go green then merge - thank you :-)

**Comment by yparitcher** [comment]
if so maybe my previous fix worked by itself. can you test your commit without mine, and post the log, we might not need my change, i hadnt relized that the accounting changes might have broke the tests

**Comment by yparitcher** [comment]
also the underlying issue of the `TestFsListDirEmpty` test being wrong for B2 bucket based remotes still needs to be resolved and might resolve the tests failing. as the implimentation works, it is just this test which cannot occur in regular usage is failing.

(the b2 web interface creates a empty hidden file in order to create a "empty" directory, and sync with copy-empty-src does not copy the empty folders)

should i open a new issue for it?

**Comment by ncw** [comment]
I checked and your new commit is still needed.

```
        --- FAIL: TestIntegration/FsMkdir/FsListDirEmpty (0.21s)
            require.go:795: 
                	Error Trace:	fstests.go:503
                	Error:      	Received unexpected error:
                	            	directory not found
                	            	github.com/rclone/rclone/fs.init.ializers
                	            		/home/ncw/go/src/github.com/rclone/rclone/fs/fs.go:58
                	            	runtime.main
                	            		/opt/go/go1.12/src/runtime/proc.go:188
                	            	runtime.goexit
                	            		/opt/go/go1.12/src/runtime/asm_amd64.s:1337
                	Test:       	TestIntegration/FsMkdir/FsListDirEmpty
        --- FAIL: TestIntegration/FsMkdir/FsListRDirEmpty (0.20s)
            require.go:795: 
                	Error Trace:	fstests.go:503
                	            				fstests.go:512
                	Error:      	Received unexpected error:
                	            	directory not found
                	            	github.com/rclone/rclone/fs.init.ializers
                	            		/home/ncw/go/src/github.com/rclone/rclone/fs/fs.go:58
                	            	runtime.main
                	            		/opt/go/go1.12/src/runtime/proc.go:188
                	            	runtime.goexit
                	            		/opt/go/go1.12/src/runtime/asm_amd64.s:1337
                	Test:       	TestIntegration/FsMkdir/FsListRDirEmpty
```

The original changes to the semantics of list were wrong I think.

I'll merge this now :-)

**Pull request merged**
