### PR TITLE
touch: add recurse functionality - issue #5301

### PR DESCRIPTION
**Pull request by aeromaxx**
#### Was the change discussed in an issue or in the forum before?

https://forum.rclone.org/t/using-rclone-touch-recursively/23975

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ ] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ncw** [comment]
```
# github.com/rclone/rclone/fs/operations
fs/operations/touch.go:5:2: imported and not used: "fmt"
fs/operations/touch.go:6:2: imported and not used: "log"
fs/operations/touch.go:7:2: imported and not used: "path"
fs/operations/touch.go:8:2: imported and not used: "sort"
fs/operations/touch.go:9:2: imported and not used: "strings"
fs/operations/touch.go:13:2: imported and not used: "github.com/rclone/rclone/fs/config"
fs/operations/touch.go:14:2: imported and not used: "github.com/rclone/rclone/fs/hash"
fs/operations/touch.go:15:2: imported and not used: "github.com/rclone/rclone/fs/walk"
fs/operations/touch.go:19:56: undefined: time
fs/operations/touch.go:20:13: undefined: time
fs/operations/touch.go:20:13: too many errors
```

Is the error from the CI?

**Comment by albertony** [comment]
@aeromaxx Are you planning to work more on this? I have digged into it a bit on my own, out of curiosity.. If you are motivated, and able to get proper build environment set up etc, I could give you some pointers.. (if not, I could continue and make my draft into a complete PR)

**Comment by aeromaxx** [comment]
> @aeromaxx Are you planning to work more on this?

No I couldn't get a proper build environment to work, and I have never used Go before, or written anything using it, and I didn't understand the confusing errors I was getting, or how to fix them...  If the errors actually made sense, I could have probably got it work.

**Comment by albertony** [comment]
Closing this in favor of https://github.com/rclone/rclone/pull/5367.

**Pull request closed without merging**
