### PR TITLE
Fix #5272: Only run workflow script in rclone repsoitory, not forks

### LINKED ISSUE #5272: Gihub action build.yml prevents updating any rclone fork
The build.yml has a `push:` event with is triggered on every branch and every repository. But this is wrong to trigger it on forks.

Here is what happens when auto-updating a rclone fork:

```
To https://github.com/mathieucarbou/rclone
 ! [remote rejected]   master -> master (refusing to allow a GitHub App to create or update workflow `.github/workflows/build.yml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/mathieucarbou/rclone'
```

It seems there is a workaround by adding `paths-ignore` filters on the push even or if condition to check the repository name:

`if: github.repository == 'rclone/rclone'`

Cheers!

### PR DESCRIPTION
**Pull request by mathieucarbou**
#### What is the purpose of this change?

Fix #5272

#### Was the change discussed in an issue or in the forum before?

See #5272

#### Checklist

- [X] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [X] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [X] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by mathieucarbou** [comment]
@ncw : FYI I was able to test that with my fork and it works fine.

See: https://github.com/mathieucarbou/rclone/actions

When pushing a test before the fix, builds were triggered and I had to cancel them. They were running from my GitHub Actions quota which is not nice for users forking the rclone repo ;-)

After merging the fix, you can see that the 2 runs are triggered but all jobs are now skipped (i.e. https://github.com/mathieucarbou/rclone/actions/runs/783274191)

**Review by ncw — COMMENTED** [review]
This is looking great!

Do the changes work properly?

Can you rename the commits so they both start with `build: ....` then the change log creator will get them in the right category.

**Comment by mathieucarbou** [comment]
> This is looking great!
> 
> Do the changes work properly?
> 
> Can you rename the commits so they both start with `build: ....` then the change log creator will get them in the right category.

will do! let me just merge this branch in my forked master and show you what will happen on a fork ;-)

**Review by ncw — APPROVED** [review]
That is a great improvement - thank you :-)

I'll merge it now.

**Pull request merged**
