### PR TITLE
Add selection to ncdu command

### PR DESCRIPTION
**Pull request by CrossR**
#### What is the purpose of this change?

Add the ability to select multiple items in the ncdu interface to delete them.

Either press `v` to select the current item, or `V` to highlight items as you move over them (slightly awkward behaviour that I'll tidy up here if you swap direction, the final item isn't toggled back). Then I've added a `D` command that will delete all the currently selected items.

#### Was the change discussed in an issue or in the forum before?

I've not discussed this elsewhere, it was just something I wanted!

I haven't fully fleshed this out yet (fixing the highlight on move feel, keybind changes/squash commits/docs/look for ncdu tests if they exist), since I wanted to check if this was something you'd be open to adding/if it fits as part of the `ncdu` command.

Assuming it is something you'd be fine to add, I'll fix up the things I mentioned above, as well as do a pass over the code. I've not written a line of go before this, so I expect I've done some things in odd, non-standard ways (whatever the equivalent of "Pythonic" is for Go!) so may need some refactoring.

Also just need to do a pass to make sure I'm not missing any edge cases (i.e. leaving a folder, making sure works as expected if a single selected file is deleted (it won't right now I think), fix cursor pos for multiple moves, etcetc).

This was just a "check a minimal case" pass, to make sure you were open to the idea first!

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [ ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ ] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ncw** [comment]
> Add the ability to select multiple items in the ncdu interface to delete them.

Sounds useful!

Is this something ncdu does?
 
> Either press `v` to select the current item, or `V` to highlight items as you move over them (slightly awkward behaviour that I'll tidy up here if you swap direction, the final item isn't toggled back). Then I've added a `D` command that will delete all the currently selected items.

I like `D` for delete marked items. `v` to mark them seems odd - what is the rational there? Can we use `m` for `Mark`? Shift arrow keys might work for multiple selections?

Is there prior art we can ~~steal~~ imitate so make it work like some other terminal app people are familiar with?

**Comment by CrossR** [comment]
>Is this something ncdu does?

Its not (at least not in the versions I use), which is why I wanted to check it was something you'd be open to adding. I know some features, even when useful, don't necessarily make sense. (Perhaps this moves the `ncdu` command closer to being a basic file explorer, which isn't necessarily desirable).

> I like D for delete marked items. v to mark them seems odd - what is the rational there? Can we use m for Mark? Shift arrow keys might work for multiple selections?
>
>Is there prior art we can steal imitate so make it work like some other terminal app people are familiar with?

I added `V` first, then realised it would be useful to add a single select too, so added it as the non-capitalised version..... so no real reasoning, just that it was the lower case of the thing I just added.

Something like ranger (https://github.com/ranger/ranger) is where I usually go to _borrow_ keybinding ideas from, so in that case it would be `Space` to single select, and `V` for visual select (though it is vim inspired so maybe its just reinforcing the binds I already know from there, and there is a nicer more general thing to look at). Either space or m sound reasonable to me, and I think adding shift-arrow keys makes a lot of sense too.

**Comment by Zirro** [comment]
I've found rclone's ncdu to be pretty handy as a makeshift file explorer in situations where the `mount`-command has not been available. It'd be unfortunate to limit its potential just for the sake of strictly mirroring the original.

One possibility would be to implement more features as an optional layer on top of the standard ncdu functionality, which could be toggled through a flag to the `ncdu` command depending on whether the user wants the extra features or prefers the "pure" ncdu experience.

Later on, assuming that additional non-ncdu features get implemented over time, these could potentially be forked into two separate commands - one which sticks to the original ncdu-features and one which fully embraces the role of file explorer.

**Comment by ivandeex** [comment]
> I like `D` for delete marked items. `v` to mark them seems odd - what is the rational there? Can we use `m` for `Mark`? Shift arrow keys might work for multiple selections?

- [x] `v` looks like a check glyph so it's better than `m` IMO

**Comment by SonaliBendre** [comment]
Hi, is it possible to add copy,sync and move besides delete? First select all files needed to copy then shortcut key to add them to task, go to destination directory, shortcut key for paste Done. a multi window feature in ncdu may also be helpful for file explore and copy/move tasks.

**Pull request closed without merging**
