### PR TITLE
Using WebDAV with CORS

### LINKED ISSUE #7492: PROPFIND with Depth fails on Serve WebDAV
I just ran into this issue after trying PROPFIND with 1.65. 
Technically, this is a follow-up on the `serve webdav` issues. #7444 and #7448. It seems that #6980 and perhaps others might also be related.

It was mentioned in the last comment [here](https://github.com/rclone/rclone/issues/7444#issuecomment-1828943189), that the message is `Request header field depth is not allowed by Access-Control-Allow-Headers in preflight response.`
This effectively prevents listing just the requested folder. The PROPFIND request works but it does not receive the Depth parameter, which is sent through the header. This comment contains the links to the WebDAV headers and the line that needs to be modified.

Additionally ,as @ncw mentioned [here](https://github.com/rclone/rclone/issues/7444#issuecomment-1838426670), this should be done in the webdav server, not the global one.

#### The associated forum post URL from `https://forum.rclone.org`

n/a

#### What is the problem you are having with rclone?

Issuing a PROPFIND request fails if it contains a `depth:1` header.

#### What is your rclone version (output from `rclone version`)

1.65

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Win 11, 64-bit

#### Which cloud storage system are you using? (e.g. Google Drive)

local drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone serve webdav . --allow-origin "*"

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

n/a

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

### PR DESCRIPTION
**Pull request by alensiljak**
Fixes #7492

#### What is the purpose of this change?

Allow WebDAV headers when using CORS. 
WebDAV request parameters are sent through headers.

#### Was the change discussed in an issue or in the forum before?

This is new pull request instead of #7493. The commits have been squashed and separated thematically.
It's a follow-up on previous fixes of WebDAV with CORS #7444, #7448. The direct issue (a problem encountered) is #7492.

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by alensiljak** [comment]
This actually doesn't work now. Previously, in the separate method in webdav, I used .set() method for headers, changing the existing ones, whereas now they are just added again:

image

The browser seems to pick up the first one and the requests fail.

**Comment by alensiljak** [comment]
Fixed with .Set() instead of .Add().

**Comment by ncw** [comment]
This is looking nice now.

We could merge it like this...

However I note from your experiments above that `MiddlewareCORS` is being called twice (the `.Add` vs `.Set` is a giveaway). I don't think it is possible to remove a middleware.

Maybe what we want is to store the CORSMethods and CORSHeaders in the [http server config](https://github.com/rclone/rclone/blob/110d07548fbe18937933239d823da904826205b3/lib/http/server.go#L100) and then instantiate the [MiddlewareCORS](https://github.com/rclone/rclone/blob/110d07548fbe18937933239d823da904826205b3/lib/http/middleware.go#L169)  with a `*http.Config` instead of `allowOrigin string` (since that is in the `http.Config` already)  - then it can read everything it needs from the `http.Config` directly.

This would also save exposing `Mux` also.

The `CORSMethods` and `CORSHeaders` should be initialised to the current values in the [DefaultCfg](https://github.com/rclone/rclone/blob/110d07548fbe18937933239d823da904826205b3/lib/http/server.go#L135)

This would then stop `MiddlewareCORS` being called twice and make it an easy config option in the servers that care.

I hope you don't mind this iterative approach to design - sometimes you don't see the way until you've tried some wrong turnings first!

**Comment by alensiljak** [comment]
Great! Thanks for the feedback and the pointers. I think I feel a bit more comfortable around these areas now.
Continuing in #7495. Is this what you had in mind?

**Pull request closed without merging**
