### PR TITLE
imagekit: updated overview - supported operations

### PR DESCRIPTION
**Pull request by harshit-budhraja**
#### What is the purpose of this change?

@ncw The [previous PR](https://github.com/rclone/rclone/pull/7570) that I had raised yesterday was not marked as ready, but unfortunately it got merged 😢 There was an internal review still going on for the correctness of the documentation around features that we shipped on the backend.

Hence, this PR updates a section that needed minor changes.

#### Was the change discussed in an issue or in the forum before?

N/A

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ahnv** [comment]
LGTM

**Comment by harshit-budhraja** [comment]
@ahnv Can you please review?

**Comment by harshit-budhraja** [comment]
@ncw This is now ready to be merged :))

**Comment by ncw** [comment]
> There was an internal review still going on for the correctness of the documentation around features that we shipped on the backend.

Oops! Fastest PR merge in the west :-)

Oh I see you didn't tick the ` I'm done, this Pull Request is ready for review :-)` button - I didn't notice that! Next time if you set the draft flag then it can't be merged and I'll definitely notice that :-)

Anyway, no worries - followup PRs are fine!

**Review by ncw — APPROVED** [review]
LGTM thank you :-)

**Pull request merged**
