### PR TITLE
ftp: Add force_list_hidden option

### PR DESCRIPTION
**Pull request by ThreePinkApples**
Forces the use of `LIST -a` command
when listing a directory which should
list all hidden folders and files.

#### What is the purpose of this change?
To introduce an option to workaround systems that do not include hidden files/folders by default when using the FTP MLST command.

#### Was the change discussed in an issue or in the forum before?
https://forum.rclone.org/t/how-to-list-hidden-folders-with-ftp/32812

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [ ] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ThreePinkApples** [comment]
I have been unable to build a Windows executable that includes cmount, any help with this would be appreciated so that I can test this properly

**Comment by albertony** [comment]
> I have been unable to build a Windows executable that includes cmount, any help with this would be appreciated so that I can test this properly

What is the problem? Which OS? Have you read this: https://rclone.org/install/#install-from-source

**Comment by ThreePinkApples** [comment]
> > I have been unable to build a Windows executable that includes cmount, any help with this would be appreciated so that I can test this properly
> 
> What is the problem? ~Which OS?~ Have you read this: https://rclone.org/install/#install-from-source

I got a little further after installing Cygwin with gcc-core, but now I fail on fuse saying platform not supported.

```
$ make GOTAGS=cmount                                                                  
go build -v --ldflags "-s -X github.com/rclone/rclone/fs.Version=v1.60.0-beta.6439.49e41bd43" -tags "cmount"                                                      
github.com/winfsp/cgofuse/fuse                                                                    
# github.com/winfsp/cgofuse/fuse
C:\Users\inste\go\pkg\mod\github.com\winfsp\cgofuse@v1.5.1-0.20220421173602-ce7e5a65cac7\fuse\fsop_cgo.go:20:2: error: #error platform not supported
	20 | #error platform not supported                                                                           
	   |  ^~~~~                                                                     
C:\mingw\bin\make.exe: *** [rclone] Error 2 
```

**Comment by albertony** [comment]
Why not build without gcc, by setting CGO_ENABLED=0?

**Comment by ThreePinkApples** [comment]
Thanks, now I could build it directly from Powershell 7. And I can now confirm that it does work as intended

**Review by albertony — APPROVED** [review]
Great work, here and on the third party library. Looks good to me (but let's wait for another reviewer to approve it as well).

**Review by ncw — APPROVED** [review]
This looks great - thank you :-)

**Pull request merged**
