### PR TITLE
implement owncloud checksum and modtime extensions for webdav server

### PR DESCRIPTION
**Pull request by WeidiDeng**
#### What is the purpose of this change?

Implement owncloud extensions for webdav server

#### Was the change discussed in an issue or in the forum before?

[3147](https://github.com/rclone/rclone/issues/3147)

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Review by ncw — COMMENTED** [review]
This code looks great!

My only questions are  about the testing.

This is tested by looping back the webdav backend and running the webdav backend tests on the webdav server.

However the backend created in the tests won't be expecting modtimes or hashes to work so it won't test them.

So I think we need to adjust the backend so it knows an rclone webdav server has hashes and modtimes. So maybe we need an `rclone` provider there which sets the correct quirks to enable hashes and modtimes?

This will be backwards compatible since we don't have an Rclone provider already.

Thoughts?

**Comment by WeidiDeng** [comment]
When I worked on the fix for the vfs cache, I think that test is using local file system. I tested this patch locally using local as backend. I'll see what can be done.

**Comment by WeidiDeng** [comment]
How do I write tests for this? I can't find how to test checksum and modtime. `TestWebDav` only contains how to create a backend webdav server, not specifying the features that should be tested.

**Comment by ncw** [comment]
You'll need to add an rclone provider to the WebDAV backend which sets the correct quirks to use modtime and checksums.

Then change the test to add the provider string.

The tests will then test the modtime and checksums.

**Comment by WeidiDeng** [comment]
image

Isn't this creating a webdav backend? Where should I put the test code?

**Review by ncw — APPROVED** [review]
Code looks good, test looks good - let's merge :-)

Thank you

**Comment by Jwink3101** [comment]
I hope it is okay to say this here, but I am really grateful for this feature! When communicating rclone-to-rclone, SFTP is just way too slow so I have to choose between WebDAV speed or ModTime support. Now, once 1.63 is released, this will greatly improve my options!

**Pull request merged**
