### PR TITLE
lib/http: export basic go strings functions

### PR DESCRIPTION
**Pull request by gspinoza**
Makes the following go strings functions available to be used in custom markup templates for HTTP and WebDAV server functions:
- contains
 - hasPrefix
 - hasSuffix

#### What is the purpose of this change?
This will allow users who specify their own custom markup template for HTTP and WebDAV server to use those strings functions to help them modify how their server pages look.  

#### Was the change discussed in an issue or in the forum before?
https://forum.rclone.org/t/cannot-use-strings-functions-in-user-defined-go-template-for-serve-http/36205

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Review by ncw — COMMENTED** [review]
This looks great thank you!

Can you add some documentation too please?

The documentation goes here. This is markdown which is expanded by the Go template processor.

https://github.com/rclone/rclone/blob/b9727cc6ab7ca563c5bb7fe83c00d1fddc1a0feb/lib/http/template.go#L21

I suggest you add a paragraph about template functions then a table of the available functions with a 1 line decscription. Can you include `afterEpoch` too as it currently isn't documented.

Thank you!

**Comment by gspinoza** [comment]
I was unsure if I needed to add documentation for this change since I didn't find anything for `afterEpoch`.  Thanks for letting me know, I'll work on it!

**Comment by gspinoza** [comment]
Hey @ncw, I have added the documentation to the source file. Let me know if it looks fine. Also, I was wondering if I also have to add the new documentation to the files below or is it automatically generated from the source file?

https://github.com/rclone/rclone/blob/5fa68e9ca5963e08c1dc9c7c1527da32f236044b/docs/content/commands/rclone_serve_http.md?plain=1#L77

https://github.com/rclone/rclone/blob/5fa68e9ca5963e08c1dc9c7c1527da32f236044b/docs/content/commands/rclone_serve_webdav.md?plain=1#L106

https://github.com/rclone/rclone/blob/5fa68e9ca5963e08c1dc9c7c1527da32f236044b/docs/content/commands/rclone_rcd.md?plain=1#L76

Thanks!

**Review by ncw — APPROVED** [review]
Looks perfect!

You don't need to adjust those other files - they are auto generated.

I'll merge when the CI goes green - thank you :-)

**Pull request merged**
