### PR TITLE
Add case insensitive alphabet option to base32768 encoding.

### PR DESCRIPTION
**Pull request by kapitainsky**
Fix for https://github.com/rclone/rclone/issues/6803

#### What is the purpose of this change?

Add case insensitive alphabet option (base32768ci) to base32768 encoding.

#### Was the change discussed in an issue or in the forum before?

https://github.com/rclone/rclone/issues/6803

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by Max-Sum** [comment]
I think we could obsolete the legacy base32768 option for the CI one, only keeping the old one for compatibility?

**Comment by kapitainsky** [comment]
> I think we could obsolete the legacy base32768 option for the CI one, only keeping the old one for compatibility?

base32768 works fine and nothing is broken with it. Its constraint is case sensitive output hence it is not good choice for e.g. OneDrive. I think making it obsolete would confuse many people...

**Comment by kapitainsky** [comment]
Also FYI I have tested one of my archive  ~200k files on Onedrive stored with base32768 names encryption. I server side copied them to the new folder with base32768ci encryption and then compared both with sync. All works perfectly.

**Comment by Max-Sum** [comment]
> > I think we could obsolete the legacy base32768 option for the CI one, only keeping the old one for compatibility?
> 
> 
> 
> base32768 works fine and nothing is broken with it. Its constraint is case sensitive output hence it is not good choice for e.g. OneDrive. I think making it obsolete would confuse many people...
> 
> 

I think providing too many choices also confuses people. Since base32768CI works on both case sensitive and case intensive environments with no drawbacks compared to base32768, why not just recommend all new users to use CI instead?

**Comment by kapitainsky** [comment]
> > > I think we could obsolete the legacy base32768 option for the CI one, only keeping the old one for compatibility?
> > 
> > 
> > base32768 works fine and nothing is broken with it. Its constraint is case sensitive output hence it is not good choice for e.g. OneDrive. I think making it obsolete would confuse many people...
> 
> I think providing too many choices also confuses people. Since base32768CI works on both case sensitive and case intensive environments with no drawbacks compared to base32768, why not just recommend all new users to use CI instead?

Valid point as well. Let's see what @ncw thinks

**Comment by kapitainsky** [comment]
I wonder why tests fail on macOS Intel... This is exactly system I am using and no issues.

**Comment by kapitainsky** [comment]
ok I tested and I know - macOS 10.11 - Big Sur (used for automated tests) does not like newer UTF characters. New from its perspective. 

It works fine on macOS 12 and 13 where all characters are accepted and code points used instead when there is no glyph. Not all characters can be displayed but OS does not care - the same as Windows or Linux.

macOS 10.11 was released in 2020 and will be deprecated about September this year when macOS 14 is released -  usual macOS cycle

So now question is what to do?

1. wait until macOS 10.11 is history? then all tests will work
2. release it now and make a note in documentation that due to Unicode v14 (released Sep/2021) some older systems might not work

**Comment by kapitainsky** [comment]
OK I have another idea but would need @Max-Sum help.

At the moment we are looking to generates 1024 plus 4 contiguous, aligned blocks of 32 code points. For case insensitive characters they can only be found for Unicode 14. 

but we can change it to 2056 blocks of  16 code points... 

now I can find such blocks for Unicode v9 (2143 suitable blocks), and still even better because excluding all lower and upper case letters I can have 2120 blocks

@Max-Sum what do you think? I am not good at go and I bet you understand algorithm better. base32768 is not ISO standard - we can be creative here without doing anything crazy.

We would make is a bit slower but much better in terms of compatibility.

**Comment by Max-Sum** [comment]
I appreciate your finding but I am afraid that I couldn't implement this by the end of April since I am quite busy now.
Are you willing to implement this?

**Comment by kapitainsky** [comment]
> I appreciate your finding but I am afraid that I couldn't implement this by the end of April since I am quite busy now. Are you willing to implement this?

No worries. Good excuse for me to learn golang. I think I understand algorithm used well enough to do it.

**Comment by kapitainsky** [comment]
Existing base32768 encoding algorithm can only be case insensitive for Unicode v14 or newer.

This algorithm can be modified and according to my research can be made case insensitive for Unicode v6 (released in 2010 ) or newer. It would provide much safer option for older systems.

I will work on this and in the meantime I am closing this PR.

**Pull request closed without merging**
