### PR TITLE
Validate Daemon Option is not set when mounting Volume via RC

### PR DESCRIPTION
**Pull request by segator**
Fixes https://github.com/rclone/rclone/issues/6469

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by segator** [comment]
I notice even we can block users to set this param, there is not enough information 
image

funny thing is in the response appears the exact error, so is just a matter to improve the UI.
```json
{
	"error": "Daemon Option not supported over the API",
	"input": {
		"fs": "xxxx:",
		"mountOpt": {
			"Daemon": true,
			"VolumeName": "zzzzzz"
		},
		"mountPoint": "/tmp/testing",
		"mountType": "",
		"vfsOpt": {}
	},
	"path": "mount/mount",
	"status": 500
}

```` 
Nevertheless I think that would be another fix

**Comment by ncw** [comment]
> I notice even we can block users to set this param, there is not enough information

I'm not sure I understand what you mean here? Do you mean in the web ui?

**Comment by segator** [comment]
Yes in the web ui @ncw

**Comment by ncw** [comment]
Probably best to make an issue in https://github.com/rclone/rclone-webui-react about that.

**Pull request merged**
