### PR TITLE
Jottacloud: Avoid returning error when option no_versions and remove fail

### PR DESCRIPTION
**Pull request by albertony**
#### What is the purpose of this change?

When using option `no_versions` with the Jottacloud backend, uploading a file will first delete any existing - using the permanent ("hard") delete option. In contrast to regular delete, the permanent delete api request will fail with 404 if path is not found. If, for whatever reason, this should occurr, it would lead to upload error:

> Failed to copy: failed to remove old object: error 404: no.jotta.backup.errors.NoSuchFileException: File /xxxxxx/Jotta/Archive/test.txt does not exist (Not Found)

#### Was the change discussed in an issue or in the forum before?

I think this will solve https://github.com/rclone/rclone/issues/6857. I didn't reproduce a real case myself, but provoked it in debugger by deleting file while paused on break point etc. I'm pretty sure the same can happen in real life though, and I think it is similar to the mentioned isseu.

#### Checklist

- [X] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [X] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [X] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by albertony** [comment]
@ncw : I think this is quite safe to merge!?

I am thinking a bit about a larger case, though; Jottacloud and other backends uses internal caching of object metadata:

https://github.com/rclone/rclone/blob/0361acbde40815534ab11b4027f8083151ff8640/backend/jottacloud/jottacloud.go#L454

Could it happen that this is out of sync and it leads to more problems similar to the one I'm fixing here? E.g. the remove function in Jottacloud does not set `hasMetaData=false`, so if we somewhere calls `readMetaData` on the same object without `force=true` it would believe the file still exists:

https://github.com/rclone/rclone/blob/0361acbde40815534ab11b4027f8083151ff8640/backend/jottacloud/jottacloud.go#L1691-L1694

https://github.com/rclone/rclone/blob/0361acbde40815534ab11b4027f8083151ff8640/backend/jottacloud/jottacloud.go#L1835-L1837

https://github.com/rclone/rclone/blob/0361acbde40815534ab11b4027f8083151ff8640/backend/jottacloud/jottacloud.go#L1709-L1711

Or is this object so short-lived that it shouldn't matter?

**Review by ncw — APPROVED** [review]
This code looks great - thank you :-)

Can you re-write the commit message so the first line is from the point of the user as that is what goes in the changelog. So something like

```
jottacloud: fix vfs writeback stuck in a failed upload loop with file versioning disabled

Avoid returning error when option no_versions and remove fail 

Fixes #6857
```

Thanks!

This looks like it is a candidate for a point release also.

**Comment by ncw** [comment]
> @ncw : I think this is quite safe to merge!?

Yes :+1:

> I am thinking a bit about a larger case, though; Jottacloud and other backends uses internal caching of object metadata:

Stuff can always be out of date - that is the nature of the beast. We need to be prepared to deal with it gracefully if it happens.

Returning an error to the user is fine. Getting stuck in a loop is not!

**Comment by albertony** [comment]
> Can you re-write the commit message

Of course. I wasn't sure if it really fixes that issue - but I guess it is safe to assume that.

**Comment by albertony** [comment]
Done.

> This looks like it is a candidate for a point release also.

I think it is safe to include, yes. Not a new bug, though, its probably been around since july 2021 when the no_versions option was implemented.

**Comment by ncw** [comment]
Thank you :-)

I'll pull it into the stable branch also.

**Pull request merged**
