### PR TITLE
imagekit: Updated docs and web content

### PR DESCRIPTION
**Pull request by harshit-budhraja**
#### What is the purpose of this change?

This PR adds [ImageKit](https://imagekit.io) to the discoverable sections of the web and documentation which was missed earlier at the time of integrating it as a backend.

Previous PR: https://github.com/rclone/rclone/pull/7071

#### Was the change discussed in an issue or in the forum before?

N/A

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ ] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Review by ncw — APPROVED** [review]
That looks great - thank you :-)

**Comment by ncw** [comment]
I should probably write a test for backend docs!

Does this complete the set of docs mentioned [here](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#writing-a-new-backend)?

- README.md - main GitHub page
- docs/content/remote.md - main docs page (note the backend options are automatically added to this file with make backenddocs)
- make sure this has the autogenerated options comments in (see your reference backend docs)
- update them in your backend with bin/make_backend_docs.py remote
- docs/content/overview.md - overview docs
- docs/content/docs.md - list of remotes in config section
- docs/content/_index.md - front page of rclone.org
- docs/layouts/chrome/navbar.html - add it to the website navigation
- bin/make_manual.py - add the page to the docs constant

Thank you!

**Comment by harshit-budhraja** [comment]
@ncw Qq - When will these changes be live on the [website](https://rclone.org/)?

**Comment by ncw** [comment]
At the next release or point release. You should see them at https://tip.rclone.org now

**Comment by harshit-budhraja** [comment]
I can't see it on `tip` either. Am I missing something?


image

**Comment by ncw** [comment]
It should be OK now. The integration test machine got broken yesterday when we upgraded to go1.22rc1!

**Pull request merged**
