### PR TITLE
Doc update: Install with docker: interactive use

### PR DESCRIPTION
**Pull request by mitthu**
#### What is the purpose of this change?
Interactive use from `docker` requires the `-it` flag. Otherwise the command files.

See: https://docs.docker.com/engine/reference/commandline/cli/#option-types

#### Was the change discussed in an issue or in the forum before?
No

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [n/a] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [ ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by albertony** [comment]
Maybe the original author assumed there was already a rclone.conf prepared on the host rclone config dir? But your addition makes sense to me! I'm not a heavy docker user though... and speaking of... is the `--volume ~/data:/data:shared \` really needed in your command, as well as the existing "listremotes" command below? If not, maybe you can delete them from the examples to make it a tiny bit cleaner...

**Comment by mitthu** [comment]
Sure. I removed `--volume ~/data:/data:shared \` since it's not really needed during "config".

I personally would keep the "listremotes" as a way to verify that the remote was indeed added.

**Comment by albertony** [comment]
> I personally would keep the "listremotes" as a way to verify that the remote was indeed added.

Actually I meant just removing the `--volume ~/data:/data:shared \` from that command as well, if not needed? Sorry for being unclear. And it's unrelated to your changes, my suggestion was to sneak in an additional improvement while you're at it. 🙈

**Comment by mitthu** [comment]
Ah okay. Updated it.

**Review by albertony — APPROVED** [review]

**Comment by albertony** [comment]
Great, thank you very much. This now looks good to me. Lets wait some time to see if anyone with more experience with the docker functionality have something to say, if not I'll just merge it in a couple of days.

**Pull request merged**
