### PR TITLE
fichier: fix filename character encoding

### LINKED ISSUE #3298: fichier: non-ASCII characters don't behave as expected
non-ASCII characters fail with 1fichier, and the default (escape with \unicode) doesn't work here as backslash is also blacklisted on 1fichier. Will try to fix this after #3295 is merged

### PR DESCRIPTION
**Pull request by lhaus**
### What is the purpose of this change?
Fix #3298 

#### Was the change discussed in an issue or in the forum before?
#3298 

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

@ncw please check if I missed another code part where we need to replace or restore names, all tests succeed and the broken files I found work now, but I might have missed more.

### CODE REVIEW

**Comment by lhaus** [comment]
Travis build timed out, no idea why

**Comment by ncw** [comment]
It would be worth checking whether `rclone ls fichier:funny_file_name` works.

You might need to take a look at the NewObject path if that fails.

Note that we're in the process of fixing this properly in https://github.com/rclone/rclone/pull/3148 so this will get re done with tests at some point.  Maybe you'd like to do the fichier backend on that branch?

**Comment by lhaus** [comment]
@ncw `rclone ls fichier:funny_file_name` works as expected.
Is it possible to merge this before #3148?
Don't want to run a self-compiled fork for longer than necessary ;)
Otherwise yes I can try to do fichier on rclone:filename-encode when I have time.

**Comment by ncw** [comment]
> @ncw `rclone ls fichier:funny_file_name` works as expected.
> Is it possible to merge this before #3148?

Absolutely.

> Don't want to run a self-compiled fork for longer than necessary ;)
> Otherwise yes I can try to do fichier on rclone:filename-encode when I have time.

Doing the file name work will make it easier to fixup with #3145 

Do you think this is ready to merge now?  How did you get along with the NewObject experiment? `rclone ls fichier:funny_file_name`  you should also try `rclone ls fichier:funny_dir_name`

**Comment by lhaus** [comment]
@ncw This fixed all my issues for a 30TB backup I'm doing, and `rclone ls fichier:funny_file_name` as well as `rclone ls fichier:funny_dir_name` works. This only fixes the issues for files as it was fixed for directories in the initial release (your tests seem to only cover special chars in folders). So yeah, should be ready to merge

**Comment by ncw** [comment]
> @ncw This fixed all my issues for a 30TB backup I'm doing, and `rclone ls fichier:funny_file_name` as well as `rclone ls fichier:funny_dir_name` works. This only fixes the issues for files as it was fixed for directories in the initial release (your tests seem to only cover special chars in folders). So yeah, should be ready to merge

Great - thanks for that.

Will merge now :-)

**Pull request merged**
