### PR TITLE
asyncreader: fix EOF error

### PR DESCRIPTION
**Pull request by buengese**
Quick fix for #3752.

### CODE REVIEW

**Comment by ncw** [comment]
If you rebase on master it should fix the build by picking up cb97239a608eb64d101c324e747918a5d882866f

Can you do a test?

**Comment by buengese** [comment]
Sure.

**Comment by buengese** [comment]
This should be correct in all cases no. I did some additional testing comparing it to bufio.Reader and appears to be correct now. The double EOF just to ignore it isn't pretty but i couldn't think of a better way to do it without either breaking something or making some bigger changes to asyncreader.

**Comment by ncw** [comment]
> This should be correct in all cases no. I did some additional testing comparing it to bufio.Reader and appears to be correct now. The double EOF just to ignore it isn't pretty but i couldn't think of a better way to do it without either breaking something or making some bigger changes to asyncreader.

That patch looks correct to me, and I think the minimal change is probably the best one.

I'll merge that now - thank you :-)

**Pull request merged**
