### PR TITLE
Plugins implementation for webgui : GSoC 2020

### PR DESCRIPTION
**Pull request by negative0**
#### What is the purpose of this change?

Implementation of plugins infrastructure, to support third-party plugins into the web ui.

#### Checklist

- [ ] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [ ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ ] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ncw** [comment]
Let me know when you want me to review this :-)

**Comment by ncw** [comment]
I think you'll need to rebase this on master and force push

**Comment by negative0** [comment]
The history got really messed up at some time. I think I will have to cherry pick.

**Comment by ncw** [comment]
It looks like `TestCoreCommand` is failing?

**Comment by ncw** [comment]
This pull request is now obsolete due to changes in the web UI

**Comment by negative0** [comment]
@ncw I was wondering if it is possible to change the cache dir while testing. The plugins' information is stored in json files, so during testing, it would be really helpful I think if the config on the local system is not considered.

**Comment by ncw** [comment]
> @ncw I was wondering if it is possible to change the cache dir while testing. The plugins' information is stored in json files, so during testing, it would be really helpful I think if the config on the local system is not considered.

Sure... You'll need to make a temporary directory and then remove it again

```go
func TestXXX() {
        cacheDir, err := ioutil.TempDir("", "rclone-cache-dir")
        require.NoError(t, err)
        oldCacheDir := config.CacheDir
        config.CacheDir = cacheDir
        defer func() {
            config.CacheDir = oldCacheDir
            _ = os.RemoveAll(cacheDir)
        }()
```

**Comment by darthShadow** [comment]
Just a tip, but the functionality of a temporary directory was added to the testing package in 1.15. It is also automatically cleaned up after use. Source: https://golang.org/pkg/testing/#T.TempDir

**Comment by negative0** [comment]
> > @ncw I was wondering if it is possible to change the cache dir while testing. The plugins' information is stored in json files, so during testing, it would be really helpful I think if the config on the local system is not considered.
> 
> Sure... You'll need to make a temporary directory and then remove it again
> 
> ```go
> func TestXXX() {
>         cacheDir, err := ioutil.TempDir("", "rclone-cache-dir")
>         require.NoError(t, err)
>         oldCacheDir := config.CacheDir
>         config.CacheDir = cacheDir
>         defer func() {
>             config.CacheDir = oldCacheDir
>             _ = os.RemoveAll(cacheDir)
>         }()
> ```

Thank you.



> Just a tip, but the functionality of a temporary directory was added to the testing package in 1.15. It is also automatically cleaned up after use. Source: https://golang.org/pkg/testing/#T.TempDir

We can use this as well. But as rclone gets compiled for go v1.11, v1.12, 1.13, 1.14. That could be a problem, what do you think @darthShadow

**Comment by darthShadow** [comment]
You are right, that's a problem. Feel free to ignore the suggestion and just use the snippet from ncw.

**Comment by negative0** [comment]
> You are right, that's a problem. Feel free to ignore the suggestion and just use the snippet from ncw.

Thanks for the suggestion.

**Comment by negative0** [comment]
This should have worked. I have just squashed a few previous commits.

**Review by ncw — APPROVED** [review]
This looks great now - thank you :-)

Well done getting the commits split up into logical sections.

I'll merge it now.

**Comment by negative0** [comment]
Thank you!

**Pull request merged**
