### PR TITLE
vfs: check if equal before uploading to remote

### PR DESCRIPTION
**Pull request by wloot**
#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Review by ncw — COMMENTED** [review]
This patch looks like a sensible idea - thank you :-)

I'm slightly concerned about changing the behaviour when using backends which don't support modtimes or checksums.

I'd like a bit more background if possible.

How did you notice that this was a problem?

Can you give me a recipe for making a duplicate upload? So I can try it here.

If so then we could make a test for it too.

Thank you

**Comment by wloot** [comment]
> I'm slightly concerned about changing the behaviour when using backends which don't support modtimes or checksums.

The Equal() is already being used elsewhere(iirc such as rclone copy), so it shouldn't be a problem.

> I'd like a bit more background if possible.
>
> How did you notice that this was a problem?

I use rclone mount with a google drive backend. When I write the same content to a file as itself, a new version of the file will be generated on drive.google.com if without the patch.

```
# mount fs
rclone mount gd:/ /gd
# create a new file
echo "content" > /gd/test
# without the patch, a new version of /gd/test generated
# with the patch, only modtime is updated
echo "content" > /gd/test
```

**Comment by ncw** [comment]
> > I'm slightly concerned about changing the behaviour when using backends which don't support modtimes or checksums.
> 
> The Equal() is already being used elsewhere(iirc such as rclone copy), so it shouldn't be a problem.

Can you try this test with your patch?

Run

```
mkdir /tmp/ftp-files
rclone serve ftp /tmp/ftp-files --user test --pass test
```

and

```
rclone mount --vfs-cache-mode full -vv  ":ftp,host=localhost,port=2121,user=test,pass=6V5Bl1rGjBXdBzAbnHP2FBMOH08:" /mnt/data/
```

And then try overwriting a file on the FTP server with a file that is the same size

```
$ echo one > /mnt/data/file.txt
$ sleep 6
$ cat /tmp/ftp-files/file.txt 
one
$ echo two > /mnt/data/file.txt
$ sleep 6
$ cat /tmp/ftp-files/file.txt 
two
$ 
```

If you do this with your patch the file won't get uploaded. This is because FTP remotes don't support modification times.

> I use rclone mount with a google drive backend. When I write the same content to a file as itself, a new revision of the file will be generated on drive.google.com if without the patch.
> 
> ```
> # mount fs
> rclone mount gd:/ /gd
> # create a new file
> echo "content" > /gd/test
> # without the patch, a new revision of /gd/test generated
> # with the patch, only modtime is updated
> echo "content" > /gd/test
> ```

I see.

So what is happening is that Equal is saying that the modtimes are different, then doing remote and local checksums and seeing they are identical and not uploading.

Perhaps what we should be doing is calling

https://github.com/rclone/rclone/blob/2bc2546d5c93d8a34361e546279e991986090c3f/fs/operations/operations.go#L55

And if `equal && ht != hash.None` then skip the transfer and set the ModTime of the destination instead.

This is slightly annoying duplication of the logic in `Equal` - however `Equal` is designed for syncing which is less demanding than mounting in a lot of ways.

Whatever logic we decide on it needs a test :-)

Another thought crosses my mind - how common is it to alter a file and leave it the same? This patch makes us checksum every file we are about to update which potentially slows everything down.

**Comment by wloot** [comment]
> Another thought crosses my mind - how common is it to alter a file and leave it the same? This patch makes us checksum every file we are about to update which potentially slows everything down.

Prehaps we only should check hash if `--checksum` is set, and otherwise use modtime-size check.
Do you think it is a good idea to modify Equal() itself's logic.

**Comment by wloot** [comment]
> Perhaps what we should be doing is calling
> 
> https://github.com/rclone/rclone/blob/2bc2546d5c93d8a34361e546279e991986090c3f/fs/operations/operations.go#L55
> 
> And if `equal && ht != hash.None` then skip the transfer and set the ModTime of the destination instead.

https://github.com/rclone/rclone/blob/f1f923a986ca193f13ec55dfef31c92f66dd6369/fs/operations/operations.go#L226

It seems the case that remote does not support check sum is checked in equal().

> 
> This is slightly annoying duplication of the logic in `Equal` - however `Equal` is designed for syncing which is less demanding than mounting in a lot of ways.
> 
> Whatever logic we decide on it needs a test :-)
> 
> Another thought crosses my mind - how common is it to alter a file and leave it the same? This patch makes us checksum every file we are about to update which potentially slows everything down.

Perhaps check modtime & size is enough and only do hash check when `--checksum` is set. And user who do not like this can set `--ignore-times` so that we skip all check.

**Comment by wloot** [comment]
> Another thought crosses my mind - how common is it to alter a file and leave it the same? This patch makes us checksum every file we are about to update which potentially slows everything down.

This is actually common in my use case, emby writes same content to metadata file within almost every check cycle, in the meantime there are thousands of metadata files.

**Comment by ivandeex** [comment]
This patch fixes a corner case and has potential to break stuff for a lot of existing cases/
I think we'd better reject this proposal for safety sake and postpone solution to
- https://github.com/rclone/rclone/issues/4810

**Comment by ivandeex** [comment]
If this ever gets accepted,
this must use a dedicated vfs flag like `--vfs-no-upload-if-same-data`
and a have a clear explanation of a warranting user case in the vfs docs

**Comment by ivandeex** [comment]
Captured the requested behavior as a new user case in https://github.com/rclone/rclone/issues/4810#issuecomment-972987493

**Comment by ivandeex** [comment]
In its current form, this PR cannot be accepted.
I wrote the requirements above.

P.S. Generally, the change detection logic in rclone has come to the verge of unsupportable. It requires deeper overall discussion rather than the stream of small per-user-case optimizations.

**Pull request closed without merging**
