### PR TITLE
oauthutil: add Shutdown method to avoid goroutine leaks

### PR DESCRIPTION
**Pull request by rkonfj**
#### What is the purpose of this change?
Before this change, calling the `oauthutil.NewRenew` func may cause goroutine leaks.

This change adds a `Shutdown` method to allow the caller to exit the goroutine to avoid leaks.

#### Was the change discussed in an issue or in the forum before?
None.

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by rkonfj** [comment]
See also #6692 .

**Comment by rkonfj** [comment]
Hi @ncw , can this be merged? 
:)

**Comment by ncw** [comment]
Nothing seems to call the Shutdown method?

**Comment by rkonfj** [comment]
> Nothing seems to call the Shutdown method?

I checked some backends, amazonclouddrive, box, onedrive, pcloud and other cloud disks call `oauthutil.NewRenew`. 
If this PR is merged, I will create additional PRs (implementing fs.Shutdowner) so that they can release resources.

@ncw May I?

**Comment by ncw** [comment]
> > Nothing seems to call the Shutdown method?
> 
> I checked some backends, amazonclouddrive, box, onedrive, pcloud and other cloud disks call `oauthutil.NewRenew`. If this PR is merged, I will create additional PRs (implementing fs.Shutdowner) so that they can release resources.
> 
> @ncw May I?

I see :-)

Can you add them as separate commits to this PR (this could be one commit with all the changes to the backends or one per backend whichever you like)? I like new code to have users before I merge it.

Thank you.

**Comment by rkonfj** [comment]
@ncw 
Done, review it again please.

**Review by ncw — APPROVED** [review]
Looks perfect - thank you :-)

I'll merge it now.

**Pull request merged**
