### PR TITLE
Clarify the docs of remote control - operations/copyfile

### PR DESCRIPTION
**Pull request by yuudi**
#### What is the purpose of this change?

The document need to be clarified. I have been struggling for this and find an answer from [this thread](https://forum.rclone.org/t/rclone-rc-operations-copyfile-copy-local-file-to-remote-fail/15608/3). This pull request is to help others avoid the same problem.

#### Was the change discussed in an issue or in the forum before?

It is discussed in the forum 2 years ago <https://forum.rclone.org/t/rclone-rc-operations-copyfile-copy-local-file-to-remote-fail/15608/3>

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ncw** [comment]
This particular phrase is repeated many many times throughout the docs.

I'd prefer to only write it once - maybe a section near the top explaining what `srcFs` etc mean might be best? What do you think?

**Comment by yuudi** [comment]
> This particular phrase is repeated many many times throughout the docs.
> 
> I'd prefer to only write it once - maybe a section near the top explaining what `srcFs` etc mean might be best? What do you think?

It is not good idea to repeat I will going to modify this. Since people may not notice the section on somewhere else, I am thinking to put annotation subscript to every `srcFs` to help people find the section of explanation. I want to know is it OK for the unity of style of the document?

I am going to modify the pull request soon.

**Comment by yuudi** [comment]
> This particular phrase is repeated many many times throughout the docs.
> 
> I'd prefer to only write it once - maybe a section near the top explaining what `srcFs` etc mean might be best? What do you think?

Thank you for reviewing.

I have noticed that this document is auto-generated from the help string in the source code, and only this `moveOrCopyFile` need to be clarify. Other functions with `srcFs` does not need to be clarify because that includes the whole path. Only `moveOrCopyFile` use separated `srcFs` and `srcRemote`.

I have edited that file and updated the pull request.

**Review by ncw — APPROVED** [review]
That looks great now - thanks.

I should have spotted that it was in auto generated docs.

I'll merge now :-)

**Comment by ncw** [comment]
Whoops, forgot to merge this!

**Pull request merged**
