### PR TITLE
chunker: implement Resumer interface

### LINKED ISSUE #5154: chunker: implement Resumer interface
### What is your current rclone version?

1.54.1

### What problem are you are trying to solve?

This ticket requests the _Resume_ feature in the chunker backend.

from https://github.com/rclone/rclone/issues/87#issuecomment-671506822 by @mcalman:

> I'm interested in addressing the case when an upload is interrupted for a large file, and must be restarted. It would be nice if the user was able to resume uploading that file from where they left off [...]
> I have been looking into using the chunker backend to support an upload resume feature. I noticed that when an upload is done with chunker and is quit during a file upload, the chunks that have already been uploaded are left on the remote, but then ignored. I have been working on modifying rclone chunker to check for these existing chunks, and if present, use them rather than re-upload those chunks.

Note that here we ask only for _sequential resume_, which is irrelevant to the _multi-thread upload feature_ covered by requests #5041 (for chunker) and #4798 (general discussion).

### How do you think rclone should be changed to solve that?

from the 1st https://github.com/rclone/rclone/pull/4547#discussion_r583522691:

> We can't just chain to the lower backend in general case. If a file is chunked, its remote will chain to a small metadata (or nothing if metadata is disabled). If it's not chunked, it can become chunked after resume, but we can't predict it [in a general case].

from the 2nd https://github.com/rclone/rclone/pull/4547#discussion_r583543773:

> Chunker can tolerate objects uploaded from multiple clients thanks to transactions [and save partially uploaded chunks per transaction].
Later, upon a resume request it can select the "best" incomplete transaction given the rolling hash state and size of already uploaded chunks.

from the 3rd https://github.com/rclone/rclone/pull/4547#discussion_r583534761:

> Golang's [Hash](https://golang.org/pkg/hash/#example__binaryMarshaler) interface allows to [save](https://golang.org/pkg/encoding/#BinaryMarshaler)/restore intermediate hash state for any (TBC) type of hash.
> [The common Resume handler will] [keep](https://golang.org/pkg/encoding/base64/#example) it in the resume metadata json together with hash name,
> [and will] negotiate with [chunker] whether operation should be continued from the last point or [retry] from the start

from the 4th https://github.com/rclone/rclone/pull/4547#issuecomment-786593956:

> [Let's] add a new per-transaction control chunk to save info about partial hash and [probably] hashes of uploaded chunks.
>
> [Let's also] add a code that selects transaction to resume given a partial hash and the total uploaded size so far. Maybe select the "best" partial transaction (when rename is fast) or just pick a single partial transaction ID (when it's slow).

This change will create a new version of the chunker metadata and grow the number of tested combinations. I think we can commit this together with other chunker PRs on a _dedicated branch_ which will produce a beta release for public beta-testing. Later we can merge these commits together from there on the master branch using a single metadata version number.

### References

- Related to feature request #87 (Resume uploads)
- Blocks on pull request #4547 (add Resumer interface)
- _Orthogonal_ to feature request #5041 (multi-thread uploads in chunker)
- _Orthogonal_ to discussion #4798 (multi-thread uploads for different backends)
- Related to thread https://forum.rclone.org/t/intelligent-faster-chunker-file-updates-on-checksum-enabled-remotes/22313/7

### PR DESCRIPTION
**Pull request by mcalman**
#### What is the purpose of this change?

Implement the Resumer interface for the Chunker backend. Thus, making resumable uploads possible for Chunker.

#### Was the change discussed in an issue or in the forum before?

Fixes #5154
Based on pull request #4547 (add Resumer interface)
Related to feature request #87 (Resume uploads)
Related to thread https://forum.rclone.org/t/intelligent-faster-chunker-file-updates-on-checksum-enabled-remotes/22313/7

Orthogonal to feature request #5041 (multi-thread uploads in chunker)
Orthogonal to discussion #4798 (multi-thread uploads for different backends)

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ ] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by Zstro** [comment]
How to record resumeOpt.Pos when failed part was among succeeded parts(like 1-5 succeeded,  6 failed, 7-10 succeeded) in multi-thread-upload

**Comment by ivandeex** [comment]
@Zstro This PR is unrelated to multi-thread uploads. They will be covered by another interface.

**Comment by Zstro** [comment]
@ivandeex Have you done demo or some else?

**Comment by ivandeex** [comment]
@Zstro Your questions belong with discussion #4798

**Comment by ivandeex** [comment]
You will need to rebase this PR when the base PR #4547 gets merged eventually.

**Comment by ivandeex** [comment]
@mcalman 
I rebased this PR on top of current rclone master with added PR #4547, do not force-push now! The pre-state of commits is saved at [ivandeex/mcalman-chunker-implement-resumer](https://github.com/ivandeex/rclone/tree/mcalman-chunker-implement-resumer).

Please add relevant unit tests.

**Comment by ivandeex** [comment]
@mcalman 
I rebased this PR on top of current rclone master with added PR #4547.
Please don't force-push now.

The pre-state of commits is saved at [ivandeex/mcalman-chunker-implement-resumer](https://github.com/ivandeex/rclone/tree/mcalman-chunker-implement-resumer).

Please add relevant unit tests!

**Comment by mcalman** [comment]
> BTW, #4547 added a test where source does not change during interrupt. It would be good to also have a test where users attempts to resume from modified source, verify that resume machinery rejects it and think whether in result it feels convenient for end user.

@ivandeex I added an adapted version of the test from #4547 as well as a new version of the test that uses a modified source. Currently, if a user has resuming enabled with --resume-larger and a modified source file is detected the resume is skipped for that file and the file is uploaded from scratch (a debug message also announces this).

**Comment by ivandeex** [comment]
@mcalman So the file is uploaded normally but with longer delay, right?

**Comment by ivandeex** [comment]
I guess you know how to calm angry go linter :)
https://github.com/rclone/rclone/pull/5185/checks?check_run_id=3175453127#step:14:25

**Comment by ivandeex** [comment]
@ncw This one is ready. Please give it your ~~applause~~ review

**Review by ivandeex — APPROVED** [review]

**Comment by ivandeex** [comment]
rebased on fresh #4547 resolving a conflict after recent master merges
don't force-push

**Comment by mcalman** [comment]
@ivandeex I noticed this PR is marked for v1.58 while the Resumer interface PR (#4547) is marked for v1.57. Pending @ncw 's review, do we think it may be possible to include both PRs in v1.57? This way there is some resume functionality for users to begin using.

**Comment by ivandeex** [comment]
cc @ncw

**Comment by ivandeex** [comment]
> @do we think it may be possible to include both PRs in v1.57?

I can't give a concrete answer in view of @ncw review delays increasing unpredictably.

> This way there is some resume functionality for users to begin using.

I published a release on my repo fork with this goal in the mind. You could advertise your development on rclone forum to attract more volunteers. If you could demonstrate a convenient use case e.g. resuming a large download to local disk, it would bring more attention.

**Comment by ivandeex** [comment]
@ncw :pray: :pray: :pray:

**Review by ncw — COMMENTED** [review]
I'm happy for you to rebase and merge this after we've merged #4547 :-)

**Comment by ivandeex** [comment]
@mcalman
Unfortunately this PR is waiting for
- #4547 
which in turn is waiting for @ncw to review
- #5299
which is spin off of
- #3850
which is stuck forever.
I am sure we can solve it
I am going to untangle the knot when I have enough time for it,
say around next January
In the meantime I have added the patch from this PR on top of #4547
At any rate I will consider all parts together
I am closing this for now
cc @ncw

**Pull request closed without merging**
