### PR TITLE
Fully automate dev setup with Gitpod

### PR DESCRIPTION
**Pull request by k84shailendra**
This commit implements a fully-automated development setup using Gitpod.io, an
online IDE for GitHub and GitLab that enables Dev-Environments-As-Code.
This makes it easy for anyone to get a ready-to-code workspace for any branch,
issue or pull request almost instantly with a single click.

#### Checklist

- [ ] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [ ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ ] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ivandeex** [comment]
@darthShadow
Could you please take a look at this?
I remember, you have experience with rclone installers?

**Comment by darthShadow** [comment]
This is not exactly an installer but a Web IDE for developers to start with.

This looks like a better and more deeply integrated alternative: https://github.com/features/codespaces

@ncw Any chance you already have access to the beta for it or can you apply for it for rclone?

**Comment by ivandeex** [comment]
From my personal point of view, this needs more documentation, at least an intro or getting started. I never used gitpod and looking at the patch I don't see how this change can improve life of an rclone hacker.

**Comment by ivandeex** [comment]
This PR does not have any updates since 4 months.

cc @ncw

**Comment by darthShadow** [comment]
[Github Codespaces](github.com/features/codespaces) still seems like a much better alternative

**Comment by ivandeex** [comment]
_Cross-post._

We have PR #5303 by @olefrost that improves the contributor documentation w.r.t. standard tools like git.

We also have PR #4771 which strives for easing the setup of web-based dev environment. However it lacks any docs making it rather useless.

It would be nice @olefrost and @k84shailendra could coordinate their efforts. Just an idea.

**Comment by olefrost** [comment]
I do like the idea of easily spinning up a pre-configured development environment to make a simple change. Both GitPod and Codespaces are good candidates for this.
 
It is however my impression, that the merge of this PR depends on a some  general decisions to be taken by the rclone core team:

1. Do we want ads for commercial products in the top left corner of the readme file?
2. Do we want to guide developers towards a single commercial service having a price per hour? (after the free lunch)
3. Do we want to build, test, and maintain image definitions for all [online integrated development environments](https://en.wikipedia.org/wiki/Online_integrated_development_environment)?

My personal opinion is "no" and I guess this is in line with the rclone mindset I have experienced so far.
 
Having said that, it could make good sense to include a tip about GitHub CodeSpaces, once it is out of beta - if it is free for  open source contributors. But I really don't think it will be needed; I guess Github will promote Codespaces right next to the fork button :)

**Comment by ivandeex** [comment]
@k84shailendra 
I can see that this PR lacks team interest.
You still can add gitpod related instructions and snippets to https://github.com/rclone/rclone/wiki
It's publicly open

**Comment by ivandeex** [comment]
If anyone is interested, I personally use https://github.com/cdr/code-server on a VPS. The setup is as simple as: apt-get install deb, adjust small yaml (or toml? I forgot) file and open a port in ubuntu ufw. Everything else is done online. In fact codespaces and gitpod are the same vscode-server plus some integrations.

**Comment by ivandeex** [comment]
Closing

**Pull request closed without merging**
