### PR TITLE
Add Copy to Local Backend

### PR DESCRIPTION
**Pull request by DWSR**
#### What is the purpose of this change?

This change implements the Copy feature on the `local` backend in order to fix an issue with the `tmp_upload_path` feature of the `cache` backend.

#### Was the change discussed in an issue or in the forum before?

https://github.com/rclone/rclone/issues/3206

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [ ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ ] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ncw** [comment]
What is the problem in the cache backend that you are trying to fix?

I think there may be an easier way to fix it there?

**Comment by DWSR** [comment]
> What is the problem in the cache backend that you are trying to fix?
> 
> 
> 
> I think there may be an easier way to fix it there?

The issue is the one linked in the PR body. Basically the cache backend needs to support a superset of all of the features supported by the wrapped backend when using `tmp_upload_path` and since that feature is implemented using the local backend and the local backend is missing Copy, server side copies are not supported when using the cache backend in that configuration.

There might be an easier way to do this but it looks like there are some assumptions made about the way that everything operates that requires the Copy feature to be implemented. That being said, I could be missing something. I’m certainly not a Go expert, nor well versed in rclone.

**Comment by ncw** [comment]
I've replied with some ideas on the original issue

**Comment by DWSR** [comment]
Based on comments from @ncw, choosing to solve this in another manner.

**Pull request closed without merging**
