### PR TITLE
Improve description for SeaweedFS

### PR DESCRIPTION
**Pull request by chrislusf**
#### What is the purpose of this change?

Improve description for SeaweedFS

#### Was the change discussed in an issue or in the forum before?

N/A

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by chrislusf** [comment]
@ivandeex I wonder why this issue was assigned to me. Was there something I should do now?

**Comment by ivandeex** [comment]
>  I wonder why this was assigned back to me.

Just for quick lookup

@albertony 
Please review

**Review by albertony — APPROVED** [review]

**Comment by ivandeex** [comment]
Merged. Thank you.

**Comment by chrislusf** [comment]
Thanks!

**Pull request merged**
