### PR TITLE
backend: adding description option to all backend filesystems

### PR DESCRIPTION
**Pull request by andrewwillette**
#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ ] I'm done, this Pull Request is ready for review :-)

Attempting to add the feature as discussed in [this issue](https://github.com/rclone/rclone/issues/4391).

A piece I could be missing, but I'm unsure of how it's used, is adding documentation to each of the markdown files for the backends for `--description` or `--s3-description` [here for s3](https://github.com/rclone/rclone/blame/5ce3019fc1b64fccfce3aef7e25be97ee453fca2/docs/content/s3.md#L1823), and this would apply to each of the backends.

If I'm missing tests, please let me know. It wasn't clear to me that the backends test that each of the options exist.

Thank you!

### CODE REVIEW

**Comment by albertony** [comment]
Nice!

> A piece I could be missing, but I'm unsure of how it's used, is adding documentation to each of the markdown files for the backends for --description or --s3-description [here for s3](https://github.com/rclone/rclone/blame/5ce3019fc1b64fccfce3aef7e25be97ee453fca2/docs/content/s3.md#L1823), and this would apply to each of the backends.

Documentation of the option will be added to markdown files automatically, in time for release. So as long as you write a `Help:` string you are covered.

PS: Some linting errors, it expects whitespace alignment like this:
```
Name:     config.ConfigDescription,
Help:     config.ConfigDescriptionHelp,
Advanced: true,
```

**Comment by andrewwillette** [comment]
@albertony, thanks for the feedback, I really appreciate it. I believe I've fixed the linting issues. (not sure how to trigger build, guessing maybe you do it [manually](https://github.com/rclone/rclone/actions/runs/1919738523/workflow#L18)?) I don't know.

Please let me know if anything else is needed/desired, I'll gladly do it.

**Comment by ncw** [comment]
I wonder whether the description definition is in the right place.

To be useful, we probably need this in the layer above the backends - none of the backends use the description in the config, but we want it there so we can display it to the user (eg in `rclone listremotes`) or the user can see it in the config file.

Maybe we should be asking for the desciption as part of the remote creation / update rather than injecting it into each backend?

We have one parameter like that already `type` which isn't handled by the backend.

What do you think?

**Comment by andrewwillette** [comment]
@ncw and @albertony, I've force pushed updates to set the "description" option via the RegisterInfo#Config callback.

If you have time, I'd love to get feedback/+1s.

Thanks so much,
Andrew

**Comment by andrewwillette** [comment]
Closing due to staleness.

**Pull request closed without merging**
