### PR TITLE
Docs: Zoho WorkDrive authorisation reword

### PR DESCRIPTION
**Pull request by edwardxml**
Mainly the reference to firewalls didn't make sense. Tried to make more precise. Left z in authorize.

#### What is the purpose of this change?

Tidy up wording encountered whilst reading docs.

#### Was the change discussed in an issue or in the forum before?
No.

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [ ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ivandeex** [comment]
@ncw
AFAICS author marked this PR as ready for review.

**Comment by ivandeex** [comment]
@ncw
I can't find an easy way on Github to find all requests waiting for one's (my) review.
So I marked all request waiting for anyone's review by relevant assignments.
This way you can quickly skip something you don't have to check.

**Comment by ncw** [comment]
@edwardxml thank you - I'll merge that now.



> @ncw
> I can't find an easy way on Github to find all requests waiting for one's (my) review.

Have you tried the advanced search? You can search for things [without tags](https://github.com/rclone/rclone/issues?q=is%3Aissue+is%3Aopen+no%3Alabel+sort%3Aupdated-asc+) which can be helpful. What criteria are you trying to match?

I use https://octobox.io to managage the notifications from GitHub

> So I marked all request waiting for anyone's review by relevant assignments.
> This way you can quickly skip something you don't have to check

Thank you

> Full-scanning is not optimal.

O(N) indeed :-)

**Comment by ivandeex** [comment]
> Have you tried the advanced search? You can search for things [without tags](https://github.com/rclone/rclone/issues?q=is%3Aissue+is%3Aopen+no%3Alabel+sort%3Aupdated-asc+) which can be helpful. What criteria are you trying to match?

Advanced search is advanced, but
https://github.com/rclone/rclone/pulls/assigned/ncw
Simple search is simple :)

**Pull request merged**
