### PR TITLE
protondrive: fix signature verification issue

### PR DESCRIPTION
**Pull request by henrybear327**
#### What is the purpose of this change?

To address the signature verification issue mentioned [here](https://github.com/rclone/rclone/issues/6072)

The changes are discussed / logged at https://github.com/henrybear327/Proton-API-Bridge/issues/3

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by henrybear327** [comment]
I personally haven't encountered this issue, so we will have to rely on the community's feedback via this thread https://github.com/rclone/rclone/issues/6072#issuecomment-1707429889.

**Comment by AimVaguely** [comment]
I have run this locally from my machine with my credentials and I still got the same error:

```log
2023/09/06 15:06:41 DEBUG : rclone: Version "v1.64.0-DEV" starting with parameters ["/home/user/Downloads/rclone/__debug_bin2878197450" "cat" "proton:/test/notes.txt" "-vv" "--log-file=rclone1.log"]
2023/09/06 15:06:41 DEBUG : Creating backend with remote "proton:/test/notes.txt"
2023/09/06 15:06:41 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2023/09/06 15:06:41 DEBUG : proton drive root link ID 'test/notes.txt': Has cached credentials
2023/09/06 15:06:45 DEBUG : proton drive root link ID 'test/notes.txt': Used cached credential to initialize the ProtonDrive API
2023/09/06 15:06:48 Failed to create file system for "proton:/test/notes.txt": couldn't initialize a new root remote: Signature Verification Error: No matching signature
```

This is on commit 9651a666c8865f6571ecbd015917a8b507349a9d.

Tell me if I can help with anything specific with debugging @henrybear327. Thanks!

**Comment by henrybear327** [comment]
> I have run this locally from my machine with my credentials and I still got the same error:
> 
> ```
> 2023/09/06 15:06:41 DEBUG : rclone: Version "v1.64.0-DEV" starting with parameters ["/home/user/Downloads/rclone/__debug_bin2878197450" "cat" "proton:/test/notes.txt" "-vv" "--log-file=rclone1.log"]
> 2023/09/06 15:06:41 DEBUG : Creating backend with remote "proton:/test/notes.txt"
> 2023/09/06 15:06:41 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
> 2023/09/06 15:06:41 DEBUG : proton drive root link ID 'test/notes.txt': Has cached credentials
> 2023/09/06 15:06:45 DEBUG : proton drive root link ID 'test/notes.txt': Used cached credential to initialize the ProtonDrive API
> 2023/09/06 15:06:48 Failed to create file system for "proton:/test/notes.txt": couldn't initialize a new root remote: Signature Verification Error: No matching signature
> ```
> 
> This is on commit [9651a66](https://github.com/rclone/rclone/commit/9651a666c8865f6571ecbd015917a8b507349a9d).
> 
> Tell me if I can help with anything specific with debugging @henrybear327. Thanks!

Hello @AimVaguely, 

Thanks for the quick testing. I will be putting up another version soon, and hopefully, this one will work! (Just discovered more cases to cover!)

**Comment by henrybear327** [comment]
> I have run this locally from my machine with my credentials and I still got the same error:
> 
> ```
> 2023/09/06 15:06:41 DEBUG : rclone: Version "v1.64.0-DEV" starting with parameters ["/home/user/Downloads/rclone/__debug_bin2878197450" "cat" "proton:/test/notes.txt" "-vv" "--log-file=rclone1.log"]
> 2023/09/06 15:06:41 DEBUG : Creating backend with remote "proton:/test/notes.txt"
> 2023/09/06 15:06:41 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
> 2023/09/06 15:06:41 DEBUG : proton drive root link ID 'test/notes.txt': Has cached credentials
> 2023/09/06 15:06:45 DEBUG : proton drive root link ID 'test/notes.txt': Used cached credential to initialize the ProtonDrive API
> 2023/09/06 15:06:48 Failed to create file system for "proton:/test/notes.txt": couldn't initialize a new root remote: Signature Verification Error: No matching signature
> ```
> 
> This is on commit [9651a66](https://github.com/rclone/rclone/commit/9651a666c8865f6571ecbd015917a8b507349a9d).
> 
> Tell me if I can help with anything specific with debugging @henrybear327. Thanks!

Hello @AimVaguely, 

I have made a new mechanism for verifying the signatures, but I have force-pushed to the branch since I squashed the commits. 

When you have time, can you please give it a last try :) Fingers crossed for the verification. 

If this one still fails, I will then be doing a special build for you with aggressive logging. 

Thank you!

**Comment by DankestOfMemers** [comment]
Hi there. Chiming in as someone who has an old Proton account and is eagerly awaiting being able to use it with rclone: when I `ls` with this build, it mostly works, but I get a bunch of signature verification errors. And it refuses to mount due to a signature verification error.

**Comment by henrybear327** [comment]
> Hi there. Chiming in as someone who has an old Proton account and is eagerly awaiting being able to use it with rclone: when I `ls` with this build, it mostly works, but I get a bunch of signature verification errors. And it refuses to mount due to a signature verification error.

Hello @DankestOfMemers!

Thanks for the feedback!! I will prepare a commit on top of this PR aggressively reports at what stage the signature verification failed …

In the meantime, can you provide the current log :) So I can understand what you mean by mostly work :)

Thank you!

**Comment by DankestOfMemers** [comment]
Thanks for all your hard work on this! Mounting the root directory of my Proton Drive worked but not one of the subdirectories. Here's the log (I changed the filenames for privacy):

```
2023/09/06 18:29:07 DEBUG : rclone: Version "v1.64.0-DEV" starting with parameters ["./rclone" "ls" "remote:" --log-file" "rclone.log" "--log-level" "DEBUG"]
2023/09/06 18:29:07 DEBUG : Creating backend with remote "remote:"
2023/09/06 18:29:07 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2023/09/06 18:29:07 DEBUG : proton drive root link ID '': Has cached credentials
2023/09/06 18:29:12 DEBUG : proton drive root link ID '': Used cached credential to initialize the ProtonDrive API
2023/09/06 18:29:16 ERROR : Documents: error listing: Signature Verification Error: Missing signature
2023/09/06 18:29:18 ERROR : FILE1: Original size should exist
2023/09/06 18:29:18 ERROR : FILE1: Original size should exist
2023/09/06 18:29:21 ERROR : FILE2: Original size should exist
2023/09/06 18:29:21 ERROR : FILE3: Original size should exist
2023/09/06 18:29:21 ERROR : FILE2: Original size should exist
2023/09/06 18:29:21 ERROR : FILE3: Original size should exist
2023/09/06 18:29:42 ERROR : FILE4: Original size should exist
2023/09/06 18:29:42 ERROR : FILE4: Original size should exist
2023/09/06 18:41:07 DEBUG : 5 go routines active
2023/09/06 18:41:07 Failed to ls with 2 errors: last error was: Signature Verification Error: Missing signature
2023/09/06 18:58:38 DEBUG : rclone: Version "v1.64.0-DEV" starting with parameters ["./rclone" "mount" "remote:" "./mnt" "--log-file" "rclone.log" "--log-level" "DEBUG"]
2023/09/06 18:58:38 DEBUG : Creating backend with remote "remote:"
2023/09/06 18:58:38 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2023/09/06 18:58:38 DEBUG : proton drive root link ID '': Has cached credentials
2023/09/06 18:58:42 DEBUG : proton drive root link ID '': Used cached credential to initialize the ProtonDrive API
2023/09/06 18:58:42 INFO  : proton drive root link ID '': poll-interval is not supported by this remote
2023/09/06 18:58:42 NOTICE: proton drive root link ID '': --vfs-cache-mode writes or full is recommended for this remote as it can't stream
2023/09/06 18:58:42 DEBUG : proton drive root link ID '': Mounting on "./mnt"
2023/09/06 18:58:42 DEBUG : : Root: 
2023/09/06 18:58:42 DEBUG : : >Root: node=/, err=<nil>
2023/09/06 18:58:42 DEBUG : /: Lookup: name="BDMV"
2023/09/06 18:58:42 DEBUG : /: Attr: 
2023/09/06 18:58:43 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2023/09/06 18:58:43 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:58:43 DEBUG : /: Lookup: name=".xdg-volume-info"
2023/09/06 18:58:43 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2023/09/06 18:58:43 DEBUG : /: Lookup: name="autorun.inf"
2023/09/06 18:58:43 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2023/09/06 18:58:43 DEBUG : /: Lookup: name=".Trash"
2023/09/06 18:58:43 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2023/09/06 18:58:43 DEBUG : /: ReadDirAll: 
2023/09/06 18:58:43 DEBUG : /: >ReadDirAll: item=24, err=<nil>
2023/09/06 18:58:43 DEBUG : /: Attr: 
2023/09/06 18:58:43 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:58:43 DEBUG : /: ReadDirAll: 
2023/09/06 18:58:43 DEBUG : /: >ReadDirAll: item=24, err=<nil>
2023/09/06 18:58:43 DEBUG : /: Lookup: name=".Trash-1000"
2023/09/06 18:58:43 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2023/09/06 18:58:43 DEBUG : /: Attr: 
2023/09/06 18:58:43 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:58:43 DEBUG : /: ReadDirAll: 
2023/09/06 18:58:43 DEBUG : /: >ReadDirAll: item=24, err=<nil>
2023/09/06 18:58:43 DEBUG : /: Attr: 
2023/09/06 18:58:43 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:58:43 DEBUG : /: ReadDirAll: 
2023/09/06 18:58:43 DEBUG : /: >ReadDirAll: item=24, err=<nil>
2023/09/06 18:58:43 DEBUG : /: Attr: 
2023/09/06 18:58:43 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:58:43 DEBUG : /: ReadDirAll: 
2023/09/06 18:58:43 DEBUG : /: >ReadDirAll: item=24, err=<nil>
2023/09/06 18:58:43 DEBUG : /: Attr: 
2023/09/06 18:58:43 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:58:43 DEBUG : /: ReadDirAll: 
2023/09/06 18:58:43 DEBUG : /: >ReadDirAll: item=24, err=<nil>
2023/09/06 18:58:43 DEBUG : /: Attr: 
2023/09/06 18:58:43 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:58:43 DEBUG : /: ReadDirAll: 
2023/09/06 18:58:43 DEBUG : /: >ReadDirAll: item=24, err=<nil>
2023/09/06 18:58:43 DEBUG : /: Attr: 
2023/09/06 18:58:43 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:58:43 DEBUG : /: ReadDirAll: 
2023/09/06 18:58:43 DEBUG : /: >ReadDirAll: item=24, err=<nil>
2023/09/06 18:58:43 DEBUG : /: Attr: 
2023/09/06 18:58:43 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:58:43 DEBUG : /: ReadDirAll: 
2023/09/06 18:58:43 DEBUG : /: >ReadDirAll: item=24, err=<nil>
2023/09/06 18:58:43 DEBUG : /: Attr: 
2023/09/06 18:58:43 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:58:43 DEBUG : /: ReadDirAll: 
2023/09/06 18:58:43 DEBUG : /: >ReadDirAll: item=24, err=<nil>
2023/09/06 18:58:43 DEBUG : /: Attr: 
2023/09/06 18:58:43 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:58:43 DEBUG : /: ReadDirAll: 
2023/09/06 18:58:43 DEBUG : /: >ReadDirAll: item=24, err=<nil>
2023/09/06 18:58:43 DEBUG : /: Attr: 
2023/09/06 18:58:43 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:58:43 DEBUG : /: ReadDirAll: 
2023/09/06 18:58:43 DEBUG : /: >ReadDirAll: item=24, err=<nil>
2023/09/06 18:58:43 DEBUG : /: Attr: 
2023/09/06 18:58:43 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:58:43 DEBUG : /: ReadDirAll: 
2023/09/06 18:58:43 DEBUG : /: >ReadDirAll: item=24, err=<nil>
2023/09/06 18:58:43 DEBUG : /: Attr: 
2023/09/06 18:58:43 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:58:43 DEBUG : /: ReadDirAll: 
2023/09/06 18:58:43 DEBUG : /: >ReadDirAll: item=24, err=<nil>
2023/09/06 18:58:43 DEBUG : /: Attr: 
2023/09/06 18:58:43 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:58:43 DEBUG : /: ReadDirAll: 
2023/09/06 18:58:43 DEBUG : /: >ReadDirAll: item=24, err=<nil>
2023/09/06 18:58:43 DEBUG : /: Attr: 
2023/09/06 18:58:43 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:58:43 DEBUG : /: ReadDirAll: 
2023/09/06 18:58:43 DEBUG : /: >ReadDirAll: item=24, err=<nil>
2023/09/06 18:58:43 DEBUG : /: Attr: 
2023/09/06 18:58:43 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:58:43 DEBUG : /: ReadDirAll: 
2023/09/06 18:58:43 DEBUG : /: >ReadDirAll: item=24, err=<nil>
2023/09/06 18:58:43 DEBUG : /: Attr: 
2023/09/06 18:58:43 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:58:43 DEBUG : /: ReadDirAll: 
2023/09/06 18:58:43 DEBUG : /: >ReadDirAll: item=24, err=<nil>
2023/09/06 18:58:43 DEBUG : /: Attr: 
2023/09/06 18:58:43 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:58:43 DEBUG : /: ReadDirAll: 
2023/09/06 18:58:43 DEBUG : /: >ReadDirAll: item=24, err=<nil>
2023/09/06 18:58:43 DEBUG : /: Attr: 
2023/09/06 18:58:43 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:58:43 DEBUG : /: ReadDirAll: 
2023/09/06 18:58:43 DEBUG : /: >ReadDirAll: item=24, err=<nil>
2023/09/06 18:58:43 DEBUG : /: Attr: 
2023/09/06 18:58:43 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:58:43 DEBUG : /: ReadDirAll: 
2023/09/06 18:58:43 DEBUG : /: >ReadDirAll: item=24, err=<nil>
2023/09/06 18:58:43 DEBUG : /: Attr: 
2023/09/06 18:58:43 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:58:43 DEBUG : /: ReadDirAll: 
2023/09/06 18:58:43 DEBUG : /: >ReadDirAll: item=24, err=<nil>
2023/09/06 18:58:43 DEBUG : /: Attr: 
2023/09/06 18:58:43 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:58:43 DEBUG : /: ReadDirAll: 
2023/09/06 18:58:43 DEBUG : /: >ReadDirAll: item=24, err=<nil>
2023/09/06 18:58:43 DEBUG : /: Attr: 
2023/09/06 18:58:43 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:58:43 DEBUG : /: ReadDirAll: 
2023/09/06 18:58:43 DEBUG : /: >ReadDirAll: item=24, err=<nil>
2023/09/06 18:58:43 DEBUG : /: Attr: 
2023/09/06 18:58:43 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:58:43 DEBUG : /: ReadDirAll: 
2023/09/06 18:58:43 DEBUG : /: >ReadDirAll: item=24, err=<nil>
2023/09/06 18:58:43 DEBUG : /: Attr: 
2023/09/06 18:58:43 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:58:43 DEBUG : /: ReadDirAll: 
2023/09/06 18:58:43 DEBUG : /: >ReadDirAll: item=24, err=<nil>
2023/09/06 18:58:43 DEBUG : /: Lookup: name="autorun.inf"
2023/09/06 18:58:43 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2023/09/06 18:58:43 DEBUG : /: Attr: 
2023/09/06 18:58:43 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:58:43 DEBUG : : Statfs: 
2023/09/06 18:58:44 DEBUG : : >Statfs: stat={Blocks:212336640 Bfree:26527699 Bavail:26527699 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2023/09/06 18:59:25 DEBUG : /: Attr: 
2023/09/06 18:59:25 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:59:25 DEBUG : /: ReadDirAll: 
2023/09/06 18:59:25 DEBUG : /: >ReadDirAll: item=24, err=<nil>
2023/09/06 18:59:25 DEBUG : /: Lookup: name="DIR1"
2023/09/06 18:59:25 DEBUG : /: >Lookup: node=DIR1/, err=<nil>
2023/09/06 18:59:25 DEBUG : DIR1/: Attr: 
2023/09/06 18:59:25 DEBUG : DIR1/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:59:25 DEBUG : /: Lookup: name="DIR2"
2023/09/06 18:59:25 DEBUG : /: >Lookup: node=DIR2/, err=<nil>
2023/09/06 18:59:25 DEBUG : DIR2/: Attr: 
2023/09/06 18:59:25 DEBUG : DIR2/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:59:25 DEBUG : /: Lookup: name="DIR3"
2023/09/06 18:59:25 DEBUG : /: >Lookup: node=DIR3/, err=<nil>
2023/09/06 18:59:25 DEBUG : DIR3: Attr: 
2023/09/06 18:59:25 DEBUG : DIR3/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:59:25 DEBUG : /: Lookup: name="DIR4"
2023/09/06 18:59:25 DEBUG : /: >Lookup: node=DIR4/, err=<nil>
2023/09/06 18:59:25 DEBUG : DIR4: Attr: 
2023/09/06 18:59:25 DEBUG : DIR4/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:59:25 DEBUG : /: Lookup: name="DIR5"
2023/09/06 18:59:25 DEBUG : /: >Lookup: node=DIR5/, err=<nil>
2023/09/06 18:59:25 DEBUG : DIR5/: Attr: 
2023/09/06 18:59:25 DEBUG : DIR5/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:59:25 DEBUG : /: Lookup: name="DIR6"
2023/09/06 18:59:25 DEBUG : /: >Lookup: node=DIR6/, err=<nil>
2023/09/06 18:59:25 DEBUG : DIR6/: Attr: 
2023/09/06 18:59:25 DEBUG : DIR6/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:59:25 DEBUG : /: Lookup: name="DIR7"
2023/09/06 18:59:25 DEBUG : /: >Lookup: node=DIR7/, err=<nil>
2023/09/06 18:59:25 DEBUG : DIR7/: Attr: 
2023/09/06 18:59:25 DEBUG : DIR7/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:59:25 DEBUG : /: Lookup: name="DIR8"
2023/09/06 18:59:25 DEBUG : /: >Lookup: node=DIR8/, err=<nil>
2023/09/06 18:59:25 DEBUG : DIR8/: Attr: 
2023/09/06 18:59:25 DEBUG : DIR8/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:59:25 DEBUG : /: Lookup: name="DIR9"
2023/09/06 18:59:25 DEBUG : /: >Lookup: node=DIR9/, err=<nil>
2023/09/06 18:59:25 DEBUG : DIR9/: Attr: 
2023/09/06 18:59:25 DEBUG : DIR9/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:59:25 DEBUG : /: Lookup: name="DIR10"
2023/09/06 18:59:25 DEBUG : /: >Lookup: node=DIR10/, err=<nil>
2023/09/06 18:59:25 DEBUG : DIR10/: Attr: 
2023/09/06 18:59:25 DEBUG : DIR10/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:59:25 DEBUG : /: Lookup: name="DIR11"
2023/09/06 18:59:25 DEBUG : /: >Lookup: node=DIR11/, err=<nil>
2023/09/06 18:59:25 DEBUG : DIR11/: Attr: 
2023/09/06 18:59:25 DEBUG : DIR11/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:59:25 DEBUG : /: Lookup: name="DIR12"
2023/09/06 18:59:25 DEBUG : /: >Lookup: node=DIR12/, err=<nil>
2023/09/06 18:59:25 DEBUG : DIR12/: Attr: 
2023/09/06 18:59:25 DEBUG : DIR12/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:59:25 DEBUG : /: Lookup: name="DIR13"
2023/09/06 18:59:25 DEBUG : /: >Lookup: node=DIR13/, err=<nil>
2023/09/06 18:59:25 DEBUG : DIR13/: Attr: 
2023/09/06 18:59:25 DEBUG : DIR13/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:59:25 DEBUG : /: Lookup: name="DIR14"
2023/09/06 18:59:25 DEBUG : /: >Lookup: node=DIR14/, err=<nil>
2023/09/06 18:59:25 DEBUG : DIR14/: Attr: 
2023/09/06 18:59:25 DEBUG : DIR14/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:59:25 DEBUG : /: Lookup: name="DIR15"
2023/09/06 18:59:25 DEBUG : /: >Lookup: node=DIR15/, err=<nil>
2023/09/06 18:59:25 DEBUG : DIR15/: Attr: 
2023/09/06 18:59:25 DEBUG : DIR15/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:59:25 DEBUG : /: Lookup: name="DIR16"
2023/09/06 18:59:25 DEBUG : /: >Lookup: node=DIR16/, err=<nil>
2023/09/06 18:59:25 DEBUG : DIR16/: Attr: 
2023/09/06 18:59:25 DEBUG : DIR16/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:59:25 DEBUG : /: Lookup: name="DIR17"
2023/09/06 18:59:25 DEBUG : /: >Lookup: node=DIR17/, err=<nil>
2023/09/06 18:59:25 DEBUG : DIR17/: Attr: 
2023/09/06 18:59:25 DEBUG : DIR17/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:59:25 DEBUG : /: Lookup: name="DIR18"
2023/09/06 18:59:25 DEBUG : /: >Lookup: node=DIR18/, err=<nil>
2023/09/06 18:59:25 DEBUG : DIR18/: Attr: 
2023/09/06 18:59:25 DEBUG : DIR18/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:59:25 DEBUG : /: Lookup: name="DIR19"
2023/09/06 18:59:25 DEBUG : /: >Lookup: node=DIR19/, err=<nil>
2023/09/06 18:59:25 DEBUG : DIR19/: Attr: 
2023/09/06 18:59:25 DEBUG : DIR19/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:59:25 DEBUG : /: Lookup: name="DIR20"
2023/09/06 18:59:25 DEBUG : /: >Lookup: node=DIR20/, err=<nil>
2023/09/06 18:59:25 DEBUG : DIR20/: Attr: 
2023/09/06 18:59:25 DEBUG : DIR20/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:59:25 DEBUG : /: Lookup: name="DIR21"
2023/09/06 18:59:25 DEBUG : /: >Lookup: node=DIR21/, err=<nil>
2023/09/06 18:59:25 DEBUG : DIR21/: Attr: 
2023/09/06 18:59:25 DEBUG : DIR21/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:59:25 DEBUG : /: Lookup: name="DIR22"
2023/09/06 18:59:25 DEBUG : /: >Lookup: node=DIR22/, err=<nil>
2023/09/06 18:59:25 DEBUG : DIR22/: Attr: 
2023/09/06 18:59:25 DEBUG : DIR22/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/09/06 18:59:47 INFO  : Signal received: interrupt
2023/09/06 18:59:47 ERROR : ./mnt: Unmounted rclone mount
2023/09/06 18:59:47 INFO  : Exiting...
2023/09/06 19:01:05 DEBUG : rclone: Version "v1.64.0-DEV" starting with parameters ["./rclone" "mount" "remote:/DIR8" "./mnt" "--log-file" "rclone.log" "--log-level" "DEBUG"]
2023/09/06 19:01:05 DEBUG : Creating backend with remote "remote:/DIR8"
2023/09/06 19:01:05 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2023/09/06 19:01:05 DEBUG : proton drive root link ID 'DIR8': Has cached credentials
2023/09/06 19:01:09 DEBUG : proton drive root link ID 'DIR8': Used cached credential to initialize the ProtonDrive API
2023/09/06 19:01:09 Failed to create file system for "remote:/DIR8": couldn't initialize a new root remote: Signature Verification Error: Missing signature
```

**Comment by henrybear327** [comment]
> Thank you, @henrybear327, It worked as expected. After I forced pulled `git reset --hard` and rebuilt it `make` It worked as it was meant to. Here is a log of what it printed if that helps, there is stuff that I don't remember seeing previously. But it did print the contents of the text file that it was meant to, and I verified that it looks correctly through looking at the same file in https://drive.proton.me.
> 
> ```
> 2023/09/07 15:58:20 DEBUG : rclone: Version "v1.64.0-beta.7331.f537e499c.protondrive/fix_signature_verification_bug" starting with parameters ["/home/user/.local/share/go/bin/rclone" "cat" "proton:/test/notes.txt" "-vv" "--log-file=rclone2.log"]
> 2023/09/07 15:58:20 DEBUG : Creating backend with remote "proton:/test/notes.txt"
> 2023/09/07 15:58:20 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
> 2023/09/07 15:58:20 DEBUG : proton drive root link ID 'test/notes.txt': Has cached credentials
> 2023/09/07 15:58:25 DEBUG : proton drive root link ID 'test/notes.txt': Used cached credential to initialize the ProtonDrive API
> 2023/09/07 15:58:32 DEBUG : fs cache: adding new entry for parent of "proton:/test/notes.txt", "proton:test"
> 2023/09/07 15:58:37 DEBUG : test2.txt: Excluded
> 2023/09/07 15:58:39 DEBUG : 8 go routines active
> ```
> 
> I have also tested with uploading a file, and it worked as expected, including drive.proton.me saying that the signature is valid.
> 
> Thank you for your amazing work.

Hi @AimVaguely, 

Thanks for the testing!! :) 

Can you also test on other directories and see if it works :) 

Thank you!

**Comment by henrybear327** [comment]
Hello @DankestOfMemers, 

Thanks for the log!! :) It's weird that it's working for @AimVaguely now but still failing in your case :( 

Do you have the following conditions:
- uploaded folder/file using iOS / Android client 
- password reset recently
- changed primary email address

Thank you! :)

**Comment by DankestOfMemers** [comment]
> Hello @DankestOfMemers,
> 
> Thanks for the log!! :) It's weird that it's working for @AimVaguely now but still failing in your case :(
> 
> Do you have the following conditions:
> 
>     * uploaded folder/file using iOS / Android client
> 
>     * password reset recently
> 
>     * changed primary email address
> 
> 
> Thank you! :)

I'm afraid the answer is yes to all three.

**Comment by henrybear327** [comment]
Hi @AimVaguely and @DankestOfMemers, 

I have put up a fix for the missing signature. Could you guys try again on the latest commit :) 

Thank you!!

Henry

**Comment by DankestOfMemers** [comment]
> Hi @AimVaguely and @DankestOfMemers,
> 
> I have put up a fix for the missing signature. Could you guys try again on the latest commit :)
> 
> Thank you!!
> 
> Henry

It works! I still get `Original size should exist` on some files when I run `ls`, but there are no more signature verification errors, and I'm able to mount.

**Comment by henrybear327** [comment]
> > Hi @AimVaguely and @DankestOfMemers,
> > I have put up a fix for the missing signature. Could you guys try again on the latest commit :)
> > Thank you!!
> > Henry
> 
> It works! I still get `Original size should exist` on some files when I run `ls`, but there are no more signature verification errors, and I'm able to mount.

Great! :) Thanks for confirming!

The `Original size should exist` message will be changed to Debug print soon! :)

**Comment by henrybear327** [comment]
FYI @ncw, this should unblock quite some users who have had the ProtonDrive account since the early days when the drive was still in Beta! So if the release is going out soon, please wait for this one to be merged (I am just waiting for the tests to pass now!)

**Pull request merged**
