### PR TITLE
dlna: change icons to the newest ones

### PR DESCRIPTION
**Pull request by hacketiwack**
#### What is the purpose of this change?
The purpose of this change is to adapt the Rclone logos to the newest ones when serving files through DLNA protocol.

#### Was the change discussed in an issue or in the forum before?
No.

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by albertony** [comment]
Great, thank you! I'm curious, how did you create the updated pngs? What was the source?

**Comment by hacketiwack** [comment]
Hi @albertony, I took the [svg](https://github.com/rclone/rclone/blob/master/graphics/logo/svg/logo_symbol_color.svg) as the source and exported it from Inkscape. Then, I optimized the PNGs so they don't embed any crap:
`pngquant --speed 1 --quality 67 rclone-48x48.png`
The compression is lossy, but difficult to see to the naked eye.

**Comment by albertony** [comment]
Thanks.
I noticed they are optimized quite hard, compared to the "official" [pngs](https://github.com/rclone/rclone/tree/master/graphics/logo/logo_symbol). E.g. this 120px file has 13 colors and size 1,4k vs official 128px has 337 colors and size 4,4k. Just mentioning it, this is not my field of expertise.

**Review by ncw — APPROVED** [review]
These are the correct logo and smaller and look OK to me which is a win so I'll merge these - thank you @hacketiwack

**Pull request merged**
