### PR TITLE
doc: fix typo in s3 documentation

### PR DESCRIPTION
**Pull request by gregsadetsky**
#### What is the purpose of this change?

fix a typo in the documentation

#### Was the change discussed in an issue or in the forum before?

no

### CODE REVIEW

**Comment by albertony** [comment]
The changed sentence:

> The modified time is stored as metadata on the object as `X-Amz-Meta-Mtime` as floating point since the epoch is accurate to 1 ns.

makes it sound like the 1ns accuracy is the primary reason for using a floating point, which I think is not the case.

In the original:

> The modified time is stored as metadata on the object as `X-Amz-Meta-Mtime` as floating point since the epoch accurate to 1 ns.

the "accurate to 1 ns" is just part of the description of how the values are interpreteted. The main point is that the value is a number of nanoseconds since the epoch.

That is my opinion anyway. I do agree the original sentence is a bit hard to read, with the three "as" etc, so I appreciate you trying to improve it!

**Comment by gregsadetsky** [comment]
Hey, you're right of course, I re-re-read and I'm seeing now what I wasn't seeing before.

Would it better if the sentence became:

> The modified time is stored as metadata on the object as X-Amz-Meta-Mtime as floating point since the epoch, accurate to 1 ns.

i.e. adding a comma before the word "accurate"?

**Comment by albertony** [comment]
> i.e. adding a comma before the word "accurate"?

Yes, I think that is good.

**Comment by albertony** [comment]
Looks good to me.
If you are happy with the results, then I think we can just merge it?
Thank you 👍

**Comment by gregsadetsky** [comment]
That's great, please go ahead! Thank you!

**Pull request merged**
