### PR TITLE
Gocritic lint basic

### PR DESCRIPTION
**Pull request by albertony**
#### What is the purpose of this change?

Enabling gocritic linting via golangci-lint. Basic features from https://github.com/rclone/rclone/pull/7884, see that for more background.

#### Checklist

- [X] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [X] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [X] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by Skylion007** [comment]
I opened a PR awhile ago I haven't had a chance to revisit about enabling more smart linter checks via codeql. Would be good to try to enable that. I never bothered to finish it though because I needed write access to add suppression to the current the open github issues  and setting up the supresssions manually was a pain.

**Review by ncw — APPROVED** [review]
I've been through all of those - they look great :-)

I'll merge them now and we can proceed with the next part without worrying about the bitrot.

**Comment by ncw** [comment]
@Skylion007 you mean https://github.com/rclone/rclone/pull/6555 ? What do you think @albertony is this something we should be using?

**Comment by albertony** [comment]
> What do you think @albertony is this something we should be using?

Answered in that PR.

**Pull request merged**
