### PR TITLE
go.mod: update storj.io/uplink to latest release

### PR DESCRIPTION
**Pull request by jtolio**
#### What is the purpose of this change?

This change updates the storj.io/uplink dependency to the latest release, which has significant performance and stability improvements.

#### Was the change discussed in an issue or in the forum before?

No

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Review by ncw — APPROVED** [review]
Thank you :-)

That reminds me I haven't updated all the deps for v1.67 yet.

I'll merge after CI goes green.

**Comment by jtolio** [comment]
Are the race checks flaky? Or did a dependency bump cause this failure?

**Comment by albertony** [comment]
> Are the race checks flaky? Or did a dependency bump cause this failure?

I triggered a re-run and then its all green, so I guess that answers your question. :)

**Comment by ncw** [comment]
> Are the race checks flaky? 

Not very, but sometimes!

> Or did a dependency bump cause this failure?

Let's hope not, but if the race tests got flakier then we'll have to deal with them.

Thank you

**Pull request merged**
