### PR TITLE
config: allow reading from FIFO

### LINKED ISSUE #5744: Can no longer pass config files in via FIFO
#### The associated forum post URL from `https://forum.rclone.org`

User `zoltan` created the following thread: https://forum.rclone.org/t/config-not-read-from-fifo-anymore/24415/13

I independently discovered this issue while trying to pass a SOPS-encrypted config file into rclone via FIFO.

#### What is the problem you are having with rclone?

Unable to pass a config file in via FIFO.

#### What is your rclone version (output from `rclone version`)

v1.57.0

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Debian Linux 10 / 4.19.0-16-amd64

#### Which cloud storage system are you using? (e.g. Google Drive)

Google Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

`sops exec-file $HOME/.config/rclone/rclone.conf "rclone --progress --config={} sync $src $dst"`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
Failed to load config file "/tmp/.sops241040067/tmp-file": seek /tmp/.sops241040067/tmp-file: illegal seek
exit status 1
```

I have cloned the repo, diffed to the noted SHA in the forum post, and am working on fixing this. I will write a test as well, and submit a PR when complete.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

### PR DESCRIPTION
**Pull request by stephanGarland**
#### What is the purpose of this change?

To fix [Issue #5744](https://github.com/rclone/rclone/issues/5744), which prevents rclone from reading in from named pipes.

#### Was the change discussed in an issue or in the forum before?

https://forum.rclone.org/t/config-not-read-from-fifo-anymore/24415/13

Fixes #5744

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
-    ^ See comment for test.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ ] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by stephanGarland** [comment]
Erroneously opened; haven't written tests yet

**Comment by ivandeex** [comment]
Feel free to stack commits and polish

**Comment by ivandeex** [comment]
Marking as draft after quick review of the general patch health

**Comment by ivandeex** [comment]
@stephanGarland Do you plan to continue your work?

**Comment by stephanGarland** [comment]
> @stephanGarland Do you plan to continue your work?

Sorry, but probably not. The program works, but the tests don't. If I figure it out in the future I'll submit a PR again, but there's no point in keeping this open for now.

**Comment by ivandeex** [comment]
C'est la sad vie

**Pull request closed without merging**
