### PR TITLE
Add a delete size threshold to sync (--max-delete-size)

### PR DESCRIPTION
**Pull request by lsacchet**
#### Checklist

- [X] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [X] I have added documentation for the changes if appropriate.
- [ ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [X] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Review by ncw — COMMENTED** [review]
Very nice code - thank you :-)

Can you write a test in `fs/operations/operations_test.go` please?

https://github.com/rclone/rclone/blob/master/fs/operations/operations_test.go

I was going to suggest you copy the test for MaxDelete but there isn't one :-( So if you are feeling kind you could write one for that too!

Make a test somewhat like this one

https://github.com/rclone/rclone/blob/72227a01519f4cc9b0a1ecd390785c9d1d09d5d0/fs/operations/operations_test.go#L413

with objects of various sizes, and make sure the objects you think should be deleted are deleted only.

Also check the response is a fatal error.

**Comment by lsacchet** [comment]
Nick, I made the necessary adjustments and tests.

**Review by ncw — COMMENTED** [review]
The code is looking nice now :-)

The new tests you made don't seem to pass though according to the CI?

**Comment by ncw** [comment]
I have squashed and merged this in f689db4422f05086bb1eae20d1b21a054a1d74a3 (I'd normally do this by pushing back to your branch which would make this branch appear as merged but I don't have permission). I managed to fix the occasional test failures too here e2984227bb7462126bfa7f8632c180f6f96a3016

Thank you :-)

**Pull request closed without merging**
