### PR TITLE
vfstest: retry flakey tests using fstest/retesting

### PR DESCRIPTION
**Pull request by ivandeex**
#### What is the purpose of this change?

> The mount tests lock my machine up quite regularly which is super boring and we don't run them on the CI for the same reason.

We actually run `mount`, `mount2` and `cmount` tests on the CI and they regularly but sporadically fail.

Now, we've got the commit https://github.com/rclone/rclone/commit/6a9ef27b0919fed17c3865a395afec97a6ed53d3. It disables a mount test failing on windows/386.
Now we've got the CI/CD test for this very commit. It fails for go 1.15 on **Linux**. Failing test name? `mount2`!
Now me tells ya. Yours is boring. Mee is musta. Don't mess on Mancunians. Get the ~~punch~~patch.

This patch provides a wrapper for `*testing.T` in "github.com/rclone/rclone/fstest/retesting".
Rewrite your test in 4 easy steps:
- replace `t *testing.T` with `t retesting.T`
- replace `t.Run(name,f)` with `retesting.Run(t,name,f)`
- rename core test function `TestName(t *testing.T)` into `testName(t retesting.T)`
- add wrapper under original name `func TestName(t *testing.T) { retesting.Run(t, "TestName", testName) }`

Set environment variable `export RCLONE_FLAKEY_RETRIES=999`, run `go test .`
Enjoy.

**When your tests get stable, just set RCLONE_FLAKEY_RETRIES=0 and test as usual.**

If Google wanted you to develop custom test drivers, they would make `testing.T` an interface, but they didn't.
It's a `struct` with private fields. You cannot instantiate it. You cannot wrap it. All functions in `testing` want only it.
The author of https://github.com/stretchr/testify noticed this and made all his functions accept an interface.
This PR provides the interface so it plays transparently with testify/accept and testify/require.
Unfortunately we've got to do a number of replacements `*testing.T -> retesting.T`
I can't help it. Blame Google.

#### Was the change discussed in an issue or in the forum before?

[commit 6a9ef27b comments](https://github.com/rclone/rclone/commit/6a9ef27b0919fed17c3865a395afec97a6ed53d3#commitcomment-55235890)

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ivandeex** [comment]
@ncw please take a look

**Comment by ncw** [comment]
(moving discussion from commit here)

Very interesting...

Maybe this is a better mechanism that the integration test retry logic?

t.Run(...) -> retesting.Run(t, ...)

Or maybe we should be using integration test runner in the CI tests? Since it knows how to retry stuff by parsing the output?

I think my only concern is that we now have two high level flakey test retriers with this?

**Comment by ivandeex** [comment]
> I think my only concern is that we now have two high level flakey test retriers with this?

No.
This one is a **low-level** retrier. It just counts failures, only in vfstest
Integration test is a **high-level** retrier. It can analyze logs and stuff.

I think we should deactivate this retrier in the integration test.
Add `export RCLONE_FLAKEY_RETRIES=0` in integration scripts
or `os.Setenv("RCLONE_FLAKEY_RETRIES", "0") somewhere in `test_all.go`

**Comment by ivandeex** [comment]
> Or maybe we should be using integration test runner in the CI tests? Since it knows how to retry stuff by parsing the output?

This approach will relegate ordinary average windows developers who just want to `go build .; go test ./backend/myfavorite` without installing `make`.

**Comment by ivandeex** [comment]
By the way, `TestDownloaders` has become a new annoyance recently.
It failed a minute ago:
https://github.com/rclone/rclone/pull/5550/checks?check_run_id=3394349997#step:11:243

**Comment by ivandeex** [comment]
I wonder what's a better location to inject the retries, core test in `vfs/vfstest/fs.go` or just `cmd/mount2/mount_test.go`?

**Comment by ivandeex** [comment]
> Maybe this is a better mechanism that the integration test retry logic?

Dunno. I just [chunk the shoddy](https://github.com/rclone/rclone/issues/5070#issuecomment-799545992).

**Comment by ncw** [comment]
> > The mount tests lock my machine up quite regularly which is super boring and we don't run them on the CI for the same reason.
> 
> We actually run `mount`, `mount2` and `cmount` tests on the CI and they regularly but sporadically fail.

The mount tests are disabled BTW - the github runners all have < 2 CPU

https://github.com/rclone/rclone/blob/6a9ef27b0919fed17c3865a395afec97a6ed53d3/cmd/mount/mount_test.go#L13-L15

> Now, we've got the commit [6a9ef27](https://github.com/rclone/rclone/commit/6a9ef27b0919fed17c3865a395afec97a6ed53d3). It disables a mount test failing on windows/386.

That is actually the cache backend not the VFS/mount. I decided I couldn't be bothered to chase down the rabbit hole to find the cause for a deprecated backend on a platform very few people use.

> > I think my only concern is that we now have two high level flakey test retriers with this?
> 
> I think we should deactivate this retrier in the integration test.
> Add `export RCLONE_FLAKEY_RETRIES=0` in integration scripts
> or `os.Setenv("RCLONE_FLAKEY_RETRIES", "0")` somewhere in `test_all.go`

OK.

I think it is fair enough that the integration tests which interact with 3rd party systems over the internet need retries.

I'm having trouble wrapping my head around file system tests needing retries. Shouldn't everything that uses a file system be perfectly deterministic?

However if I look at the test code, it is full of retries and sleeps and all sorts of horrible hacks, so maybe I should relax and put filesystem checks into the class of code which might need retries because file systems are not deterministic, especially not on the GitHub actions runners where there is always other stuff going on on the file system.

> > Or maybe we should be using integration test runner in the CI tests? Since it knows how to retry stuff by parsing the output?
> 
> This approach will relegate ordinary windows developers who just want to
> `go build . ; go test ./backend/mybackend` without installing `make`.

Indeed. Good point.

> I wonder what's a better location to inject the retries,
> `RunTests` in `vfs/vfstest/fs.go` or just `cmd/mount2/mount_test.go`?
> One or all?

Probably `vfs/vfstest/fs.go` going on the theory that file systems tests need retries - then all of them will need retries.

> > Maybe this is a better mechanism that the integration test retry logic?
> 
> Dunno. I just [chuck the shoddy](https://github.com/rclone/rclone/issues/5070#issuecomment-799545992).
> 
> This one is a **low-level** retrier. It just counts failures, only in `vfstest`.
> Integration test is a **high-level** retrier. It can analyze logs and stuff.

Do you think this code shouldn't retry by default, **unless** we set the env var which we can do in the CI?

**Comment by ivandeex** [comment]
> > I wonder what's a better location to inject the retries,
> > `RunTests` in `vfs/vfstest/fs.go` or just `cmd/mount2/mount_test.go`?
> 
> Probably `vfs/vfstest/fs.go` going on the theory that file systems tests need retries - then all of them will need retries.
> 
> Do you think this code shouldn't retry by default, **unless** we set the env var which we can do in the CI?
>

Let's make it flexible to decide later:
- Add public `RetryTests` wrapper for RunTests in vfstest
- Keep public `RunTests` in vfstest (both will take retesting.T consequently accept *testing.T as before)
- Make `defaultFlakyRetries=0` in retesting (no retries by default)
- Add `export RCLONE_FLAKY_RETRIES=2` in the `Run tests` workflow task

Please point where to replace `vfstest.RunTests` by `RetryTests`.

**Comment by ivandeex** [comment]
@ncw I hope you will find time for decisions on this test suite enhancement before.... xmas?

**Comment by ivandeex** [comment]
This PR is of minor importance. Closing.

**Pull request closed without merging**
