### PR TITLE
oracle-object-storage: support for bring your own encryption keys

### PR DESCRIPTION
**Pull request by msays2000**
#### What is the purpose of this change?
Bring your own encryption keys to encrypt objects in object storage
https://docs.cloud.oracle.com/Content/Object/Tasks/usingyourencryptionkeys.htm

5 new optional parameters are added to support bring your own encryption keys scenarios.
```
	SSEKMSKeyID          string               `config:"sse_kms_key_id"`
	SSECustomerAlgorithm string               `config:"sse_customer_algorithm"`
	SSECustomerKey       string               `config:"sse_customer_key"`
	SSECustomerKeyFile   string               `config:"sse_customer_key_file"`
	SSECustomerKeySha256 string               `config:"sse_customer_key_sha256"`
```
#### Checklist

- [X] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [X] I have added tests for all changes in this PR if appropriate.
- [X] I have added documentation for the changes if appropriate.
- [X] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [X] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by msays2000** [comment]
## Requirements:
When using SSE-Customer side, only one of sse_customer_key or sse_customer_key_file or sse_kms_key_id should be specified. 
### Test Cases
## Only One of:

`2023/02/17 09:42:36 Failed to create file system for "sse:sse/1.txt": oos: can't use vault sse_kms_key_id and local sse_customer_key at the same time`


## Mismatched Customer Key with Customer Key's Sha256

`2023/02/17 09:38:58 DEBUG : Using config file from "/Users/mkghosh/.config/rclone/rclone.conf"
2023/02/17 09:38:58 Failed to create file system for "sse:sse/1.txt": the computed SHA256 checksum (wuClzQArMXeKTpnwRbXGVv8Dnbf0rpVxEO6LOQAmMF4=) of the key doesn't match the config entry sse_customer_key_sha256=(wuClzQArMXeKTpnwRbXGVv8Dnbf0rpVxEO6LOQAmMF5=)
`

## Successful post with encryption keys:
`
MacBook-Pro:rclone mkghosh$ ./rclone copy  sse:sse/1.txt ~/Desktop/ --dump headers
2023/02/17 09:44:06 NOTICE: Automatically setting -vv as --dump is enabled
2023/02/17 09:44:06 DEBUG : rclone: Version "v1.62.0-beta.6736.3543a1eb1.manoj/sse" starting with parameters ["./rclone" "copy" "sse:sse/1.txt" "/Users/mkghosh/Desktop/" "--dump" "headers"]
2023/02/17 09:44:06 DEBUG : Creating backend with remote "sse:sse/1.txt"
2023/02/17 09:44:06 DEBUG : Using config file from "/Users/mkghosh/.config/rclone/rclone.conf"
2023/02/17 09:44:06 DEBUG : You have specified to dump information. Please be noted that the Accept-Encoding as shown may not be correct in the request and the response may not show Content-Encoding if the go standard libraries auto gzip encoding was in effect. In this case the body of the request will be gunzipped before showing it.
2023/02/17 09:44:06 DEBUG : 1.txt: trying to read metadata 1.txt
2023/02/17 09:44:06 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2023/02/17 09:44:06 DEBUG : HTTP REQUEST (req 0xc0008e1500)
2023/02/17 09:44:06 DEBUG : HEAD /n/manoj-prod/b/sse/o/1.txt HTTP/1.1
Host: objectstorage.us-ashburn-1.oraclecloud.com
User-Agent: rclone/v1.62.0-beta.6736.3543a1eb1.manoj/sse
Accept: */*
Authorization: XXXX
Content-Type: application/json
Date: Fri, 17 Feb 2023 17:44:06 GMT
Opc-Client-Info: Oracle-GoSDK/65.29.0
Opc-Client-Request-Id: ea5768d649dd9ee2594a1a9c02b9af54
Opc-Client-Retries: true
Opc-Sse-Customer-Algorithm: AES256
Opc-Sse-Customer-Key: ZFNnVmtZcDNzNnY5eSRCJkUpSEBNY1FlVGhXbVpxNHQ=
Opc-Sse-Customer-Key-Sha256: wuClzQArMXeKTpnwRbXGVv8Dnbf0rpVxEO6LOQAmMF4=

2023/02/17 09:44:06 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2023/02/17 09:44:07 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2023/02/17 09:44:07 DEBUG : HTTP RESPONSE (req 0xc0008e1500)
2023/02/17 09:44:07 DEBUG : HTTP/1.1 200 OK
Content-Length: 15
Accept-Ranges: bytes
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: POST,PUT,GET,HEAD,DELETE,OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: accept-ranges,access-control-allow-credentials,access-control-allow-methods,access-control-allow-origin,content-length,content-md5,content-type,date,etag,last-modified,opc-client-info,opc-client-request-id,opc-meta-mtime,opc-request-id,storage-tier,version-id,x-api-id
Content-Md5: 80YYU2o0dhdszLGnIKfMbw==
Content-Type: text/plain; charset=utf-8
Date: Fri, 17 Feb 2023 17:44:07 GMT
Etag: b664e289-38d5-4dc6-8434-04201965c2f3
Last-Modified: Fri, 17 Feb 2023 09:51:06 GMT
Opc-Client-Request-Id: ea5768d649dd9ee2594a1a9c02b9af54
Opc-Meta-Mtime: 1676491876.48414501
Opc-Request-Id: iad-1:VHjjxC1i_aiJDeZq8aFerQIL3kZ_mpIR35VApbBsUzJokp43sfk5961Evq_MbyGQ
Storage-Tier: Standard
Version-Id: b7541f88-005e-4719-9dad-81c3d41a00c6
X-Api-Id: native

2023/02/17 09:44:07 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2023/02/17 09:44:07 DEBUG : fs cache: adding new entry for parent of "sse:sse/1.txt", "sse:sse"
2023/02/17 09:44:07 DEBUG : Creating backend with remote "/Users/mkghosh/Desktop/"
2023/02/17 09:44:07 DEBUG : fs cache: renaming cache item "/Users/mkghosh/Desktop/" to be canonical "/Users/mkghosh/Desktop"
2023/02/17 09:44:07 DEBUG : 1.txt: trying to read metadata 1.txt
2023/02/17 09:44:07 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2023/02/17 09:44:07 DEBUG : HTTP REQUEST (req 0xc0000c9700)
2023/02/17 09:44:07 DEBUG : HEAD /n/manoj-prod/b/sse/o/1.txt HTTP/1.1
Host: objectstorage.us-ashburn-1.oraclecloud.com
User-Agent: rclone/v1.62.0-beta.6736.3543a1eb1.manoj/sse
Accept: */*
Authorization: XXXX
Content-Type: application/json
Date: Fri, 17 Feb 2023 17:44:07 GMT
Opc-Client-Info: Oracle-GoSDK/65.29.0
Opc-Client-Request-Id: 302d5dc64225e7062e0cd996e3b33aca
Opc-Client-Retries: true
Opc-Sse-Customer-Algorithm: AES256
Opc-Sse-Customer-Key: ZFNnVmtZcDNzNnY5eSRCJkUpSEBNY1FlVGhXbVpxNHQ=
Opc-Sse-Customer-Key-Sha256: wuClzQArMXeKTpnwRbXGVv8Dnbf0rpVxEO6LOQAmMF4=

2023/02/17 09:44:07 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2023/02/17 09:44:07 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2023/02/17 09:44:07 DEBUG : HTTP RESPONSE (req 0xc0000c9700)
2023/02/17 09:44:07 DEBUG : HTTP/1.1 200 OK
Content-Length: 15
Accept-Ranges: bytes
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: POST,PUT,GET,HEAD,DELETE,OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: accept-ranges,access-control-allow-credentials,access-control-allow-methods,access-control-allow-origin,content-length,content-md5,content-type,date,etag,last-modified,opc-client-info,opc-client-request-id,opc-meta-mtime,opc-request-id,storage-tier,version-id,x-api-id
Content-Md5: 80YYU2o0dhdszLGnIKfMbw==
Content-Type: text/plain; charset=utf-8
Date: Fri, 17 Feb 2023 17:44:07 GMT
Etag: b664e289-38d5-4dc6-8434-04201965c2f3
Last-Modified: Fri, 17 Feb 2023 09:51:06 GMT
Opc-Client-Request-Id: 302d5dc64225e7062e0cd996e3b33aca
Opc-Meta-Mtime: 1676491876.48414501
Opc-Request-Id: iad-1:skiZCZ65O6Td7jLkPkZUh48kAhgFW5uMHICEq4-2T-levXWVgp0LtPLnZyPfgaXd
Storage-Tier: Standard
Version-Id: b7541f88-005e-4719-9dad-81c3d41a00c6
X-Api-Id: native

2023/02/17 09:44:07 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2023/02/17 09:44:07 DEBUG : 1.txt: Need to transfer - File not found at Destination
2023/02/17 09:44:07 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2023/02/17 09:44:07 DEBUG : HTTP REQUEST (req 0xc0003ca300)
2023/02/17 09:44:07 DEBUG : GET /n/manoj-prod/b/sse/o/1.txt HTTP/1.1
Host: objectstorage.us-ashburn-1.oraclecloud.com
User-Agent: rclone/v1.62.0-beta.6736.3543a1eb1.manoj/sse
Accept: */*
Authorization: XXXX
Content-Type: application/json
Date: Fri, 17 Feb 2023 17:44:07 GMT
Opc-Client-Info: Oracle-GoSDK/65.29.0
Opc-Client-Request-Id: 632aae573630349469a747d55b75fdb2
Opc-Client-Retries: true
Opc-Sse-Customer-Algorithm: AES256
Opc-Sse-Customer-Key: ZFNnVmtZcDNzNnY5eSRCJkUpSEBNY1FlVGhXbVpxNHQ=
Opc-Sse-Customer-Key-Sha256: wuClzQArMXeKTpnwRbXGVv8Dnbf0rpVxEO6LOQAmMF4=
Accept-Encoding: gzip

2023/02/17 09:44:07 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2023/02/17 09:44:07 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2023/02/17 09:44:07 DEBUG : HTTP RESPONSE (req 0xc0003ca300)
2023/02/17 09:44:07 DEBUG : HTTP/1.1 200 OK
Content-Length: 15
Accept-Ranges: bytes
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: POST,PUT,GET,HEAD,DELETE,OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: accept-ranges,access-control-allow-credentials,access-control-allow-methods,access-control-allow-origin,content-length,content-md5,content-type,date,etag,last-modified,opc-client-info,opc-client-request-id,opc-meta-mtime,opc-request-id,storage-tier,version-id,x-api-id
Content-Md5: 80YYU2o0dhdszLGnIKfMbw==
Content-Type: text/plain; charset=utf-8
Date: Fri, 17 Feb 2023 17:44:07 GMT
Etag: b664e289-38d5-4dc6-8434-04201965c2f3
Last-Modified: Fri, 17 Feb 2023 09:51:06 GMT
Opc-Client-Request-Id: 632aae573630349469a747d55b75fdb2
Opc-Meta-Mtime: 1676491876.48414501
Opc-Request-Id: iad-1:OnQ18GJvMmoxOzNzju0aaKWWxfgJ8bBmNKZg5mn61D4y3Wwbnmic2aoehgMjTnNw
Storage-Tier: Standard
Version-Id: b7541f88-005e-4719-9dad-81c3d41a00c6
X-Api-Id: native

2023/02/17 09:44:07 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2023/02/17 09:44:07 DEBUG : 1.txt: trying to read metadata 1.txt
2023/02/17 09:44:07 DEBUG : 1.txt: md5 = f34618536a3476176cccb1a720a7cc6f OK
2023/02/17 09:44:07 INFO  : 1.txt: Copied (new)
2023/02/17 09:44:07 INFO  : 
Transferred:             15 B / 15 B, 100%, 0 B/s, ETA -
Transferred:            1 / 1, 100%
Elapsed time:         1.0s

2023/02/17 09:44:07 DEBUG : 7 go routines active
MacBook-Pro:rclone mkghosh$ 

`

**Comment by msays2000** [comment]
@ncw @albertony any suggestion how to fix the lint error in unrelated code.

**Comment by msays2000** [comment]
looks like I can upgrade this package to get the vulnerability resolved. 
  Module: golang.org/x/net
    Found in: golang.org/x/net@v0.5.0
    Fixed in: golang.org/x/net@v0.7.0

**Comment by msays2000** [comment]
@ncw @albertony vulnerabilities fixed.

**Comment by albertony** [comment]
> @ncw @albertony vulnerabilities fixed.

Great. You should probably make that a separate commit, though.

**Comment by msays2000** [comment]
> > @ncw @albertony vulnerabilities fixed.
> 
> Great. You should probably make that a separate commit, though.

sure: its here https://github.com/rclone/rclone/pull/6777

**Review by ncw — APPROVED** [review]
This looks great - thank you.

It looks like it will merge cleanly too, so I'll do that now :-)

**Pull request merged**
