### PR TITLE
cmd/version: add support for openbsd/amd64

### PR DESCRIPTION
**Pull request by ivandeex**
#### What is the purpose of this change?

#5204 added the `rclone version` command based on the [gopsutil](https://github.com/shirou/gopsutil) project, but we excluded it from the OpenBSD build due to build failures.

The root of the problem appeared to lie in the [CGO dependency left in process_openbsd.go](https://github.com/shirou/gopsutil/blob/v3.21.5/v3/process/process_openbsd.go#L83).

I noticed that https://github.com/shirou/gopsutil/pull/965 claiming to fix the CGO issue is stalled since October 2020. I [improved its patch](https://github.com/shirou/gopsutil/pull/1087/files) so it applies successfully to the current gopsutil master on gopsutil/process and on `gopsutil/v3`.
I then built rclone with patched gopsutil and successfully ran `rclone version` on OpenBSD 6.7 x86_64 ([Virtualbox](https://app.vagrantup.com/fnichol/boxes/openbsd-6.7)):

```
rclone v1.56.0-DEV
- os/version: openbsd 6.7 (64 bit)
- os/kernel: 6.7 (amd64)
- os/type: openbsd
- os/arch: amd64
- go/version: go1.16.4
- go/linking: static
- go/tags: none
```

I submitted the changes as upstream PR https://github.com/shirou/gopsutil/pull/1087 which is currently awaiting approval by @shirou.

#### Was the change discussed in an issue or in the forum before?

Explained here https://github.com/rclone/rclone/pull/5204#discussion_r606765569

Waiting for https://github.com/shirou/gopsutil/pull/1087 merged or for https://github.com/shirou/gopsutil/pull/965 extended to gopsutil/v3 and merged.

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ ] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ivandeex** [comment]
Still got `openbsd/i386` build error due to [tklauser/go-sysconf sysconf_openbsd.go:22](https://github.com/tklauser/go-sysconf/blob/master/sysconf_openbsd.go#L20) ([docs](https://pkg.go.dev/golang.org/x/sys/unix#pkg-constants)):
```
Error: .../go/pkg/mod/github.com/tklauser/go-sysconf@v0.3.5/sysconf_openbsd.go:22:28: undefined: unix.RLIMIT_NPROC
```

**Comment by ivandeex** [comment]
Merged https://github.com/shirou/gopsutil/pull/1087 fixed build on `openbsd/amd64`.

Now waiting for https://github.com/tklauser/go-sysconf/issues/21 to let build on `openbsd/i386`.

**Comment by ivandeex** [comment]
Having merged https://github.com/shirou/gopsutil/pull/1087 fixed build on `openbsd/amd64`.

Now waiting for https://github.com/tklauser/go-sysconf/issues/21 to let build on `openbsd/i386`.

**Comment by ivandeex** [comment]
The _go-sysconf_ issue now depends in turn on request https://golang.org/cl/341069 which will be merged in go1.17 at its earliest.
Maybe it will be backported to 1.16.8. At any rate there's no chance to see it in go 1.14, 1.15 or 1.16.6 currently required to build rclone in CI/CD.

Given that, this pull request will add compiler pragmas to skip the failing dependency on `openbsd/i386` and a comment advising to drop the quirk as soon as rclone no more depends on go 1.14-1.16.
Building on `openbsd/amd64` will be restored immediately.

**Comment by ivandeex** [comment]
## Manual unit test

### version output on OpenBSD 6

1. Run Vagrant box https://app.vagrantup.com/fnichol/boxes/openbsd-6.7 in VirtualBox and configure ssh port forwarding
2. Build rclone for `openbsd/amd64` and `openbsd/386` on Linux and upload to vagrantified OpenBSD 6.7
```
GOOS=openbsd GOARCH=amd64 go build -o rclone.bsd64 -v .
scp rclone.bsd64 bsd:
GOOS=openbsd GOARCH=386 go build -o rclone.bsd32 -v .
scp rclone.bsd32 bsd:
```
3. Run the test
```
$ ssh bsd

openbsd-67$ uname -a
OpenBSD openbsd-67.flam.nichol.ca 6.7 GENERIC.MP#5 amd64

openbsd-67$ ./rclone.bsd64 version
rclone v1.57.0-DEV
- os/version: openbsd 6.7 (64 bit)
- os/kernel: 6.7 (amd64)
- os/type: openbsd
- os/arch: amd64
- go/version: go1.16.7
- go/linking: static
- go/tags: none

openbsd-67$ ./rclone.bsd32 version
./rclone.bsd32[1]: ELF
                      @: not found
./rclone.bsd32[2]: syntax error: `(' unexpected

openbsd-67$ exit
```

### version output on github runners

https://github.com/ivandeex/rclone/runs/3334374437?check_suite_focus=true

Linux
```
rclone v1.57.0-beta.5630.c055e3794.ci-version-openbsd
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 5.8.0-1039-azure (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.16.7
- go/linking: dynamic
- go/tags: cmount
```

Windows/x86_64
```
rclone v1.57.0-beta.5630.c055e3794.ci-version-openbsd
- os/version: Microsoft Windows Server 2019 Datacenter 1809 (64 bit)
- os/kernel: 10.0.17763.2061 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.16.7
- go/linking: dynamic
- go/tags: cmount
```

Windows/386
```
rclone v1.57.0-beta.5630.c055e3794.ci-version-openbsd
- os/version: Microsoft Windows Server 2019 Datacenter 1809 (64 bit)
- os/kernel: 10.0.17763.2061 (x86_64)
- os/type: windows
- os/arch: 386
- go/version: go1.16.7
- go/linking: dynamic
- go/tags: cmount
```

macOS/x86_64
```
rclone v1.57.0-beta.5630.c055e3794.ci-version-openbsd
- os/version: darwin 10.15.7 (64 bit)
- os/kernel: 19.6.0 (x86_64)
- os/type: darwin
- os/arch: amd64
- go/version: go1.16.7
- go/linking: dynamic
- go/tags: cmount
```

macOS/arm64 (actually runner is `macOS/x86_64`! see [build.yml](https://github.com/rclone/rclone/blob/v1.56.0/.github/workflows/build.yml#L52))
```
rclone v1.57.0-beta.5630.c055e3794.ci-version-openbsd
- os/version: darwin 10.15.7 (64 bit)
- os/kernel: 19.6.0 (x86_64)
- os/type: darwin
- os/arch: amd64
- go/version: go1.16.7
- go/linking: dynamic
- go/tags: cmount
```

### Compile all architectures - PASSED
https://github.com/ivandeex/rclone/runs/3334374552?check_suite_focus=true#step:15:1

**Comment by ivandeex** [comment]
@ncw Please review

**Review by ncw — APPROVED** [review]
Looks great :+1:

**Pull request merged**
