### PR TITLE
drive: Added flag to stop when the download limit is exceeded

### PR DESCRIPTION
**Pull request by darthShadow**
Signed-off-by: Anagh Kumar Baranwal <6824881+darthShadow@users.noreply.github.com>

#### What is the purpose of this change?

Added flag to stop transfers when the download limit is exceeded

#### Was the change discussed in an issue or in the forum before?

N/A

#### Checklist

- [X] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [X] I have added tests for all changes in this PR if appropriate.
- [X] I have added documentation for the changes if appropriate.
- [X] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [X] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by darthShadow** [comment]
@ncw I hope you don't mind the additional `hacktoberfest-accepted` label here.

**Comment by ncw** [comment]
This looks great - thank you!

Could you just edit the commit message to put the name of the flag in the first line? This helps users when I build the changelog (which is just the first lines of each commit message)

Thanks.

**Comment by darthShadow** [comment]
Done.

**Comment by ncw** [comment]
Did you push it? I don't see the change?

**Comment by darthShadow** [comment]
It's showing for me properly on this PR. This is the new commit message:

drive: Added flag `--drive-stop-on-download-limit` to stop transfers when the download limit is exceeded

Did you mean something else?

**Comment by ncw** [comment]
It looks fine now. Maybe I looked at the cached version or something :-(

I'll merge it now - thank you very much :-)

**Pull request merged**
