### PR TITLE
Performance improvements for Proton Drive backend

### PR DESCRIPTION
**Pull request by lawmurray**
#### What is the purpose of this change?

The change improves performance of the Proton Drive backend by removing some redundant calls to the Proton Drive API. It may help with the performance issues reported in #7322 and #7413.

I'm particularly interested in using Proton Drive with `bisync`. For my particular use case (~500 files in ~50 directories weighing in at 600 MB), the change reduces `bisync` runtime from ~45 to ~7 minutes with `--resync`, and from ~30 mins to ~2 minutes without `--resync`.

The change is just based on the observation that links to files obtained via the Proton Drive API are sometimes retrieved twice. The function `List()` does a directory listing and gets a link to each child file, then constructs a path from each link, then `getObjectLink()` is called to get a link again from each path. The change removes that unnecessary call, preserving the original link when it is available. In doing so it also tidies up a bit of related code that had functions with unused (or often `nil`) arguments.

A couple of tests are failing when I run `go test -v` in the `backend/protondrive` directory, with a test account that I set up on Proton Drive. The current head also appears to fail the same tests, however, so I don't think these failures are related to the changes.

#### Was the change discussed in an issue or in the forum before?

No

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate. *(None to add.)*
- [x] I have added documentation for the changes if appropriate. *(Inline comments where appropriate.)*
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

Thanks to all the developers for their work on rclone, especially @henrybear327 for this Proton Drive backend! I hope this contribution is useful.

### CODE REVIEW

**Comment by henrybear327** [comment]
Hey @lawmurray,

Thanks for the neat observation and PR!

> A couple of tests are failing when I run go test -v in the backend/protondrive directory, with a test account that I set up on Proton Drive. The current head also appears to fail the same tests, however, so I don't think these failures are related to the changes.

I will test it on my account and see if it's related to the ProtonDrive's newly introduced ProtonDocs links :) 

Have a nice day!

**Review by ncw — APPROVED** [review]
This looks like a nice efficiency fix.

I'm happy to merge if you are @henrybear327 

Note that currently the backend integration tests are passing for protondrive. The bisync tests are not - not sure if that is what you meant by failing tests @lawmurray ?

**Comment by lawmurray** [comment]
Thanks @henrybear327 and @ncw, glad this looks useful. I'm toying with another idea too to improve performance in specific circumstances. If you're happy to merge this I'll get on with that.

On the tests, I'm just running `go test -v` from within the `backend/protondrive` directory, as suggested in the contributor guide (after setting up a `TestProtonDrive` remote, a separate Proton account that I set up for the purpose). I get the [attached](https://github.com/user-attachments/files/16944847/test.log), i.e. a few errors in the mix, but perhaps they are expected:

**Comment by ncw** [comment]
> Thanks @henrybear327 and @ncw, glad this looks useful. I'm toying with another idea too to improve performance in specific circumstances. If you're happy to merge this I'll get on with that.
> 
> On the tests, I'm just running `go test -v` from within the `backend/protondrive` directory, as suggested in the contributor guide (after setting up a `TestProtonDrive` remote, a separate Proton account that I set up for the purpose). I get the [attached](https://github.com/user-attachments/files/16944847/test.log), i.e. a few errors in the mix, but perhaps they are expected:

There is one integration test failing `TestIntegration/FsMkdir/FsPutFiles`

This is the error message

```
=== RUN   TestIntegration/FsMkdir/FsPutFiles
2024/09/10 19:32:40.145777 WARN RESTY 422 POST https://mail.proton.me/api/drive/shares/SLMhzxxK9KGno4-97MqPpQydGxDO8Bg5SHAblMF6j2B39nIGYyarh3e0kI3dvDDFhrOqRh-LyFqzS0B_YZMNAA==/files: A file or folder with that name already exists (Code=2500, Status=422), Attempt 1
2024/09/10 19:32:40.145837 ERROR RESTY 422 POST https://mail.proton.me/api/drive/shares/SLMhzxxK9KGno4-97MqPpQydGxDO8Bg5SHAblMF6j2B39nIGYyarh3e0kI3dvDDFhrOqRh-LyFqzS0B_YZMNAA==/files: A file or folder with that name already exists (Code=2500, Status=422)
    fstests.go:145: 
        	Error Trace:	/home/lawrence/Code/rclone/fstest/fstests/fstests.go:145
        	            				/home/lawrence/Code/rclone/fstest/fstests/fstests.go:161
        	            				/home/lawrence/Code/rclone/fstest/fstests/fstests.go:223
        	            				/home/lawrence/Code/rclone/fstest/fstests/fstests.go:213
        	            				/home/lawrence/Code/rclone/fstest/fstests/fstests.go:958
        	Error:      	Received unexpected error:
        	            	a draft exist - usually this means a file is being uploaded at another client, or, there was a failed upload attempt. Can use --protondrive-replace-existing-draft=true to temporarily override the existing draft
        	Test:       	TestIntegration/FsMkdir/FsPutFiles
        	Messages:   	Put
```

This test is also failing [in the integration tests](https://pub.rclone.org/integration-tests/current/protondrive-backend.protondrive-TestProtonDrive-1.txt)  but it [passed when retried](https://pub.rclone.org/integration-tests/current/protondrive-backend.protondrive-TestProtonDrive-2.txt) so this isn't a regression.

As far as I'm concerned this looks good to me.

@henrybear327 are you OK with these changes?

**Comment by lawmurray** [comment]
I have some additional changes now that, for my `bisync` use case above, reduce the initial `--resync` time to 5 minutes and subsequent calls to 12 seconds. They do not require any changes to rclone itself, but rather to your `Proton-API-Bridge` and `go-proton-api` repos @henrybear327, so heads up that I'll send some more pull requests your way, and I'll link them in here for tracking.

What I discovered is that with the Proton API, the JSON response to a directory listing request (`ListChildren()`) includes an `XAttr` for each link, but the `Link` struct into which it is unmarshalled (in `go-proton-api`) does not include such a field, and so it's dropped. But that `XAttr` is the same as that of the active revision, and so can be used to obtain the size and modification time of the original (plaintext, not encrypted) file, without further Proton API requests for the revisions of the file.

It makes for a big performance gain: only one API call per directory, plus one API call per file that needs to be updated (rather than one API call per file regardless of whether it needs to be updated or not).

**Comment by lawmurray** [comment]
To be clear, this pull request does not depend on the new ones in these other repositories, nor do they depend on it, but as there's no new pull request required for rclone I thought I'd keep them together here as related changes.

**Comment by ncw** [comment]
I think these changes look correct so I am going to merge them now - thank you @lawmurray

**Comment by Fr00t** [comment]
Hey guys, I can see this has been merged - but I cant find it in the changelogs of recent releases, has it yet to be published? The Unraid Plugin I'm using is running version 1.68.1 still, but I wanted to make sure I'm running this commit because I'm having performance issues with ProtonDrive-syncing :)

**Comment by lawmurray** [comment]
@Fr00t This one has been merged and @ncw added it to the [1.69](https://github.com/rclone/rclone/milestone/57) milestone. While I'm not familiar with the rclone release process, I presume that means it will be available in the next release.

The second round of changes that I mentioned above, and that offer a bigger performance improvement yet, require action from @henrybear327. The state of those is:

- [x] henrybear327/Proton-API-Bridge#28 (merged)
- [ ] henrybear327/go-proton-api#4 (awaiting review---although it's trivial actually, should be easy)

I think @henrybear327 will then have to create a release on each of those separate repositories for rclone to use the updated versions.

@henrybear327 also mentioned in henrybear327/go-proton-api#4 that he's working on merging these repos into the rclone repo. I think that's wise, as he's done some great work there and consolidating under the rclone repo would make contributions and review much easier, as well as reduce external dependencies. That's not a prerequisite for these performance improvements, however, so I presume they can get to users sooner.

**Comment by Fr00t** [comment]
@lawmurray - Thanks for such a great response, and thanks to everyone involved for maintaining and contributing to the code base :)

I'll look out for new versions when they drop

**Comment by ncw** [comment]
@Fr00t , @lawmurray is correct this change will be in 1.69. You can try it now in [the latest beta](https://beta.rclone.org/)
 though.

**Pull request merged**
