### PR TITLE
New backend: Estuary

### PR DESCRIPTION
**Pull request by anjor**
#### What is the purpose of this change?

Implementing a new backend estuary.
Supersedes https://github.com/rclone/rclone/pull/6638.

#### Was the change discussed in an issue or in the forum before?

https://github.com/rclone/rclone/issues/5854
#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ncw** [comment]
Le me know if you have a problem fixing the lint problems.

It is quite a good idea to install a local copy of golangci-lint (you can run this with `make check`)

**Comment by anjor** [comment]
I ended up doing just that. They are fixed now I think.

**Comment by anjor** [comment]
@ncw hope you had a good Christmas and a new year. I was wondering if we could pick this up again?

Not sure why the arm64 build is failing -- do you have any ideas?

**Comment by ncw** [comment]
> @ncw hope you had a good Christmas and a new year. I was wondering if we could pick this up again?

Sure thing!

> Not sure why the arm64 build is failing -- do you have any ideas?

I think it was just one of those things - I've just retried the build.

What is the status of this re the integration tests? Does `test_all -backends estuary` run clean now?

I forgot what we said about an integration test account - is that something I can make or you can make for me?

**Comment by anjor** [comment]
Not quite.

`FsPutFiles` fails as discussed earlier:
```
=== RUN   TestIntegration/FsMkdir/FsPutFiles
    fstests.go:152:
        	Error Trace:	/Users/anjor/repos/application-research/rclone/backend/estuary/fstests.go:152
        	            				/Users/anjor/repos/application-research/rclone/backend/estuary/fstests.go:168
        	            				/Users/anjor/repos/application-research/rclone/backend/estuary/fstests.go:221
        	            				/Users/anjor/repos/application-research/rclone/backend/estuary/fstests.go:873
        	Error:      	Received unexpected error:
        	            	HTTP error 500 (500 Internal Server Error) returned body: "{\"error\":{\"code\":500,\"reason\":\"Internal Server Error\",\"details\":\"UNIQUE constraint failed: collection_refs.path, collection_refs.collection\"}}\n"
        	Test:       	TestIntegration/FsMkdir/FsPutFiles
        	Messages:   	Put
```


I hadn't tried running `test_all` before, I was just running `TestIntegration`. Looks like something in the operations tests is failing too:

```
2023/01/03 13:13:21 "./operations.test -test.v -test.timeout 1h0m0s -remote TestEstuary: -fast-list" - Finished ERROR in 19m51.229995708s (try 1/5): exit status 1: Failed [TestMultithreadCopy/{size:131071_streams:2} TestMultithreadCopy/{size:131072_streams:2} TestCheck/3 TestCheck/4 TestCheck/5 TestCheck/6 TestCheck/7 TestCheckDownload/1 TestCheckDownload/2 TestCheckSizeOnly TestParseSumFile TestCheckSum TestCheckSumDownload TestListDirSorted TestListJSON/Default TestListJSON/FilesOnly TestListJSON/DirsOnly TestListJSON/Recurse TestListJSON/NoModTime TestListJSON/NoMimeType TestListJSON/ShowHash TestListJSON/HashTypes TestListJSON/Metadata TestStatJSON TestMkdir TestLsd TestLs TestLsWithFilesFrom TestLsLong TestHashSums TestCount TestDelete TestCat TestRmdirsNoLeaveRoot TestRmdirsLeaveRoot TestRmdirsWithFilter TestCopyURL TestMoveFile TestMoveFileWithIgnoreExisting TestCaseInsensitiveMoveFile TestCopyFileCompareDest TestDirMove TestGetFsInfo TestRcat/withChecksum=false,ignoreChecksum=false TestRcat/withChecksum=true,ignoreChecksum=false TestRcat/withChecksum=false,ignoreChecksum=true TestRcat/withChecksum=true,ignoreChecksum=true TestRcatMetadata TestRcatSize TestRcatSizeMetadata TestCopyFileMaxTransfer TestTouchDir]
```


Re integration test account -- I set one up for you on https://estuary.tech and emailed you an invitation code. Let me know if you need me to resend it.

However, to be honest, I am actually thinking of changing the default from using the hosted version of estuary (https://estuary.tech) to a locally running estuary as outlined here -- https://docs.estuary.tech/tutorial-managing-files-with-rclone .

Would you be able to run the integration tests locally? Or would you need a remote server?

**Comment by ncw** [comment]
> Not quite.
> 
> `FsPutFiles` fails as discussed earlier:

If this test is failing, then it is skipping all the tests (lots!) which depend on it.

> I hadn't tried running `test_all` before, I was just running `TestIntegration`. Looks like something in the operations tests is failing too:

Looks like that will need fixing up. Get the basic backend integration tests working first.

> Re integration test account -- I set one up for you on https://estuary.tech and emailed you an invitation code. Let me know if you need me to resend it.

I've got it thanks, I just forgot (too much going on!).
 
> However, to be honest, I am actually thinking of changing the default from using the hosted version of estuary (https://estuary.tech) to a locally running estuary as outlined here -- https://docs.estuary.tech/tutorial-managing-files-with-rclone .
> 
> Would you be able to run the integration tests locally? Or would you need a remote server?

If you want to run the integration tests locally, then they need to be set up in a docker image, or with docker compose.

See `fstest/testserver/init.d/` for examples of this. Most are single docker images, but some (eg Seafile) are docker compose.

Rclone will start the server run the tests and shut it down automatically as part of the tests.

**Comment by ncw** [comment]
How are you doing with this? Any further progress on the tests?

**Comment by anjor** [comment]
We are making progress but still working on it. @LucRoy is involved in the effort as well now. I will let you know when we have a meaningful update.

**Pull request closed without merging**
