### PR TITLE
Add Outscale S3 Provider

### PR DESCRIPTION
**Pull request by outscale-mgo**
#### What is the purpose of this change?

This PR add [Outscale](https://fr.outscale.com/solutions-stockage-cloud/oos/) S3 provider, so we can use rclone with Outscale OOS API directly. 

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

Note that it's my first time contributing to this project, and I think that everything is correct in the checklist, but I might have miss some tasks. If so I'll try to fixe them asap.

### CODE REVIEW

**Review by ncw — COMMENTED** [review]
Code looks great - thank you :-)

Did you run the integration tests to check the quirks are correct?

> Once you've written the code, test rclone config works to your satisfaction, and check the integration tests work `go test -v -remote NewS3Provider:`. You may need to adjust the quirks to get them to pass. Some providers just can't pass the tests with control characters in the names so if these fail and the provider doesn't support urlEncodeListings in the quirks then ignore them. Note that the SetTier test may also fail on non AWS providers.

If the integration tests are passing then I'll merge, but if you haven't run them, please do so and fix up any problems - do ask for help if you get stuck.

Thanks

**Comment by outscale-mgo** [comment]
Hello, thanks for the review,
When I call 
```sh
go test -v -remote NewS3Provider:
```
I got 
```
?   	github.com/rclone/rclone	[no test files]
```
So I guess I did miss config something, maybe you know what I could have miss ?

Thanks.

**Comment by ncw** [comment]
@outscale-mgo you need to `cd backend/s3` first then run `go test -v -remote NewS3Provider:`

**Comment by outscale-mgo** [comment]
```bash
matthias.gatto % go test -v -remote NewS3Provider:
=== RUN   TestVersionLess
--- PASS: TestVersionLess (0.00s)
=== RUN   TestMergeDeleteMarkers
--- PASS: TestMergeDeleteMarkers (0.00s)
=== RUN   TestIntegration
    fstests.go:442: Using remote "NewS3Provider:"
    fstests.go:463: Didn't find "NewS3Provider:" in config file - skipping tests
--- PASS: TestIntegration (0.00s)
=== RUN   TestIntegration2
    s3_test.go:38: skipping as -remote is set
--- SKIP: TestIntegration2 (0.00s)
=== RUN   TestAWSDualStackOption
--- PASS: TestAWSDualStackOption (0.00s)
PASS
ok  	github.com/rclone/rclone/backend/s3	0.463s
(.venv) matthias.gatto@LMAC-0E5Q6LR-EU s3 % go test -v -remote NewS3Provider:
```

**Comment by ncw** [comment]
> ```shell
> === RUN   TestIntegration
>     fstests.go:442: Using remote "NewS3Provider:"
>     fstests.go:463: Didn't find "NewS3Provider:" in config file - skipping tests
> ```

You need to make a remote for the new provider and use it here `-remote NewS3Provider:` - I expect you've made one for testing already - use that!

**Comment by outscale-mgo** [comment]
Ok, so I got a few errors.
Some errors with characters encodings, but it seems it happen to a lot of providers, and `urlEncodeListings` doesn't seem to change anything.

With `useMultipartUploads` I got this error:
```
=== RUN   TestIntegration/FsMkdir/FsOpenChunkWriter
2024/09/26 14:35:21 ERROR : writer-at-subdir/writer-at-file: Don't know how to set key "chunkSize" on upload
2024/09/26 14:35:21 NOTICE: S3 bucket rclone-test-dubiyim5moxu: Streaming uploads using chunk size 5Mi will have maximum file size of 48.828Gi
```
If I remove the option, I got this error:
```
    fstests.go:2285: 
        	Error Trace:	/Users/matthias.gatto/rclone/fstest/fstests/fstests.go:2285
        	            				/Users/matthias.gatto/rclone/fstest/fstests/fstests.go:2336
        	Error:      	Received unexpected error:
        	            	8Ei is greater than 5Gi
        	Test:       	TestIntegration/FsMkdir/FsPutChunked
```
I've tried to do this: 
```go
               // 5 Gi seems to be max chunk size                                                                                                                                                          
                if opt.ChunkSize > 4*fs.Gibi {
                        opt.ChunkSize = 4*fs.Gibi
                }
```
But it doesn't seem to change anything. 


And I got this error: (but maybe this one is a miss config on my system local ?)
```
    s3_internal_test.go:93: 
        	Error Trace:	/Users/matthias.gatto/rclone/backend/s3/s3_internal_test.go:93
        	Error:      	Not equal: 
        	            	expected: "en-US"
        	            	actual  : ""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-en-US
        	            	+
        	Test:       	TestIntegration/FsMkdir/FsPutFiles/Internal/Metadata
        	Messages:   	content-language
```

Any ideas which options might help to pass the tests ?

Thanks a lot.

**Comment by ncw** [comment]
> Ok, so I got a few errors.
> Some errors with characters encodings, but it seems it happen to a lot of providers, and `urlEncodeListings` doesn't seem to change anything.

AWS can store anything it its keys but other providers often limit which are available. Which tests failed?

> With `useMultipartUploads` I got this error:
> 
> ```
> === RUN   TestIntegration/FsMkdir/FsOpenChunkWriter
> 2024/09/26 14:35:21 ERROR : writer-at-subdir/writer-at-file: Don't know how to set key "chunkSize" on upload
> 2024/09/26 14:35:21 NOTICE: S3 bucket rclone-test-dubiyim5moxu: Streaming uploads using chunk size 5Mi will have maximum file size of 48.828Gi
> ```

I don't understand this error! This seems to be trying to set some metadata called `chunkSize` which doesn't exist.

Can you do `rclone config redacted` and show your config please?

> And I got this error: (but maybe this one is a miss config on my system local ?)
> 
> ```
>     s3_internal_test.go:93: 
>         	Error Trace:	/Users/matthias.gatto/rclone/backend/s3/s3_internal_test.go:93
>         	Error:      	Not equal: 
>         	            	expected: "en-US"
>         	            	actual  : ""
>         	            	
>         	            	Diff:
>         	            	--- Expected
>         	            	+++ Actual
>         	            	@@ -1 +1 @@
>         	            	-en-US
>         	            	+
>         	Test:       	TestIntegration/FsMkdir/FsPutFiles/Internal/Metadata
>         	Messages:   	content-language
> ```
> 
> Any ideas which options might help to pass the tests ?

This looks like the backend doesn't support the `Content-Language` header. Can you check its docs?

It is not a big deal.

**Comment by outscale-mgo** [comment]
Hello, here is my config:

```
[TestSFTPRclone]
# couldn't find type of fs for "TestSFTPRclone"
shell_type = unix
md5sum_command = md5sum
sha1sum_command = sha1sum

[TestSFTPRcloneSSH]
# couldn't find type of fs for "TestSFTPRcloneSSH"
shell_type = unix
md5sum_command = md5sum
sha1sum_command = sha1sum

[me]
type = s3
provider = Outscale
access_key_id = XXX
secret_access_key = XXX
region = eu-west-2
endpoint = oos.eu-west-2.outscale.com
acl = private
```

**Comment by outscale-mgo** [comment]
the character encoding tests that fail are those one:
```
    --- FAIL: TestIntegration/FsMkdir (260.82s)
        --- PASS: TestIntegration/FsMkdir/FsMkdirRmdirSubdir (0.16s)
        --- PASS: TestIntegration/FsMkdir/FsListEmpty (0.11s)
        --- PASS: TestIntegration/FsMkdir/FsListDirEmpty (0.05s)
        --- PASS: TestIntegration/FsMkdir/FsListRDirEmpty (0.05s)
        --- PASS: TestIntegration/FsMkdir/FsListDirNotFound (0.05s)
        --- PASS: TestIntegration/FsMkdir/FsListRDirNotFound (0.06s)
        --- FAIL: TestIntegration/FsMkdir/FsEncoding (10.21s)
            --- FAIL: TestIntegration/FsMkdir/FsEncoding/control_chars (0.08s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/dot (0.79s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/dot_dot (0.64s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/punctuation (0.65s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/leading_space (0.94s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/leading_tilde (1.08s)
            --- FAIL: TestIntegration/FsMkdir/FsEncoding/leading_CR (0.01s)
            --- FAIL: TestIntegration/FsMkdir/FsEncoding/leading_LF (0.04s)
            --- FAIL: TestIntegration/FsMkdir/FsEncoding/leading_HT (0.04s)
            --- FAIL: TestIntegration/FsMkdir/FsEncoding/leading_VT (0.04s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/leading_dot (1.53s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/trailing_space (0.70s)
            --- FAIL: TestIntegration/FsMkdir/FsEncoding/trailing_CR (0.02s)
            --- FAIL: TestIntegration/FsMkdir/FsEncoding/trailing_LF (0.07s)
            --- FAIL: TestIntegration/FsMkdir/FsEncoding/trailing_HT (0.06s)
            --- FAIL: TestIntegration/FsMkdir/FsEncoding/trailing_VT (0.06s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/trailing_dot (1.56s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/invalid_UTF-8 (0.89s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/URL_encoding (0.93s)
```

**Comment by outscale-mgo** [comment]
I've checked with the Doc, and yes it seems that `Content-Language` is ignored.

**Comment by ncw** [comment]
The character encoding errors look fine, let's ignore those.

Not supporting `Content-Language` is fine also - that is niche.

There is just that bit

> > With `useMultipartUploads` I got this error:
> > ```
> > === RUN   TestIntegration/FsMkdir/FsOpenChunkWriter
> > 2024/09/26 14:35:21 ERROR : writer-at-subdir/writer-at-file: Don't know how to set key "chunkSize" on upload
> > 2024/09/26 14:35:21 NOTICE: S3 bucket rclone-test-dubiyim5moxu: Streaming uploads using chunk size 5Mi will have maximum file size of 48.828Gi
> > ```
> 
> I don't understand this error! This seems to be trying to set some metadata called `chunkSize` which doesn't exist.

Can you attach the complete output of `rclone test -v -verbose -remote YOURPROVIDER:` please so I can check that over - thanks.

**Comment by outscale-mgo** [comment]
```
=== RUN   TestIntegration/FsMkdir/FsOpenWriterAt
    fstests.go:790: FS has no OpenWriterAt interface
=== RUN   TestIntegration/FsMkdir/FsOpenChunkWriter
2024/09/30 19:50:11 ERROR : writer-at-subdir/writer-at-file: Don't know how to set key "chunkSize" on upload
2024/09/30 19:50:11 NOTICE: S3 bucket rclone-test-letasep9jevo: Streaming uploads using chunk size 5Mi will have maximum file size of 48.828Gi
2024/09/30 19:50:11 DEBUG : writer-at-subdir/writer-at-file: open chunk writer: started multipart upload: ae0dd4599248462b8392290bed5609ef
2024/09/30 19:50:12 DEBUG : writer-at-subdir/writer-at-file: multipart upload wrote chunk 2 with 5242880 bytes and etag "f07a01409bd4733426b35b2ec8adacac"
2024/09/30 19:50:12 DEBUG : writer-at-subdir/writer-at-file: multipart upload wrote chunk 3 with 1048576 bytes and etag "7b0cdf29e537f663a8c3b69814890600"
2024/09/30 19:50:13 DEBUG : writer-at-subdir/writer-at-file: multipart upload wrote chunk 1 with 5242880 bytes and etag "25a3f67aa8a148535654ccee206a3e1a"
2024/09/30 19:50:13 DEBUG : writer-at-subdir/writer-at-file: multipart upload "ae0dd4599248462b8392290bed5609ef" finished
=== RUN   TestIntegration/FsMkdir/FsChangeNotify
```

**Comment by ncw** [comment]
Can you attach the complete output please. Thanks

**Comment by outscale-mgo** [comment]
Hello,

Here is the full output.
run with: 
```sh
go test -v -verbose -remote me: > out
```
[out.txt](https://github.com/user-attachments/files/17202831/out.txt)

**Comment by ncw** [comment]
> Here is the full output. run with:
> 
> ```shell
> go test -v -verbose -remote me: > out
> ```

That looks great now - thank you.

**Review by ncw — APPROVED** [review]
This looks good now - thank you :-)

I'll merge now.

**Pull request merged**
