### PR TITLE
compute total running average speed and use that for ETA and display

### PR DESCRIPTION
**Pull request by sjpotter**
#### What is the purpose of this change?

rclone only prints the average speed from the beginning of the connection which can be very different for long transfers over time from the actual speed one is getting at that moment.

This is easily seen by the ETA calculation being wrong in those cases.

i.e. if someone can get 2 MB/s per transfer, but can do 40 transfers in parallel to get 80MB/s they will see that as their average if its a very long transfer, but towards the end when only a few files are remaining, their actual transfer rate will be much lower, but ETA will still be calculated based on average from the beginning of time

use inProgress set to calculate the current transfer rate and use that for ETA as wel as printing

#### Was the change discussed in an issue or in the forum before?

sort of: https://github.com/rclone/rclone/issues/3909

#### Checklist

- [ ] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [ ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ ] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ivandeex** [comment]
Hi! Do you need a hand rebasing this on master?

**Comment by ivandeex** [comment]
I suspect this PR solves diferently the same problem as
#4329 (accounting: use **rolling** average for speed display)

**Comment by ivandeex** [comment]
@sjpotter Are you still interested in getting this merged?

**Comment by sjpotter** [comment]
the other pr can probably go ahead.

**Pull request closed without merging**
