### PR TITLE
size: warn about inaccurate results when objects with unknown size

### PR DESCRIPTION
**Pull request by albertony**
#### What is the purpose of this change?

Some backends do not provide object size and simply return -1, e.g. Google Docs documents in Google Drive backend. The reported size will ignore these, i.e. assume size 0. This PR adds information when this is the case.

This PR adds reporting of a notice log message:

```
2022/04/06 14:09:32 NOTICE: Google drive root '': Size may be underestimated due to 2 objects with unknown size
Total objects: 13 (13)
Total size: 27.125 MiB (28442166 Byte)
```

An alternative could be to include it in the output string:

```
Total objects: 13 (13)
Total size: 27.125 MiB (28442166 Byte) [Size may be underestimated due to 2 objects with unknown size]
```

I've also included the relevant information in the json and rc output, that is: The number of objects with unknown size. Don't know if this is something we want? I named the property `sizeless`, which is probably not the best name for it...!

By using log message alternative above this will be shown always, regardless if json output or not. If switching to the alternative 2 above (including the information in output string only), then called with option for json output this information would have to be included in the json (as it currently is) for user to get the information.

A third alternative could be to do it all: Log it as a notice log message, include it in the output string, and possibly also include in the json/rc output.

#### Was the change discussed in an issue or in the forum before?

Related to #6085, which handles similar case for `rclone ncdu` command.

#### Checklist

- [X] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [X] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [X] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [X] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by albertony** [comment]
Thank you for your feedback!

> Regarding the property name, maybe objsWithUnknownSize? Too long?

Maybe, not sure.. In json the existing properties are simply called "Count" and "Bytes", so wanted a concise name also for this - but maybe it is not possible. And also, I'm not sure if we even need or want this in the json. Your suggestion has been noted, but I think I'll wait and see if Nick has an opinion on the above first.

> Maybe we can include both the log and the output message. I think the log is harder to spot.

Sure. We have three places to include it:
- Log
- String output
- Json and rc output

Log sort of ensures it is always informed in some way, at least it should be possible for user to get the information if looking into logs one way or another. But the default size command returns human-readable string by default, so it does make sense to inform about it as part of the command output as well. 🤔

**Review by ncw — APPROVED** [review]
I think that looks nice - please merge, thank you :-)

**Comment by zanna-37** [comment]
Are we adding the string in the output as well? (in addition to the log) I think it would be beneficial.

**Comment by albertony** [comment]
Hard to find the perfect solution (as always).. I find that suggested alternative a bit too "messy":

```
Total size: 27.125 MiB (28442166 Byte) [Size may be underestimated due to 2 objects with unknown size]
```

Another alternative could be to included as a separate result property (when value is not 0), like it is with json/rc output:

```
Total objects: 13 (13)
Total size: 27.125 MiB (28442166 Byte)
Total objects with unknown size: 2
```

That does not explicitely tell user that size is underestimated, but that is implied? And also, could still report the notice log message.

I don't know if @ncw's approval meant he prefers the current implementation, or did not consider the alternatives, or have no strong opinion...?

**Comment by albertony** [comment]
Also, @zanna-37: I guess this is a edge case limited to Google Drive/Photos, pehaps some very few other cases? For Google Photos it is documented here: https://rclone.org/googlephotos/#size. But in Google Drive backend docs it is not mentioned, pehaps it should. Do you want to do that? Or if not; do you know in which cases Google Drive does and does not return file sizes?

**Comment by ncw** [comment]
> Hard to find the perfect solution (as always).. I find that suggested alternative a bit too "messy":
> 
> ```
> Total size: 27.125 MiB (28442166 Byte) [Size may be underestimated due to 2 objects with unknown size]
> ```

I think if you wanted to do this I'd just write

    Total size: 27.125 MiB (28442166 Byte) [2 objects with unknown size]

> Another alternative could be to include it as a separate result property (when value is not 0), like it is with json/rc output:
> 
> ```
> Total objects: 13 (13)
> Total size: 27.125 MiB (28442166 Byte)
> Total objects with unknown size: 2
> ```

I think this is the best solution and is matches up with the JSON.

> That does not explicitely tell user that size is underestimated, but that is implied? And also, could still report the notice log message.
> 
> I don't know if @ncw's approval meant he prefers the current implementation, or did not consider the alternatives, or have no strong opinion...?

My approval meant happy for you to merge what you have got already, though if you want to carry on refining it then that is fine too :-)

**Comment by ncw** [comment]
This looks ready to merge if you want to merge it?

**Pull request merged**
