### PR TITLE
cmd/mountlib: better snap mount error message

### PR DESCRIPTION
**Pull request by divinity76**
#### What is the purpose of this change?

mounting will always fail when rclone is installed from the snap package manager.
But the error message generated when trying to mount from a snap install was not
very good. Improve the error message.
Should prevent more bugreports like https://github.com/rclone/rclone/issues/8208
(I spent an hour on that bugreport.. Time wasted that wouldn't be if the error message was better)

#### Was the change discussed in an issue or in the forum before?

discussed in issue #8208.

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by divinity76** [comment]
Haven't found a way to actually test this because snap use mount tricks and read-only filesystem to protect it's install files, to the point where even root can't touch the filesystem the normal way, 
quote:
```
$ sudo bash -c 'cat ./rclone > /snap/rclone/current/bin/rclone'
bash: line 1: /snap/rclone/current/bin/rclone: Read-only file system
```

But the code seems trivial enough to me.. I'm requesting review.

**Review by ncw — APPROVED** [review]
This looks very useful, thank you and will undoubtedly help people in the future.

I'll merge when the ci goes green.

**Comment by divinity76** [comment]
@ncw thanks, was just a formatting issue, should be fixed now but the CI's didn't auto-rerun when I pushed the formatted version.. 
>1 workflow awaiting approval
>This workflow requires approval from a maintainer. [Learn more about approving workflows.](https://docs.github.com/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks)

Seems a maintainer needs to manually approve that the CI's re-run?

**Review by ncw — APPROVED** [review]
Thank you - looks great now :-)

**Pull request merged**
