### PR TITLE
backend/s3: add support for Internet Archive S3 API

### PR DESCRIPTION
**Pull request by liushuyu**
#### What is the purpose of this change?

This Pull Request will add Internet Archive support.

This is still a draft as I need some inputs about whether _it should have its own `Fs` type_ instead of introducing various hacks to the existing `s3` backend.

#### Was the change discussed in an issue or in the forum before?

In #1608 

#### Checklist

- [X] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [ ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ ] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ncw** [comment]
> It's a completely different API that does not conform to S3 implementations at all:

That looks very useful the output...

I think if we are replacing the listing it probably should be a new backend as I can see in there lots of things you can't get out of the s3 api like sha1, crc32, mtimes in listings etc

```
      "sha1": "9595045ac41eab38b66f0535e2ed1e9b04632941",
      "crc32": "ce64be45",
      "md5": "06c730d44a5046a7756f88f177515eec",
      "size": "14731016",
      "mtime": "1362412426",
```

**Comment by ivandeex** [comment]
@liushuyu Is this PR alive?

**Comment by ivandeex** [comment]
This PR is abandoned and needs a maintainer.
It will be closed in about three months.

**Comment by ncw** [comment]
I think probably what we should to is close this PR and open a new one about making a backend for the internet archive native API.

I think that would be a worthy goal for rclone to help with the internet archive.

**Comment by ivandeex** [comment]
A sufficiently recent reference implementation in go
https://github.com/nektro/go-internetarchive

**Comment by ivandeex** [comment]
Closing abandoned PR #4521

**Pull request closed without merging**
