### PR TITLE
bisync: add to integration tests - fixes #7665

### LINKED ISSUE #7665: bisync: add to integration tests
[Here](https://github.com/rclone/rclone/issues/6685#issuecomment-1974747783) we decided that bisync should participate in the integration tests for all backends

This will be part of giving us the confidence to take bisync out of beta.

I note that the bisync tests are likely to be troublesome here and very likely this issue will cause us to have to re-work them.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

### PR DESCRIPTION
**Pull request by nielash**
#### What is the purpose of this change?

This change officially adds bisync to the nightly integration tests for all backends.

This will be part of giving us the confidence to take bisync out of beta.

A number of fixes have been added to account for features which can differ on different backends -- for example, hash types / modtime support, empty directories, unicode normalization, and unimportant differences in log output. We will likely find that more of these are needed once we start running these with the full set of remotes.

Additionally, bisync's extremely sensitive tests revealed a few bugs in other backends that weren't previously covered by other tests. Fixes for those issues have been submitted on the following separate PRs (and bisync test failures will be expected until they are merged):

- #7670
- #7688
- #7690
- #7692

Relatedly, workarounds have been put in place for the following backend limitations that are unsolvable for the time being:

- #3262 (drive is sometimes aware of trashed files/folders when it shouldn't be)
- #6199 (dropbox can't handle emojis and certain other characters)
- #4590 (onedrive API has longstanding bug for `conflictBehavior=replace` in server-side copy/move)

#### Was the change discussed in an issue or in the forum before?

- #7665 

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Review by ncw — APPROVED** [review]
This looks great - thank you :-)

Let's merge this now and see what explodes in the integration tests.

I suspect fixing up all the errors is going to take some time!

The PR's you linked are all in progress so get merged soon.

This is a great step forward to making bisync production ready - well done :-)

Please merge when ready.

**Comment by nielash** [comment]
I added a fix for the bug described [here](https://github.com/rclone/rclone/pull/7692#issuecomment-2022258352).

I also added a condition to skip the `volatile` test on non-local, anticipating that your answer to [this question](https://github.com/rclone/rclone/pull/7670#discussion_r1540073107) will be "yes".

**Comment by ncw** [comment]
> I added a fix for the bug described [here](https://github.com/rclone/rclone/pull/7692#issuecomment-2022258352).

Great

> I also added a condition to skip the `volatile` test on non-local, anticipating that your answer to [this question](https://github.com/rclone/rclone/pull/7670#discussion_r1540073107) will be "yes".

And yes!

I suggest you merge this now - we don't have to merge all the fixes first.

**Comment by nielash** [comment]
> I suggest you merge this now - we don't have to merge all the fixes first.

Ok great -- will do now!

Are the 2 `memory` bug fixes good to go as well? I think I made all the changes.

**Comment by ncw** [comment]
> Are the 2 `memory` bug fixes good to go as well? I think I made all the changes.

Yes they look good now - please merge :-)

**Pull request merged**
