### PR TITLE
Adding a new backend implementation for uloz.to

### PR DESCRIPTION
**Pull request by iotmaestro**
#### What is the purpose of this change?

As noted in the title, this PR adds a new backend for uloz.to. In the past the server was focused on free-for-all sharing, and has recently pivoted into a more Dropbox-like business model. They offer affordable storage plans, especially around the 10 TB mark where other larger providers fall short.

The PR only implements the basic functionality for now. I plan to add support for more optional features but wanted to keep the initial PR as simple as possible (it's quite bloated already).

Disclaimer: I'm not affiliated with Uloz.to in any way but as a satisfied customer.

#### Was the change discussed in an issue or in the forum before?

No

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [ ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages). - **apologies about this, let's squash merge with a better message** 
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ncw** [comment]
I've given the code a quick skim and it is looking good :-) I started the CI on it.

How are the integration tests looking? Do the `test_all` results work properly?

**Comment by iotmaestro** [comment]
Thank you for taking a look!

I ran the integration tests before submitting the PR, they're all green. The free tier account is more than enough to run them if you want to try it yourself. Here' s a log from a run after the last commit:

```
go test -v
=== RUN   TestIntegration
    fstests.go:446: Using remote "TestUlozto:"
=== RUN   TestIntegration/FsCheckWrap
    fstests.go:487: Not a wrapping Fs
=== RUN   TestIntegration/FsCommand
    fstests.go:515: No commands in this remote
=== RUN   TestIntegration/FsRmdirNotFound
=== RUN   TestIntegration/FsString
=== RUN   TestIntegration/FsName
=== RUN   TestIntegration/FsRoot
=== RUN   TestIntegration/FsRmdirEmpty
=== RUN   TestIntegration/FsMkdir
=== RUN   TestIntegration/FsMkdir/FsMkdirRmdirSubdir
=== RUN   TestIntegration/FsMkdir/FsListEmpty
=== RUN   TestIntegration/FsMkdir/FsListDirEmpty
=== RUN   TestIntegration/FsMkdir/FsListRDirEmpty
    fstests.go:407: FS has no ListR interface
=== RUN   TestIntegration/FsMkdir/FsListDirNotFound
2024/01/09 16:50:39 ERROR : does not exist: error listing: directory not found
=== RUN   TestIntegration/FsMkdir/FsListRDirNotFound
    fstests.go:407: FS has no ListR interface
=== RUN   TestIntegration/FsMkdir/FsEncoding
=== RUN   TestIntegration/FsMkdir/FsEncoding/control_chars
    fstests.go:712: testing "␀␁␂␃␄␅␆␇␈␉␊␋␌␍␎␏␐␑␒␓␔␕␖␗␘␙␚␛␜␝␞␟␡"
=== RUN   TestIntegration/FsMkdir/FsEncoding/dot
    fstests.go:712: testing "．"
=== RUN   TestIntegration/FsMkdir/FsEncoding/dot_dot
    fstests.go:712: testing "．．"
=== RUN   TestIntegration/FsMkdir/FsEncoding/punctuation
    fstests.go:712: testing "!\"#$%&'()*+,-.／:;<=>?@[\\]^_`{|}~"
=== RUN   TestIntegration/FsMkdir/FsEncoding/leading_space
    fstests.go:712: testing " leading space"
=== RUN   TestIntegration/FsMkdir/FsEncoding/leading_tilde
    fstests.go:712: testing "~leading tilde"
=== RUN   TestIntegration/FsMkdir/FsEncoding/leading_CR
    fstests.go:712: testing "␍leading CR"
=== RUN   TestIntegration/FsMkdir/FsEncoding/leading_LF
    fstests.go:712: testing "␊leading LF"
=== RUN   TestIntegration/FsMkdir/FsEncoding/leading_HT
    fstests.go:712: testing "␉leading HT"
=== RUN   TestIntegration/FsMkdir/FsEncoding/leading_VT
    fstests.go:712: testing "␋leading VT"
=== RUN   TestIntegration/FsMkdir/FsEncoding/leading_dot
    fstests.go:712: testing ".leading dot"
=== RUN   TestIntegration/FsMkdir/FsEncoding/trailing_space
    fstests.go:712: testing "trailing space "
=== RUN   TestIntegration/FsMkdir/FsEncoding/trailing_CR
    fstests.go:712: testing "trailing CR␍"
=== RUN   TestIntegration/FsMkdir/FsEncoding/trailing_LF
    fstests.go:712: testing "trailing LF␊"
=== RUN   TestIntegration/FsMkdir/FsEncoding/trailing_HT
    fstests.go:712: testing "trailing HT␉"
=== RUN   TestIntegration/FsMkdir/FsEncoding/trailing_VT
    fstests.go:712: testing "trailing VT␋"
=== RUN   TestIntegration/FsMkdir/FsEncoding/trailing_dot
    fstests.go:712: testing "trailing dot."
=== RUN   TestIntegration/FsMkdir/FsEncoding/invalid_UTF-8
    fstests.go:712: testing "invalid utf-8\xfe"
=== RUN   TestIntegration/FsMkdir/FsEncoding/URL_encoding
    fstests.go:712: testing "test%46.txt"
=== RUN   TestIntegration/FsMkdir/FsNewObjectNotFound
=== RUN   TestIntegration/FsMkdir/FsPutError
=== RUN   TestIntegration/FsMkdir/FsPutZeroLength
=== RUN   TestIntegration/FsMkdir/FsOpenWriterAt
    fstests.go:785: FS has no OpenWriterAt interface
=== RUN   TestIntegration/FsMkdir/FsOpenChunkWriter
    fstests.go:818: FS has no OpenChunkWriter interface
=== RUN   TestIntegration/FsMkdir/FsChangeNotify
    fstests.go:867: FS has no ChangeNotify interface
=== RUN   TestIntegration/FsMkdir/FsPutFiles
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsListDirFile2
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsListRDirFile2
    fstests.go:407: FS has no ListR interface
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsListR
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsListRSubdir
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsListDirRoot
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsListRDirRoot
    fstests.go:407: FS has no ListR interface
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsListSubdir
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsListRSubdir#01
    fstests.go:407: FS has no ListR interface
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsListLevel2
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsListRLevel2
    fstests.go:407: FS has no ListR interface
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsListFile1
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsNewObject
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsNewObjectCaseInsensitive
    fstests.go:1120: Not Case Insensitive
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsListFile1and2
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsNewObjectDir
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsPurge
    fstests.go:1152: FS has no Purge interface
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsPurgeRoot
    fstests.go:1189: FS has no Purge interface
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsCopy
    fstests.go:1231: FS has no Copier interface
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsMove
    fstests.go:1265: FS has no Mover interface
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsDirMove
    fstests.go:1336: FS has no DirMover interface
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsRmdirFull
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsPrecision
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectString
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectFs
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectRemote
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectHashes
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectModTime
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectMimeType
    fstests.go:1469: MimeType method not supported
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectMetadata
    fstests.go:1500: Metadata method not supported
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectSetModTime
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectSize
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectOpen
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectOpenSeek
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectOpenRange
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectPartialRead
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectUpdate
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectStorable
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsIsFile
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsIsFile/FsRoot
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsIsFileNotFound
2024/01/09 16:52:24 ERROR : : error listing: directory not found
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FromRoot
    fstests.go:1727: Opening root remote "TestUlozto:" path "rclone-test-hawosek0vezinum8gilevel0" from "TestUlozto:rclone-test-hawosek0vezinum8gilevel0"
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FromRoot/List
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FromRoot/ListEntries
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FromRoot/ListR
    fstests.go:1761: FS has no ListR interface
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FromRoot/Put
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FromRoot/Put/Remove
=== RUN   TestIntegration/FsMkdir/FsPutFiles/PublicLink
    fstests.go:1820: FS has no PublicLinker interface
=== RUN   TestIntegration/FsMkdir/FsPutFiles/SetTier
    fstests.go:420: FS has no SetTier & GetTier interfaces
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectCheckWrap
    fstests.go:1925: Not a wrapping Fs
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectRemove
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectAbout
    fstests.go:1959: FS does not support About
=== RUN   TestIntegration/FsMkdir/FsPutFiles/FsPutStream
    fstests.go:1977: FS has no PutStream interface
=== RUN   TestIntegration/FsMkdir/FsPutFiles/Internal
    fstests.go:2021: *ulozto.Fs does not implement InternalTester
=== RUN   TestIntegration/FsMkdir/FsPutChunked
    fstests.go:2042: *ulozto.Fs does not implement SetUploadChunkSizer
=== RUN   TestIntegration/FsMkdir/FsCopyChunked
    fstests.go:2160: FS has no Copier interface
=== RUN   TestIntegration/FsMkdir/FsUploadUnknownSize
=== RUN   TestIntegration/FsMkdir/FsUploadUnknownSize/FsPutUnknownSize
=== RUN   TestIntegration/FsMkdir/FsUploadUnknownSize/FsUpdateUnknownSize
=== RUN   TestIntegration/FsMkdir/FsRootCollapse
2024/01/09 16:52:45 ERROR : : error listing: directory not found
2024/01/09 16:52:45 ERROR : : error listing: directory not found
2024/01/09 16:52:46 ERROR : uloz.to root 'rclone-test-hawosek0vezinum8gilevel0': Failed to list "": directory not found
2024/01/09 16:52:46 ERROR : : Failed to rmdir: directory not found
=== RUN   TestIntegration/FsShutdown
    fstests.go:2331: Shutdown method not supported
--- PASS: TestIntegration (137.26s)
    --- SKIP: TestIntegration/FsCheckWrap (0.00s)
    --- SKIP: TestIntegration/FsCommand (0.00s)
    --- PASS: TestIntegration/FsRmdirNotFound (0.23s)
    --- PASS: TestIntegration/FsString (0.00s)
    --- PASS: TestIntegration/FsName (0.00s)
    --- PASS: TestIntegration/FsRoot (0.00s)
    --- PASS: TestIntegration/FsRmdirEmpty (1.14s)
    --- PASS: TestIntegration/FsMkdir (133.09s)
        --- PASS: TestIntegration/FsMkdir/FsMkdirRmdirSubdir (4.23s)
        --- PASS: TestIntegration/FsMkdir/FsListEmpty (0.23s)
        --- PASS: TestIntegration/FsMkdir/FsListDirEmpty (0.24s)
        --- SKIP: TestIntegration/FsMkdir/FsListRDirEmpty (0.00s)
        --- PASS: TestIntegration/FsMkdir/FsListDirNotFound (0.26s)
        --- SKIP: TestIntegration/FsMkdir/FsListRDirNotFound (0.00s)
        --- PASS: TestIntegration/FsMkdir/FsEncoding (74.79s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/control_chars (4.00s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/dot (3.22s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/dot_dot (3.39s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/punctuation (11.22s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/leading_space (3.13s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/leading_tilde (5.24s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/leading_CR (3.27s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/leading_LF (3.18s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/leading_HT (3.44s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/leading_VT (3.37s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/leading_dot (3.52s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/trailing_space (3.51s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/trailing_CR (3.44s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/trailing_LF (3.31s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/trailing_HT (3.66s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/trailing_VT (3.44s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/trailing_dot (3.32s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/invalid_UTF-8 (3.47s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/URL_encoding (3.42s)
        --- PASS: TestIntegration/FsMkdir/FsNewObjectNotFound (0.51s)
        --- PASS: TestIntegration/FsMkdir/FsPutError (3.61s)
        --- PASS: TestIntegration/FsMkdir/FsPutZeroLength (2.91s)
        --- SKIP: TestIntegration/FsMkdir/FsOpenWriterAt (0.00s)
        --- SKIP: TestIntegration/FsMkdir/FsOpenChunkWriter (0.00s)
        --- SKIP: TestIntegration/FsMkdir/FsChangeNotify (0.00s)
        --- PASS: TestIntegration/FsMkdir/FsPutFiles (31.49s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsListDirFile2 (1.17s)
            --- SKIP: TestIntegration/FsMkdir/FsPutFiles/FsListRDirFile2 (0.00s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsListR (1.21s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsListRSubdir (0.95s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsListDirRoot (1.63s)
            --- SKIP: TestIntegration/FsMkdir/FsPutFiles/FsListRDirRoot (0.00s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsListSubdir (0.48s)
            --- SKIP: TestIntegration/FsMkdir/FsPutFiles/FsListRSubdir#01 (0.00s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsListLevel2 (0.52s)
            --- SKIP: TestIntegration/FsMkdir/FsPutFiles/FsListRLevel2 (0.00s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsListFile1 (1.16s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsNewObject (0.12s)
            --- SKIP: TestIntegration/FsMkdir/FsPutFiles/FsNewObjectCaseInsensitive (0.00s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsListFile1and2 (1.19s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsNewObjectDir (0.22s)
            --- SKIP: TestIntegration/FsMkdir/FsPutFiles/FsPurge (0.00s)
            --- SKIP: TestIntegration/FsMkdir/FsPutFiles/FsPurgeRoot (0.00s)
            --- SKIP: TestIntegration/FsMkdir/FsPutFiles/FsCopy (0.00s)
            --- SKIP: TestIntegration/FsMkdir/FsPutFiles/FsMove (0.00s)
            --- SKIP: TestIntegration/FsMkdir/FsPutFiles/FsDirMove (0.00s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsRmdirFull (0.15s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsPrecision (0.00s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/ObjectString (0.13s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/ObjectFs (0.13s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/ObjectRemote (0.12s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/ObjectHashes (0.14s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/ObjectModTime (0.16s)
            --- SKIP: TestIntegration/FsMkdir/FsPutFiles/ObjectMimeType (0.16s)
            --- SKIP: TestIntegration/FsMkdir/FsPutFiles/ObjectMetadata (0.13s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/ObjectSetModTime (0.48s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/ObjectSize (0.12s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/ObjectOpen (0.74s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/ObjectOpenSeek (0.62s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/ObjectOpenRange (1.29s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/ObjectPartialRead (0.44s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/ObjectUpdate (1.55s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/ObjectStorable (0.13s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsIsFile (3.08s)
                --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsIsFile/FsRoot (0.00s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FsIsFileNotFound (1.94s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/FromRoot (6.45s)
                --- PASS: TestIntegration/FsMkdir/FsPutFiles/FromRoot/List (1.31s)
                --- PASS: TestIntegration/FsMkdir/FsPutFiles/FromRoot/ListEntries (0.22s)
                --- SKIP: TestIntegration/FsMkdir/FsPutFiles/FromRoot/ListR (0.00s)
                --- PASS: TestIntegration/FsMkdir/FsPutFiles/FromRoot/Put (3.59s)
                    --- PASS: TestIntegration/FsMkdir/FsPutFiles/FromRoot/Put/Remove (1.38s)
            --- SKIP: TestIntegration/FsMkdir/FsPutFiles/PublicLink (0.00s)
            --- SKIP: TestIntegration/FsMkdir/FsPutFiles/SetTier (0.00s)
            --- SKIP: TestIntegration/FsMkdir/FsPutFiles/ObjectCheckWrap (0.00s)
            --- PASS: TestIntegration/FsMkdir/FsPutFiles/ObjectRemove (1.54s)
            --- SKIP: TestIntegration/FsMkdir/FsPutFiles/ObjectAbout (0.00s)
            --- SKIP: TestIntegration/FsMkdir/FsPutFiles/FsPutStream (0.00s)
            --- SKIP: TestIntegration/FsMkdir/FsPutFiles/Internal (0.00s)
        --- SKIP: TestIntegration/FsMkdir/FsPutChunked (0.00s)
        --- SKIP: TestIntegration/FsMkdir/FsCopyChunked (0.00s)
        --- PASS: TestIntegration/FsMkdir/FsUploadUnknownSize (3.32s)
            --- PASS: TestIntegration/FsMkdir/FsUploadUnknownSize/FsPutUnknownSize (1.14s)
            --- PASS: TestIntegration/FsMkdir/FsUploadUnknownSize/FsUpdateUnknownSize (2.18s)
        --- PASS: TestIntegration/FsMkdir/FsRootCollapse (2.00s)
    --- SKIP: TestIntegration/FsShutdown (0.00s)
PASS
ok      github.com/rclone/rclone/backend/ulozto 137.271s
```

**Comment by StarHack** [comment]
@iotmaestro Thanks for your contribution. I tested this feature today with a real premium account with super old files in it and the connection failed with the error message `can't decode, unknown encoded metadata version` (ulozto.go#605).  The logic expected `"1"` but actually was fed with an empty string.

I simply changed  the function `decodeDescriptionMetadata` to return an empty struct `DescriptionEncodedMetadata{}` for now and most of the actions worked (including mounts). Uploads didn't. The app crashed but that's presumably because of the changes.

**Comment by iotmaestro** [comment]
@StarHack Thanks for flagging. I'm incorrectly assuming all remote files originate from rclone uploads (which is true for my intended use case) but not true in general. I'll take another look at handling the metadata.

**Comment by iotmaestro** [comment]
Should be fixed now, also added a custom integration test for the issue.

All tests still [look good](https://gist.github.com/iotmaestro/5ba28b68f7391aa08d4b5ab582177024).

**Comment by StarHack** [comment]
@iotmaestro The implementation is indeed working flawlessly now, thank you!

I discovered one more (minor) issue. When mounting a volume, the following hint is printed:

```
./rclone mount ulozto: /mnt/ulozto/
2024/01/23 03:27:15 NOTICE: uloz.to root '': --vfs-cache-mode writes or full is recommended for this remote as it can't stream
```

If we actually use the flag `--vfs-cache-mode writes`, the program is crashing (ulozto.go#824):

```
./rclone mount --vfs-cache-mode writes  ulozto: /mnt/ulozto/
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x18e9800]

goroutine 1 [running]:
github.com/rclone/rclone/backend/ulozto.(*Object).Fs(0x1f8a200?)
	/rclone/backend/ulozto/ulozto.go:824
github.com/rclone/rclone/fs.Fingerprint({0x28e2990, 0x3b7c7c0}, {0x7f111ed8b058, 0x0}, 0x0)
	/rclone/fs/fingerprint.go:24 +0x71
github.com/rclone/rclone/vfs/vfscache.(*Item)._checkObject(0xc0009e8000, {0x28f7ab8, 0x0})
	/rclone/vfs/vfscache/item.go:805 +0xfc
```

**Comment by iotmaestro** [comment]
@StarHack can you share your repro steps? I can't reproduce the issue with either vfs cache mode using all sorts of file/folder operations. Building from the PR branch (f4571f79a56f24ddc812f0c18fc03b3c01447c19).

**Comment by StarHack** [comment]
@iotmaestro You're right. I recreated the config and the error no longer occurs. All good!

**Comment by maniac-manfred** [comment]
Thanks for providing uloz in rclone.
I have a question as to whether others have the problem uploading larger files (from 2.5GB) it crashes and tries to upload the file over and over again.

2024/02/13 20:56:52 DEBUG : test.img: >Attr: a=valid=1s ino=0 size=2700000000 mode=-rw-r--r--, err=<nil>
2024/02/13 20:56:52 DEBUG : &{test.img (w)}: Flush: 
2024/02/13 20:56:52 DEBUG : test.img: md5 = 0fb32f64dc93629ece010c8bad68fcd3 OK
2024/02/13 20:56:52 DEBUG : test.img: Size and md5 of src and dst objects identical
2024/02/13 20:57:01 DEBUG : pacer: low level retry 1/1 (error HTTP error 500 (500 Internal Server Error) returned body: "<html>\r\n<head><title>500 Internal Server Error</title></head>\r\n<body>\r\n<center><h1>500 Internal Server Error</h1></center>\r\n<hr><center>nginx/1.18.0</center>\r\n</body>\r\n</html>\r\n")
2024/02/13 20:57:01 DEBUG : pacer: Rate limited, increasing sleep to 20ms
2024/02/13 20:57:02 DEBUG : test.img: Received error: HTTP error 500 (500 Internal Server Error) returned body: "<html>\r\n<head><title>500 Internal Server Error</title></head>\r\n<body>\r\n<center><h1>500 Internal Server Error</h1></center>\r\n<hr><center>nginx/1.18.0</center>\r\n</body>\r\n</html>\r\n" - low level retry 0/10
2024/02/13 20:57:02 DEBUG : pacer: Reducing sleep to 15ms
2024/02/13 20:57:02 DEBUG : pacer: Reducing sleep to 11.25ms
2024/02/13 20:57:02 DEBUG : pacer: Reducing sleep to 10ms

**Comment by iotmaestro** [comment]
Thanks for flagging @maniac-manfred. This looks like an undocumented internal limitation of the API (and possibly even a bug, given the error code) on uloz.to's end. The correct fix for that is using the chunked upload API but I plan to submit support for that as a separate PR once the basics are merged.

For now, I'll add a rclone condition to skip files over 2500M. I haven't bisected the exact threshold but at the end of the day a few megs don't make much of a difference.

**Comment by etaloncop** [comment]
When will this get merged?

**Comment by n0v3xx** [comment]
@ncw Hi, could you check this PR again and maybe merge it?

**Comment by Griss168** [comment]
Tried the same thing today on Windows 10 with the same result.

3GB file uploaded to uloz.to at a speed of 5 MByte/s. I stopped it after 30 minutes.

**Comment by iotmaestro** [comment]
@Griss168 Thanks for trying the implementation and for the feedback. 

The file size limit is a known issue discussed here: https://github.com/rclone/rclone/pull/7552#issuecomment-1956316492. It's an undocumented limitation of the upload API and the fix is to use the chunked upload API. Looks like I forgot to push the temporary workaround to skip files which are too big - I'll do so when I get back home in a week. It's just an if condition if you want to add it yourself. 

The chunker support, as the message suggests, relies on implementation of optional interfaces which I didn't include in the integration (yet). I have a minimal implementation of Mover ready which is good enough for chunker but IIRC it doesn't pass the whole test suite. I can share it in a separate branch if there's interest (in a week). It's again a fairly simple alteration of one of the already implemented API calls to update the folder slug of an existing file.

In general I wanted to keep the PR as small as possible but given the turnaround time (not complaining, just look at my own round trip time :) ) it might be better to shove everything in here. No promises though.

**Comment by ncw** [comment]
@iotmaestro I'm happy to merge this now - it would be good to get it into v1.67

Shall I merge as-is? Are you finished with it? You can always make followup PRs.

**Comment by iotmaestro** [comment]
@ncw I think it's good to go as-is, having just added the condition for skipping large files again (added a test and did a quick manual run but as said previously still on the go, so didn't spend too much though on hackiness).

I'll continue improving the integration incrementally. The file size limit is rather annoying and chunked upload is much more reliable in general so that's the natural next step. I hope I'll have some time over Easter to look at it.

**Comment by Griss168** [comment]
I'm not familiar with Go and I'm not a developer in general, just an hobbyist. But today I read the uloz.to website API documentation https://uloz.to/upload-resumable-api-beta and at the bottom I found sample code written in Python and BASH. I tried it and it works with files larger than 2.5 GB. If you know Python or Bash, you might find a difference between your implementation and theirs.
In my quick look I found that in your code you use /v5/upload/link to upload files instead of the Python script using /v6/upload/link.
https://uloz.to/apidoc/public#tag/menuUploadLink

There is also an example code for /v5/upload/link and when I try it, it doesn't work with large files.
https://uloz.to/upload-api-beta

**Comment by iotmaestro** [comment]
@Griss168 that's the chunked upload API I'm referring to in other comments. 

The difference is that the API this PR is using uploads the file as a single piece, whereas with the chunked API the client (rclone in our case) chops the file up into smaller blocks, uploads each of them individually, and then tells server to reconstruct the file once all blocks are ready. Apart from the max file size limitation, this is also better for other reasons, e.g. reliability and resource utlization. If an upload fails you only need to retry uploading the small piece, not the whole large file.

**Comment by Griss168** [comment]
There is also example code that uses a file upload in one piece. With the BASH script, I uploaded an 8GB .iso file without any problems.
https://uloz.to/upload-api-beta

**Comment by iotmaestro** [comment]
@Griss168 Good catch, the script uses `v6` as well. It might be as easy as replacing `v5` with `v6` after all.

**Comment by Griss168** [comment]
There must be something else because I tried it (replace V5 with V6) and the result is the same. Infinite upload.

**Review by ncw — APPROVED** [review]
This looks great now - thank you :-)

I'll merge now for v1.67.

**Comment by Griss168** [comment]
[iotmaestro](https://github.com/iotmaestro) I searched a little deeper yesterday and found out that the upload link generated by your backend can easily upload a file larger than 3GB using CURL. But if the same file is uploaded using the same generated upload link using the /lib/rest library used in your backend, after uploading approx. 2.5 GB, the server will return HTTP 500 "Internal Server Error". Subsequently, the entire upload process is restarted and continues from the beginning (infinite loop).

It is interesting, however, that this does not happen with CURL and that with a minimum of parameters (practically only the POST method, the generated URL and the location of the file)

**Comment by iotmaestro** [comment]
@Griss168 I narrowed down the issue to the presence of the Content-Length header (or lack thereof) - setting it seems to do the trick at least at first glance. I'll keep digging,.

**Comment by Vidanox** [comment]
Hi, how exactly do you add the uloz.to remote? Instructions in rclone are unclear, what is "option username/password"? do i insert my email as the username and application token as the password? Because that doesn't work

**Comment by nelson777** [comment]
I'm testing this. And I'm getting the following error:

2024/05/21 01:25:40 Failed to create file system for "uloz:bkp/test.vdi": Error 90001 (401): Invalid authorization token. Please provide correct X-Auth-Token api key header.

I got the token from the application token in settings (https://uloz.to/nastaveni). Is this correct ? I used my email as username and even tested with the numeric user_id. What am I doing wrong ?

**Comment by nelson777** [comment]
I could make it work with test key " ;HG%7jW6@6/8vx">R;f(". Is that it ?

2 questions:

-Is there any way to change chunk size or use multithreaded single file uploads in order to increase speed ? 
-Any specific options for this backend ?

**Comment by ckcr4lyf** [comment]
> I could make it work with test key " ;HG%7jW6@6/8vx">R;f(". Is that it ?

Yes. Though technically this is only meant for debugging and can change at anytime. You would need to contact their support for a more permanent key.

**Comment by iotmaestro** [comment]
Thanks for trying the implementation out!

> -Is there any way to change chunk size or use multithreaded single file uploads in order to increase speed ?

Not yet - I've been a bit too busy to carve out time for it, but it's on the todo list.

Nevertheless, according to my testing it's not too hard to saturate a gigabit line even with a single connection if the file is large. For smaller files, setting the file level concurrency might be a better strategy.

> -Any specific options for this backend ?

See [the docs](https://tip.rclone.org/ulozto/).

**Comment by StarHack** [comment]
> Now I saw in the doc that copy isn't even supported: https://rclone.org/overview/#optional-features
> 
> However in the uluz setup doc it clearly uses rclone copy as an example. What's true here? :D

I've used `rclone copy <source_dir> ulozto:` for several TB of data and it definitely works fine.

**Comment by ManuelReschke** [comment]
@elchupacabrinski do you setup the remote with an requested API key? This key is **only available from the uloz support** via mail.

**Comment by elchupacabrinski** [comment]
> @elchupacabrinski do you setup the remote with an requested API key? This key is **only available from the uloz support** via mail.

Yeah I got my own key from support! It's just I can't get it to copy as intended, copying random files over and over again + some unfortunate issues with long file names

**Pull request merged**
