### PR TITLE
Add SCSU as tables

### PR DESCRIPTION
**Pull request by klauspost**
#### What is the purpose of this change?

Instead of only adding SCSU to #4866, add it as an existing table.

Allow direct SCSU and add a reasonable table as well.

Add byte interfaces that doesn't base64 encode the URL as well with `EncodeBytes` and `DecodeBytes`.

Fuzz tested and decode tests added.

#### Was the change discussed in an issue or in the forum before?

Only in issue #4866

File used for generating the table: [sample.txt.gz](https://github.com/rclone/rclone/files/5765636/sample.txt.gz) using `go run gentable.go -index=sample.txt -scsu -all`

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ncw** [comment]
Sorry for the long delay looking at this!

I think the idea is great and we should merge :-)

The tests indicate we probably need to exclude go1.12 from the build though (we've dropped go1.11 support just recently).

**Comment by klauspost** [comment]
@ncw No problem. I don't feel like forking the upstream just for this, so removing 1.12 (which AFAICT has know security issues) would probably be fine.

**Comment by ncw** [comment]
Do you want to put some build constraints in to exclude go1.12? That would be fine with me.

The mac build failure is a flakey test

The xgo failure is because the go.mod is out of date WRT the code and go is trying to update it on a read only fs I think.

**Comment by klauspost** [comment]
@ncw Updated+master merged.

**Comment by klauspost** [comment]
The remaining failures appears to be unrelated now.

**Comment by ncw** [comment]
I just added a commit to try to fix the build/other_os - I think what is happening is that the go.mod file isn't sorted so go1.13 is sorting it and can't write it back to the read only docker image...

**Comment by ncw** [comment]
If that works, I'll rebase the branch and merge :-)

**Comment by ncw** [comment]
OK all built!  I'll merge now - thank you @klauspost 

Next crypt integration and a bit of experimentation.

**Comment by klauspost** [comment]
@ncw Great. For crypt input you can use the byte interfaces which of course is more compact than the base64 string versions.

**Pull request merged**
