### PR TITLE
backend/tardigrade: Upgrade to uplink v1.0.6

### PR DESCRIPTION
**Pull request by calebcase**
This fixes an important bug with listing that affects users with more
than 500 objects in a listing operation.

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by calebcase** [comment]
@ncw Sorry for this. We found this bug earlier in the cycle, but then spaced cutting a release of our client library. The bug can be pretty bad as users will see rclone "hang" if they have more than 500 objects in a listing. It never gets past the first page of objects and keeps pulling down the same page over and over.

I didn't add a test in rclone for this because we have added a test upstream in storj/uplink for it.

**Comment by kaloyan-raev** [comment]
@calebcase I think the correct new version of libuplink is v1.0.6, not v1.6.0. Could you fix the PR title to avoid confusion if someone sees this in the future.

**Comment by calebcase** [comment]
@kaloyan-raev doh! Thanks!

**Comment by calebcase** [comment]
> Well done for fixing :-)
> 
> Would you like this in a point release for 1.52?
> 
> I think it probably should be even though it is a bigger change than I normally like for point releases.

Yes, that would be great if it isn't too much trouble.

**Comment by ncw** [comment]
That is fine!

**Comment by ncw** [comment]
@calebcase it looks like this update has broken some of [the integration tests](https://pub.rclone.org/integration-tests/current/)

image

Logs [1](https://pub.rclone.org/integration-tests/current/tardigrade-fs.sync-TestTardigrade-5.txt) and [2](https://pub.rclone.org/integration-tests/current/tardigrade-fs.sync-TestTardigrade-fastlist-5.txt)

Can you take a look please?

**Comment by calebcase** [comment]
> @calebcase it looks like this update has broken some of [the integration tests](https://pub.rclone.org/integration-tests/current/)
> 
> image
> 
> Logs [1](https://pub.rclone.org/integration-tests/current/tardigrade-fs.sync-TestTardigrade-5.txt) and [2](https://pub.rclone.org/integration-tests/current/tardigrade-fs.sync-TestTardigrade-fastlist-5.txt)
> 
> Can you take a look please?

Investigating...

**Comment by calebcase** [comment]
> > @calebcase it looks like this update has broken some of [the integration tests](https://pub.rclone.org/integration-tests/current/)
> > image
> > Logs [1](https://pub.rclone.org/integration-tests/current/tardigrade-fs.sync-TestTardigrade-5.txt) and [2](https://pub.rclone.org/integration-tests/current/tardigrade-fs.sync-TestTardigrade-fastlist-5.txt)
> > Can you take a look please?
> 
> Investigating...

@ncw We've located the regression and missing test. A subtle change to the way error types are converted resulted in the bucket error getting incorrectly converted to object not found. There will be another release of up the upstream library to fix it.

**Comment by ncw** [comment]
> We've located the regression and missing test. A subtle change to the way error types are converted resulted in the bucket error getting incorrectly converted to object not found. There will be another release of up the upstream library to fix it.

Great! I'll hold off the point release until then :-)

**Pull request merged**
