### PR TITLE
chunker: reservations for future, security improvements, complete sha1/md5 overlay

### PR DESCRIPTION
**Pull request by ivandeex**
#### What is the purpose of this change?

Goal:
Reserve possibility for future chunker/rclone releases to add more control information (which can be used to implement resumable uploads etc) in a way that future types of hidden chunks don't play jack-in-the-box in file listings of unaware past releases.

Subgoals:
* keep metadata format estableshed earlier
* postpone creation of internal structures for future, only prepare chunk name and metadata validators
* rectify validation so that future control structures can't be accidentally corrupted by past releases
* polish terminology in docs and comments (in fact 70% of the diff).

Security fixes:
* reject or report attempts to corrupt chunks (in fact remaining 20% of the diff)
* reject huge numbers in chunk name, prevent memory overflow
* specially handle user files containing valid chunker metadata  (currently treated as corrupted composites upon upload)

New Features:
* implement consistent hashing option

#### Was the change discussed in an issue or in the forum before?

No, but it's good :)

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ivandeex** [comment]
Of Testing:
I'm not adding remotes with consistent hashing into "config.yaml". They are rather superfluous (rclone config is copy/pasted from similar hashing remotes with substitution "hash_type = sha1all"):
```
- backend:  "chunker"
  remote:   "TestChunkerChunk50bSha1AllMailru:"
  fastlist: true
  maxfile:  3k
  ignore:
    - TestSyncWithTrackRenames
```
Tracking test detects new counters because hash-based sync jumps in. Expected.

Integration tests (`test_all -backends=chunker`) pass, except for 3 issues I'm being investigating:
* test `TestIntegration/FsMkdir/FsPutFiles/Internal/MetadataInput` fails on remote `TestChunkerChunk50bYandex` with non-standar error  message `"can't move file - destination already exists"` (translated from russian). I will change Fs.baseMove() to delete destination and repeat move if first move fails with whatever error
* Tests on remote `TestChunkerChunk3bLocal` have become slow, under investigation
* Encoding tests fail on `TestChunkerChunk3bLoca`, with lots of debug messages `"chunk without meta object"`, under investigation

**Comment by ncw** [comment]
I fixed the build :-(

Do you want me to merge this now or wait until you've investigated the test failures?

**Comment by ivandeex** [comment]
> Do you want me to merge this now or wait until you've investigated the test failures?
Do I have to rebase to pick the fixed build?
I'd rather take one-two days to investigate.

**Comment by ncw** [comment]
Yes rebase needed. I think you've done that already though 

Ok will await your updates.

**Comment by ivandeex** [comment]
Integration tests pass now. Please review.

**Comment by ivandeex** [comment]
Besides official test_all and integration tests I have run it on real data, all works fine for me. Hopefully you have time to integrate this change.

**Comment by ivandeex** [comment]
if integrated, this change effectively adds md5/sha1 feature to any other remote

**Comment by ncw** [comment]
> If integrated, this change effectively allows to add md5/sha1 support to any other remote by using `hash_type=md5all/sha1all chunk_size=1P` as described in [#1712 (comment)](https://github.com/rclone/rclone/issues/1712#issuecomment-541395548)

That is very interesting and a really useful addition. When wrapping a crypt remote the would be leaking the hash of the unencrypted file wouldn't it?

I've had a skim over the code and i think it looks great - I'll merge it now in time for 1.50 - thank you :-)

I've got a couple of release blockers for v1.50.  Once is the whole[ go1.12 vs go1.13 regression which is possibly caused by http2](https://forum.rclone.org/t/1-49-4-plex-internal-errors-on-google-drive/12108) - your thoughts on that would be appreciated!

The other is the [--files-from issue](https://github.com/rclone/rclone/issues/3619) which I have a good idea what the problem is.

And finally - would you like to be an rclone maintainer and owner of the chunker/mailru backends?  If so drop me an email to nick@craig-wood.com from your preferred email address and we can discuss - thank you!

**Comment by ivandeex** [comment]
> That is very interesting and a really useful addition. When wrapping a crypt remote the would be leaking the hash of the unencrypted file wouldn't it?
It creates a small encrypted sidecar file with hashsum. I described it in the docs https://github.com/rclone/rclone/blob/master/docs/content/chunker.md#hashsums
No leakage - the sidecar is NaCl-crypted even though it's tiny.
> And finally - would you like to be an rclone maintainer and owner of the chunker/mailru backends? If so drop me an email to [nick@craig-wood.com](mailto:nick@craig-wood.com) from your preferred email address and we can discuss - thank you!
Sent out.

**Comment by ncw** [comment]
> > That is very interesting and a really useful addition. When wrapping a crypt remote the would be leaking the hash of the unencrypted file wouldn't it?
> 
> It creates a small sidecar file with hashsum for each original file. I described it in [the docs](https://github.com/rclone/rclone/blob/master/docs/content/chunker.md#hashsums) (hashsum section)
> No leakage - the sidecar is NaCl-crypted thanks to crypt overlay even though it's tiny.

Of course it is encrypted - I should have thought that through a bit more.

> > And finally - would you like to be an rclone maintainer and owner of the chunker/mailru backends? If so drop me an email to [nick@craig-wood.com](mailto:nick@craig-wood.com) from your preferred email address and we can discuss - thank you!
> 
> Sent out.

:-) Will reply shortly

**Pull request merged**
