### PR TITLE
Add instructions in how to mount remotes as network shares in Windows

### PR DESCRIPTION
**Pull request by ferferga**
Provided instructions for mounting remotes as network shares/network drives in a Windows environment

This PR adds the proper documentation to explain Windows users how to mount rclone remotes as network shares, as discussed [in the forums](https://forum.rclone.org/t/mount-as-network-drive-in-windows/7341)

### CODE REVIEW

**Comment by ncw** [comment]
That looks great thank you - I'll merge it now

**Comment by ferferga** [comment]
Great, thank you very much!

**Comment by ferferga** [comment]
Good afternoon again!

I needed to check some mount commands in the docs and I found nothing about mounting rclone as a network drive. Looked for docs in master and seems that my changes aren't there as well.
There was a branch confusion that overwrote my commit maybe?

**Comment by ncw** [comment]
@ferferga Oh, I see what happened. The file you patched is auto generated...

I'm going to write some comments into the docs/content/command files saying they are auto generated.

I see I've made this mistake (merging patches to auto generated files) a few times so I'm going to rescue the help text that has been overwritten.

Thanks very much for pointing this out.

The docs will be restored when I make a 1.51.1 release.

**Comment by ferferga** [comment]
No problem, thank you very much to you for such a great tool! 

Keep up the hard work!

**Pull request merged**
