### PR TITLE
protondrive: fix bug in digests parsing

### PR DESCRIPTION
**Pull request by henrybear327**
**For Beta testers: Please remove all the files you have uploaded using rclone before trying this version! The bug in the digests parsing and uploading logic is a breaking change**
---

#### What is the purpose of this change?

To address the [signature verification issue](https://github.com/rclone/rclone/issues/6072#issuecomment-1646749246) and the digests parsing bug discovered along the way.

#### Was the change discussed in an issue or in the forum before?

Yes

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by henrybear327** [comment]
@ncw When the PR is merged, we need to make the following announcement to the rclone testers :( Sorry.

> For Beta testers: Please remove all the files you have uploaded using rclone before trying this version! The bug in the digests parsing and uploading logic is a breaking change

**Comment by ncw** [comment]
If you want to build binaries for users to test, you can push this to a named branch on rclone/rclone. This will build binaries in beta.rclone.org/branches

> @ncw When the PR is merged, we need to make the following announcement to the rclone testers :( Sorry.
> 
> > For Beta testers: Please remove all the files you have uploaded using rclone before trying this version! The bug in the digests parsing and uploading logic is a breaking change. Thank you!

No worries - that is why we have a beta test! Much more painful after it hits a release.

If this was after the release I'd get you to make rclone give a warning, but we don't need to bother just yet.

Feel free to merge this yourself when ready :--)

**Comment by henrybear327** [comment]
> If you want to build binaries for users to test, you can push this to a named branch on rclone/rclone (eg `pr-7164-protondrive` - one of these days I will get round to making PRs from maintainers build binaries automatically...). This will build binaries in beta.rclone.org/branches
> 

Thanks for the instructions! I will try this once I am ready with my changes!

> > @ncw When the PR is merged, we need to make the following announcement to the rclone testers :( Sorry.
> > > For Beta testers: Please remove all the files you have uploaded using rclone before trying this version! The bug in the digests parsing and uploading logic is a breaking change. Thank you!
> 
> No worries - that is why we have a beta test! Much more painful after it hits a release.

Good to know! Big relief to me! 

> 
> If this was after the release I'd get you to make rclone give a warning, but we don't need to bother just yet.
> 
> Feel free to merge this yourself when ready :--)

Got it! There are one more issue that I will be addressing - signature verification error - and then I will start the testing, deploying to beta users, and then merging process!

Have a nice day!

**Comment by henrybear327** [comment]
I will try to create a new beta build after I merge the last pending branch tonight! 
cc: @ncw

**Pull request merged**
