### PR TITLE
20230701 onlime backend

### PR DESCRIPTION
**Pull request by Fjodor42**
#### What is the purpose of this change?

Implement a Jottacloud-based backend for Onlime (https://onlime.dk), which recently moved to their own servers, after selling support and access to Jottacloud proper.

#### Was the change discussed in an issue or in the forum before?

Not to my knowledge

#### Checklist

- [X] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [ ] I have added tests for all changes in this PR if appropriate.
- [X] I have added documentation for the changes if appropriate.
- [X] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [X] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Review by ncw — COMMENTED** [review]
Thank you for doing this :-)

This seems to be missing the actual changes to add Onlime in `jottacloud.go`?

Also can you drop the changes to MANUAL.* and rclone.1 - these are auto generated so we don't need to change them in this commit.

**Comment by Fjodor42** [comment]
Well, that was embarrassing - thank you for catching it, @ncw :-$

Actual code change added, and requested reverts done.

**Review by ncw — APPROVED** [review]
Looks perfect now - thank you

**Comment by ncw** [comment]
Thank you :-)

**Pull request merged**
