### PR TITLE
Add an extra step in doc:google-drive to proceed correctly.

### PR DESCRIPTION
**Pull request by jcguu95**
* This is to fix this issue: https://github.com/rclone/rclone/issues/5435#issuecomment-873985284

#### Checklist

- [X] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [X] I have added tests for all changes in this PR if appropriate.
- [X] I have added documentation for the changes if appropriate.
- [X] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [X] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by animosity22** [comment]
There are two paths for getting your own client ID.

Breaking down the two paths:

Non GSuite User:
- User type must be external as you cannot pick internal
- If you are using testing, you must add the users to the test group:
image
- If you hit publish and push to production, most likely that will work as well as there aren't any other changes that most users will make, it just works so it feels like this  would work generally

If you are a GSuite user:
- You can pick external following the same flow above
- If you pick internal (only users on the same gsuite domain can use it), you don't need to publish (that's what I use)

@jcguu95 - let me know if you want to touch up that to cover that as that's how it seems like the process works now. Let me know if you have a different flow.

**Comment by jcguu95** [comment]
Ah. Thanks for providing those information.

I'm no GSuite user, and dunno if I can say that's right. I'm just adding the extra step that worked for me (and another dude on the forum). Perhaps someone else should make the PR?

**Comment by ncw** [comment]
If between you, you can come up with some wording, I can mash it into the PR :-)

**Comment by ivandeex** [comment]
@animosity22 @jcguu95 
Do you think you can come to agreement by **this** christmas?

**Comment by ivandeex** [comment]
Closed due to total inactivity

**Pull request closed without merging**
