### PR TITLE
feat: add onedrive make direct link feature

### PR DESCRIPTION
**Pull request by septs**
#### What is the purpose of this change?

Export direct download link

#### Was the change discussed in an issue or in the forum before?

No

https://github.com/rclone/rclone/issues/3930

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by septs** [comment]
@ncw

**Comment by septs** [comment]
(Next a Pull request, implementation #3930)

**Comment by Cnly** [comment]
First of all thanks for your work :) I have two comments on this PR:

First is that flags beginning with `--drive-` are usually Google-Drive-specific. If multiple backends support this operation we can consider a more general name.

Next, I'm not sure if `@microsoft.graph.downloadUrl` will be what most users expect, since that link is [only valid for an hour](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/driveitem?view=odsp-graph-online#instance-attributes). An alternative (but hacky) approach is the transformation exemplified below:

If you get the public link of an item in the form of `https://contoso-my.sharepoint.com/:p:/g/personal/you_contoso_org/verylongandopaquestring` and transform it to `https://contoso-my.sharepoint.com/personal/you_contoso_org/_layouts/15/download.aspx?share=verylongandopaquestring`, this new link is directly downloadable and doesn't have the one-hour limit.

I don't think this is something documented so I can't guarantee it'll work forever, but personally I think it has been fairly stable.

**Comment by septs** [comment]
OK
1. `--drive-direct-link` to `--direct-link` (general)
2. Timeliness this is a design, We should follow the designed usage (use-case)

**Comment by ncw** [comment]
This looks like exactly what should be returned from the `PublicLink` interface - not sure why we need a new `DownloadLink` interface. Can you explain your reasoning @septs ?

Thanks!

**Comment by septs** [comment]
@ncw 
`PublicLink` method based, onedrive `createLink` method
the method is create a sharing link (official share page)
see https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createlink

`DownloadLink` method based, onedrive `DriveItem` object - `@microsoft.graph.downloadUrl` field
generated direct download link without token
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/driveitem#instance-attributes

**Comment by septs** [comment]
image

**Comment by ncw** [comment]
I see!

The docs for PublicLink() say "PublicLink generates a public link to the remote path (usually readable by anyone)" so maybe we should change the implementation of PublicLink in the onedrive backend to be your new DownloadLink code?

What do you think?

**Comment by septs** [comment]
@ncw This is definitely break semantics.
see Google Drive implementation
see #3930

**Pull request closed without merging**
