### PR TITLE
Contributing squashing

### PR DESCRIPTION
**Pull request by jtagcat**
#### What is the purpose of this change?

Add how-to-squash. A few months ago, I couldn't get my head around git. Why not just have it there?

#### Was the change discussed in an issue or in the forum before?

No.

#### Checklist

- [x] I have totally not read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] ~I have added tests for all changes in this PR if appropriate.~
- [x] I have added documentation ~for the changes if appropriate.~
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ncw** [comment]
I think it is a great idea to have this in the docs.

Just wondering why you used that workflow? I think most people would use `git rebase -i origin/master` which is quite a bit simpler?

**Comment by jtagcat** [comment]
> Just wondering why you used that workflow? I think most people would use `git rebase -i origin/master` which is quite a bit simpler?

I think my way makes more sense, but change instructions as you see fit.

**Comment by ncw** [comment]
I guess simpler is in the eye of the beholder!

I'll merge what you've done as being more beginner friendly.

I like your cheeky shoutout to wizardzines ;-)

**Comment by jtagcat** [comment]
I was thinking for 1-2m if I should remove the advertising...

**Pull request merged**
