### PR TITLE
swift: support copying large objects

### PR DESCRIPTION
**Pull request by nguyenhuuluan434**
#### What is the purpose of this change?

The max size object in swift is 5G, if we copy object what greater than 5G (large object) the operation will fail.

#### Was the change discussed in an issue or in the forum before?

I run test local.

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ ] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by nguyenhuuluan434** [comment]
If we use the server side copy, in the case object what has size greater 5G, the request will raise error "Too Large Object"

**Comment by nguyenhuuluan434** [comment]
Hi @ivandeex ,
The check "xgo cross compile" fail with error "error writing go.mod: open /ext-go/1/src/github.com/rclone/rclone/go.mod789296422.tmp: read-only file system". Do you have any advice to solve it?

Thank,
Luan

**Comment by ivandeex** [comment]
It was introduced by commit https://github.com/rclone/rclone/commit/e5aa92c9222d8d999c9bd0a20c2b6074aab43f5a
It affects all later PRs. We'd better correct it right on master.
If you don't want to wait, run `go mod tidy` on your local copy (it will swap some go.mod lines) and add to your commit.

**Comment by ivandeex** [comment]
please mark as ready for review when you are done with the checklist, tests and docs, and integration tests pass

**Comment by nguyenhuuluan434** [comment]
Hi @ivandeex ,
Please, help me review the PR.
Thanks,
Luan

**Comment by ivandeex** [comment]
I would love to see two things:
- A new unit test in [swift_test.go](https://github.com/rclone/rclone/blob/v1.54.1/backend/swift/swift_test.go#L23) or [swift_internal_test.go](https://github.com/rclone/rclone/blob/v1.54.1/backend/swift/swift_internal_test.go#L11) that _passes_ with the main patch applied and _fails_ otherwise
- A comment in [swift.md](https://github.com/rclone/rclone/blob/v1.54.1/docs/content/swift.md#limitations) regarding large objects: do they still show up with size 0 in listings? is copying now fully supported or still has (less) limitations?

**Comment by nguyenhuuluan434** [comment]
Hi @ivandeex ,
The purpose of this PR to fully support for large object what include the source object is DLO or DLO.
The steps:
+ check type of source object what is large object (DLO or SLO) or normal.
+ if the source is normal object, we will call copy by old flow.
+ if the source is large object, we try to get segments what belongs to the manifest. and copy segments individually. After coping segment was done, we create manifest. [advice in swift api](https://github.com/openstack/swift/blob/master/swift/common/middleware/copy.py#L105)

Thanks,
Luan.

**Review by ncw — COMMENTED** [review]
I think the code is looking great thanks :-)

Can you have a go at a test please?

This should be in swift_test.go, put another test function here

https://github.com/rclone/rclone/blob/f76c6cc8931c7574a21b5ff7d03ae4ab82f59dcb/backend/swift/swift_test.go#L78-L83

What you should do is upload a small segmented file, copy it then check the copy is OK. It shouldn't be too hard - let me know if you need any help.

**Comment by nguyenhuuluan434** [comment]
@ncw
I added ```testCopyLargeObject```, reuse code of ```testWithChunk``` to upload and call copy after that.
Please help me review.
Thanks.

**Comment by nguyenhuuluan434** [comment]
Hi @ncw just remind.

**Review by ncw — APPROVED** [review]
Thanks for writing a test :-)

I think this looks good now and I will rebase it, squash it and merge!

**Comment by ncw** [comment]
Thank you for this code - very useful. It is merged for v1.55 now :-)

**Pull request merged**
