### PR TITLE
jottacloud: add no versions option

### PR DESCRIPTION
**Pull request by buengese**
This is another one of those annoying workaround. Currently, Jottacloud doesn't provide a way to delete old versions of files via the API and no such option exists in the web ui either. This means the only way to remove old versions from the file is to completely delete. Since old versions obviously count against your quota, they can get rather annoying. This pr adds an option to avoid any server side versioning by deleting old files before uploading a new version.

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by albertony** [comment]
Nice.
Is there a risk worthy a doc warning or something, that the file may be "lost" from the destination if something bad happens? I mean after deleting existing file but before copying the new file, e.g. if it bails out on "failed to calculate MD5"? I don't know, just a thought..

**Comment by buengese** [comment]
I think that's pretty minor risk, since it's not like rclone is going to ever delete the source files unless the transfer succeeded. Though better safe than sorry. I'll add a short warning in the docs.

**Comment by ncw** [comment]
> I think that's pretty minor risk, since it's not like rclone is going to ever delete the source files unless the transfer succeeded. Though better safe than sorry. I'll add a short warning in the docs.

I think that is probably a good idea.

If you were feeling very paranoid you could rename the old file to .TEMP and delete it or rename it back if successful/unsuccesfull.

I don't think that is necessary though provided we put the warning in the docs.

**Comment by albertony** [comment]
> If you were feeling very paranoid you could rename the old file to .TEMP and delete it or rename it back if successful/unsuccesfull.

Another positive side of this approach is that it would take advantage of deduplication. With the existing approach, permanent delete followed by upload, it is more likely resulting in entire content having to be uploaded.

What I have found is that a simple copy, i.e. server-side copy, will not include the revisions. One could therefore instead upload to .TEMP, then permanent delete target, then rename .TEMP to target. Result will be the same - no revisions on resulting target. But I guess no big advantages from former approach either: 1 rename + 1 delete + 1 upload (when everything succeeds).

> I don't think that is necessary.

No, probably not. The downside of these two approaches is complexity (e.g. with upload/rename to .TEMP - what if .TEMP already exists?), and also if you are near your quota then replacing a huge file could (depending on deduplication) count twice for the short time before original is deleted.

So... Sorry for the "bump". Primarly just wanted to "record" the finding of copy not including revisions. 😊

**Pull request merged**
