### PR TITLE
Improve explanation of windows filesystem permissions

### PR DESCRIPTION
**Pull request by albertony**
#### Was the change discussed in an issue or in the forum before?

#6758

#### Checklist

- [X] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [ ] I have added tests for all changes in this PR if appropriate.
- [X] I have added documentation for the changes if appropriate.
- [X] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [X] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ElDavoo** [comment]
Looks good, you were faster than me

**Comment by albertony** [comment]
Oh, excuse me if you had already started on it! I found that the existing text in that section was a bit messy and started something of a rewrite immediately without considering if you were going to work on adding the note from the other issue. I appreciate if you have any suggestions to improvement, or spot any typos, though.

**Comment by ElDavoo** [comment]
no worries, it's for sure much better than what i was writing

**Review by ncw — APPROVED** [review]
Super job - well done :-)

Please merge when ready.

**Pull request merged**
