### PR TITLE
Jottacloud: bring back old authentification for whitelabel versions

### PR DESCRIPTION
**Pull request by buengese**
As discussed in #4299.

### CODE REVIEW

**Comment by buengese** [comment]
Beta available [here](https://beta.rclone.org/branch/v1.52.1-053-gdc24ccc9-jotta-legacy-auth-beta/)
I don't have access to any of the Jottacloud whitelabel versions so it would be great if @Krakkan83 could give this a quick test.

**Comment by Krakkan83** [comment]
I get the white label warning when editing remote so that works fine, i then get the text message with auth code after entering username and password however there is an error after typing in credentials so i can't type in the auth code:
:2020/06/11 13:58:54 Failed to get oauth token: HTTP error 400 (400 Bad Request) returned body: "{\"error\":\"invalid_client_or_otp_missing_or_wrong\",\"error_description\":\"Client authentication failed (e.g., unknown client, no client authentication included, unsupported authentication method, or the resource owner has enabled OTP and the otp code is not supplied in the password grant request or the supplied otp code is wrong).\"}"

The same with adding a new remote, so the sms code works and gives me a code but i can't type it in as rclone exits with the above error. Hope this was the right place to type this.

**Comment by buengese** [comment]
Ah I see. I forgot about the otp stuff.

**Comment by buengese** [comment]
[new beta](https://beta.rclone.org/branch/v1.52.1-054-g92142d73-jotta-auth-beta/)

**Comment by Krakkan83** [comment]
Works now! 👍

**Comment by CHRONiCiTY** [comment]
This works for me as well using Com Hem Cloud. Thanks!

**Comment by ncw** [comment]
Great work! Is this ready to be merged now?

**Comment by Krakkan83** [comment]
I got another issue now with authentication and mount fails after some time:
2020/06/11 18:51:08 Failed to create file system for "****:": failed to make remote ****:"****" to wrap: couldn't get customer info: Get "https://api.jottacloud.com/account/v1/customer": couldn't fetch token - maybe it has expired? - refresh with "rclone config reconnect ****:": Post "https://id.jottacloud.com/auth/realms/jottacloud/protocol/openid-connect/token": dial tcp: i/o timeout
2020/06/11 18:52:06 Failed to create file system for "****:": failed to make remote ****:"****" to wrap: couldn't get customer info: Get "https://api.jottacloud.com/account/v1/customer": couldn't fetch token - maybe it has expired? - refresh with "rclone config reconnect Krakkan:": oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"unauthorized_client","error_description":"INVALID_CREDENTIALS: Invalid client credentials"}

**Comment by buengese** [comment]
Was kinda waiting for this to happen. Thats why I hadn't merged this yet. This kinda looks like these whitelabel versions are handled by servers running older software that still retains bugs that had allready been fixed for the main Jottacloud version. Fix and a third beta in a few minutes.

**Comment by buengese** [comment]
[Third beta](https://beta.rclone.org/branch/v1.52.1-054-g4df0406f-jotta-auth-beta/) I'm not expecting anymore problems after this so if this works for you I'm going to merge this.

**Comment by CHRONiCiTY** [comment]
I also encountered the invalid credentials problem. Strangely enough it also affected my Jottacloud-account. With this third beta everything looks good so far.

**Comment by ncw** [comment]
Do you want this fix to go in a point release @buengese ? It is quite a big change though. Maybe we could leave it to cook in the beta for a bit and see what the demand is?

**Comment by buengese** [comment]
I'd prefer not to. I don't think there is that much demand and this being jottcloud it's entirely possible that something else break before the next release.

**Comment by ncw** [comment]
> I'd prefer not to. I don't think there is that much demand and this being jottcloud it's entirely possible that something else break before the next release.

Sounds good to me. I'll leave it out.

**Pull request merged**
