### PR TITLE
drive: add support of SHA-1 and SHA-256 checksum

### LINKED ISSUE #7327: Add support to Google Drive's SHA-1/SHA-256 checksum
#### What is your current rclone version (output from `rclone version`)?

```
rclone v1.64.0
- os/version: darwin 14.0 (64 bit)
- os/kernel: 23.0.0 (arm64)
- os/type: darwin
- os/arch: arm64 (ARMv8 compatible)
- go/version: go1.21.1
- go/linking: dynamic
- go/tags: none
```

(Installed from Homebrew)

#### What problem are you are trying to solve?

in 2022/08, Google adds `sha1Checksum` and `sha256Checksum` fields to Google Drive API v3.
src (warning: really big commit): https://github.com/googleapis/google-api-go-client/commit/7158b896335d4f986ae6a3624955b5c1e7c1f51a#diff-eec56ddbef94122b30ec863bfa9f9f1abbda87ac35232b0feaec633d18aa3bec

It provides SHA-1 And SHA-256 checksums, but currently rclone doens't support that, like:

```
$ rclone hashsum md5 gsuite:empty
d41d8cd98f00b204e9800998ecf8427e  empty
$ rclone hashsum sha1 gsuite:empty
2023/09/22 07:51:54 ERROR : empty: hash unsupported: hash type not supported
2023/09/22 07:51:54 Failed to hashsum with 2 errors: last error was: hash unsupported: hash type not supported
$ rclone hashsum sha256 gsuite:empty
2023/09/22 07:52:00 ERROR : empty: hash unsupported: hash type not supported
2023/09/22 07:52:00 Failed to hashsum with 2 errors: last error was: hash unsupported: hash type not supported
```

#### How do you think rclone should be changed to solve that?

Add sha1Checksum and sha256Checksum to Google Drive backend implementation.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

### PR DESCRIPTION
**Pull request by rinsuki**
#### What is the purpose of this change?

```
$ ./rclone hashsum md5 gsuite:empty
d41d8cd98f00b204e9800998ecf8427e  empty
$ ./rclone hashsum sha1 gsuite:empty # Previously not supported
da39a3ee5e6b4b0d3255bfef95601890afd80709  empty
$ ./rclone hashsum sha256 gsuite:empty # Previously not supported
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  empty
```

#### Was the change discussed in an issue or in the forum before?

Fix #7327 

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [ ] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Review by ncw — COMMENTED** [review]
This looks nice - I'll run the CI in a moment.

It needs a patch to docs/content/overview.md ( https://rclone.org/overview ) in the summary table

Are we sure that this is supported by all objects, even ones uploaded a very long time ago?

I guess if they return as blank then rclone will do the right thing.

**Comment by rinsuki** [comment]
> It needs a patch to docs/content/overview.md ( https://rclone.org/overview ) in the summary table

Fixed!

> Are we sure that this is supported by all objects, even ones uploaded a very long time ago?

I'm not sure about very old files (like 2012), but files uploaded in 2018 seems fine.

**Review by ncw — APPROVED** [review]
This looks great :-)

I tested on my personal drive which I've had for a long time.

Out of 1606 files on my drive, 382 are missing SHA1 and 421 SHA256. They all have MD5s though.

I looked through the dates when these were uploaded and it is all a bit inconsistent. Most of these were uploaded in 2017 or before so that is probably the cutoff. There are 4 files with missing checksums uploaded later than that though including one file uploaded on 2022-06-22 with no SHA1 or SHA256 which is weird.

I think this deserves a note in the docs. Can you make a `Hashes` section in the google drive docs (`docs/content/drive.md`) [like this one from s3](https://rclone.org/s3/#hashes).

We need to say that all files have MD5 hashes, but a small fraction of files uploaded may not have SHA1 or SHA256 hashes especially if they were uploaded before 2018.

Something like that!

Here is how I did my analysis

```
rclone --drive-skip-shortcuts --drive-skip-gdocs hashsum sha1 drive:  | grep '^ ' | sort > missing.sha1
rclone --drive-skip-shortcuts --drive-skip-gdocs hashsum sha256 drive:  | grep '^ ' | sort > missing.sha256
rclone --drive-skip-shortcuts --drive-skip-gdocs size drive:
rclone lsl --files-from <(sed 's/^[ \t]*//' <missing.sha256) drive: > missing.sha256.files
rclone lsl --files-from <(sed 's/^[ \t]*//' <missing.sha1) drive: > missing.sha1.files
cut -c11- missing.sha256.files | sort > missing.sha256.files.sorted 
cut -c11- missing.sha1.files | sort > missing.sha1.files.sorted 
```

**Comment by rinsuki** [comment]
> I think this deserves a note in the docs. 

Added!

**Review by ncw — APPROVED** [review]
Looks great - thank you :-)

Will merge now.

**Pull request merged**
