### PR TITLE
s3/v2Auth: copy multipart failed with 'SignatureDoesNotMatch'

### PR DESCRIPTION
**Pull request by zhucan**
Signed-off-by: zhuc <zhucan.k8s@gmail.com>

#### What is the purpose of this change?
s3/v2Auth: copy multipart failed with 'SignatureDoesNotMatch'

#### Was the change discussed in an issue or in the forum before?

#4961 

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [ ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ ] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by zhucan** [comment]
@ncw  how to retest?

**Review by ncw — APPROVED** [review]
This looks great - thank you :-)

I'll merge it now.

**Comment by ncw** [comment]
PS the test failure was not connected

**Pull request merged**
