### PR TITLE
azureblob: allow emulator account/key override

### PR DESCRIPTION
**Pull request by roelarents**
#### What is the purpose of this change?

In #3285 support for `azureblob` was added. In #6290 the option was added to override the endpoint. This adds the option to override the account name and key also.

Note: this could be regarded backwards incompatible. E.g. for people who keep their production credentials in the config but only switch `use_emulator` on and off. In which case an attempt would be made to authorize with the emulator with wrong credentials.

#### Was the change discussed in an issue or in the forum before?

I couldn't find any mentions of it.

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [ ] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Review by ncw — COMMENTED** [review]
This change looks good to me.

> Note: this could be regarded backwards incompatible. E.g. for people who keep their production credentials in the config but only switch use_emulator on and off. In which case an attempt would be made to authorize with the emulator with wrong credentials.

How likely do you think that is? I guess maybe a note in the docs saying prior to v1.60 that rclone ignored the account and key would at least document it?

**Comment by ncw** [comment]
Agreed! Do you want to add the note in this PR?

**Comment by roelarents** [comment]
Where should I put it exactly? I've added it in the azureblob docs now, in the emulator paragraph at the bottom.

**Comment by roelarents** [comment]
By the way: instead of the additional `use_emulator` I would actually prefer that the full `endpoint` could be overridden. That saves an extra parameter in e.g. a production/test situation where the connection parameters are switched with config.

It would be backwards incompatible, because the `endpoint` param is [now interpreted as](https://github.com/rclone/rclone/blob/master/backend/azureblob/azureblob.go#L688) (part of) the hostname for the full endpoint url, i.e. `blob.core.windows.net`. Unless testing the endpoint parameter for starting with `http` (new style) or not (backwards compat)?

**Comment by roelarents** [comment]
What can I do to get this in the next release?

**Comment by roelarents** [comment]
Good one :). Thanks, no problem, I can see rclone keeps you very busy. (Which makes me happy, I used it to abstract away from 3 backends already.) The 1.60 mention has been updated. I will put the endpoint thing in another PR. We can see then if it's desirable at all.

**Review by ncw — APPROVED** [review]
Great - thank you :-)

Will run through the CI then merge if it goes green.

**Comment by ncw** [comment]
Thank you :-)

**Pull request merged**
