### PR TITLE
crypt: add --crypt-filename-compression option to compress unicode filename before encryption (WIP)

### PR DESCRIPTION
**Pull request by Milly**
**WIP** now. Please advice to this feature.
I will combine the commits into one later.

#### What is the purpose of this change?

Filename encryption inflates its length.
Some remote backends has a limitation of the filename length that counted by *characters* (not bytes).
So, if it contains multi-bytes characters in UTF-8, the filename length was not problematic in the remote can be a problem in the crypt backend.

If remote backend has 255 characters limit.  "standard" mode has limits below.

* ASCII (7bits, 1byte/char) ~143 characters **limited**
* Alphabetic (Latin, Cyrillic, etc., 2bytes/char) ~71 characters **big limited**
* East-Asian (CJK, 3bytes/char) ~47 characters  **extremely limited**
                                                                         
If `--crypt-filename-compression` option is enabled, the filename is compressed by [SCSU (Standard Compression Scheme for Unicode)](https://en.wikipedia.org/wiki/Standard_Compression_Scheme_for_Unicode) before encryption.
This feature allows non-ASCII file names to be stored up to the same length as ASCII file names.

#### Was the change discussed in an issue or in the forum before?

The problem of filename length has been discussed a lot.
However, it seems that the problem extremely limited in East Asian characters has not been discussed.

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [ ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [ ] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ivandeex** [comment]
Related to _crypt: add option to not encrypt data_ #1077 #2981

**Comment by Milly** [comment]
Currently CI failed in go1.12 and earlier, because the [SCSU library](https://github.com/dop251/scsu) uses `errors.Is`.
I'm PRed to it.

**Comment by Milly** [comment]
https://forum.rclone.org/t/filename-too-long/12753

**Comment by ivandeex** [comment]
@ncw
Does the crypt format allow for future extensions?
Is it possible to add a _data format_ marker to a crypt-encrypted value? Like a byte or variadic integer meaning e.g. 1="encrypted bytes", 2="SCSU-compressed encrypted bytes", 3-...="reserved"

If a meta-format field is not reserved a.t.m., is there a _currently impossible_ (but valid) combination of `crypt`-stream bits, which can be used to "hack" the field into existing wire format?

If SCSU appears succesful we could default to it in future and decode **automatically** while maintaining backward compatibility. Or "SCSU+" or "encrypted bytes with modtime" or whatever...

**Comment by ivandeex** [comment]
Marking as `breaking change` because older versions of rclone cannot parse new _wire format_ correctly.

**Comment by ncw** [comment]
This is very interesting - thank you.

We've been working on a file name compression scheme based on pre-defined huffman tables using @klauspost 's excellent library.

Currently the scheme uses the first byte of the name to select the huffman table to use - the idea being that we collect distributions of file name characters from users to build some typical huffman tables. The compression is quick enough that we can try all the tables to find the minimum match.

Using SCSU as well sounds ike an interesting idea. Maybe before the huffman coding or on its own.

Do you have a corpus of file names that we could experiment on? It would be interesting to experiment with this vs huffman encoding.

**Comment by Milly** [comment]
The problematic point in that case.
The appropriate corpus depends on the language and users.

**Comment by klauspost** [comment]
This seems to mostly achieve compression by shifting down character codes.

This means it retains codes 32 -> 127 ( plus CR, LF, TAB) as is, but places another set of characters in the "upper" 128->255 part, so they don't take up several bytes. The remaining are used for selecting what should be in the upper window.

It could be interesting to combine this.

**Comment by klauspost** [comment]
@Milly See #4901 - this adds scsu as a compression type that can be selected if it is optimal.  This extends the filename compression I prepared for @ncw

**Comment by ivandeex** [comment]
Marking WIP PRs as draft.

**Comment by Milly** [comment]
Features that use SCSU were merged in #4901.
So close this.
Thank you @klauspost !!

**Pull request closed without merging**
