### PR TITLE
dropbox: add option to override root namespace

### PR DESCRIPTION
**Pull request by wfraser**
#### What is the purpose of this change?

This lets you, for example, use shared folders without mounting them into your home namespace first, as long as you know their namespace ID.

(The --dropbox-shared-folders flag could thus be changed to not need to mount the shared folder first, but I'm not doing that here as it's a behavior change, who knows, maybe somebody relies on it.)

This also allows access to your Dropbox Backups hidden namespace once you figure out what its namespace ID is.

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Review by ncw — COMMENTED** [review]
I think this change looks great thank you.

I'd just like to have a discussion about the naming.

In other backends we have called this feature like this

```
      --box-root-folder-id string          Fill in for rclone to use a non root folder as its starting point
      --drive-root-folder-id string        ID of the root folder
      --filefabric-root-folder-id string   ID of the root folder
      --onedrive-root-folder-id string     ID of the root folder
      --pcloud-root-folder-id string       Fill in for rclone to use a non root folder as its starting point (default "d0")
      --pikpak-root-folder-id string       ID of the root folder
      --sharefile-root-folder-id string    ID of the root folder
```

So I'm tempted to say we should do the same for the dropbox backend too and call this `--dropbox-root-folder-id` to fit in with the rest of rclone.

However dropbox have their very specific naming with namespaces so maybe it isn't a good idea. We could of course write lots of help explaining things.

What do you think?

I'll run the CI now too.

**Comment by wfraser** [comment]
Thanks for the review!

I think calling it "folder ID" here would be more confusing, because it needs to specifically be a namespace ID and not a file/folder ID (which is a different kind of identifier).

**Comment by ncw** [comment]
Thank you :-)

I'll merge this now.

**Comment by 2994dd42d75b0** [comment]
How to find namespace ID of Back in Dropbox?

**Pull request merged**
