### PR TITLE
docs: improve google drive usage information

### PR DESCRIPTION
**Pull request by fzn0x**
Just leaving `remote` is confusing. Modify it to something user must aware of.

### CODE REVIEW

**Comment by albertony** [comment]
I understand this can be confusing, and perhaps we should come up with better naming in the examples. But, in the interactive sequence shown just above your changes the name `remote` is given as input to the `rclone config` command. So therefore, running `rclone lsd remote:` follows naturally from that.

```
No remotes found, make a new one?
n) New remote
r) Rename remote
c) Copy remote
s) Set configuration password
q) Quit config
n/r/c/s/q> n
name> remote
```

Also, this part of the documentation is very similar in many of the backends, so if we are going to change it I think we'll have to do it for all of them.

Perhaps you could create an issue for this instead, where possible improvements can be discussed and agreed upon, before we consider doing changes that affect many of the backend doc pages?

**Comment by fzn0x** [comment]
> I understand this can be confusing, and perhaps we should come up with better naming in the examples. But, in the interactive sequence shown just above your changes the name `remote` is given as input to the `rclone config` command. So therefore, running `rclone lsd remote:` follows naturally from that.
> 
> ```
> No remotes found, make a new one?
> n) New remote
> r) Rename remote
> c) Copy remote
> s) Set configuration password
> q) Quit config
> n/r/c/s/q> n
> name> remote
> ```
> 
> Also, this part of the documentation is very similar in many of the backends, so if we are going to change it I think we'll have to do it for all of them.
> 
> Perhaps you could create an issue for this instead, where possible improvements can be discussed and agreed upon, before we consider doing changes that affect many of the backend doc pages?

We can discuss it here I guess

**Comment by fzn0x** [comment]
I changed it to warning message, someone may ignore the configuration steps after runs `rclone config`.

**Comment by albertony** [comment]
I'm still not sure about this one.

I do agree there can be some confusion around this for newcomers, but my personal opinion is that it is a bit too "noisy" with a warning like the latest change. And all backends use the same "template" for this docs, so an added description like this would have to be in all of them, not only drive.

The section does already start by this short explanation:

> Here is an example of how to make a remote called `remote`.

And also we have the usage docs which users should definitely take a look at first, e.g. the https://rclone.org/docs/#syntax-of-remote-paths section is highly relevant, so its a question how much of this kind of "generic help" we want in the backend docs.

**Pull request closed without merging**
