### PR TITLE
Remove email from authors

### PR DESCRIPTION
**Pull request by psychopatt**
#### What is the purpose of this change?

Just remove my email from authors public page because I get a lot of spam.

#### Was the change discussed in an issue or in the forum before?

Nope, not relevant

#### Checklist

- [ ] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [ ] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Review by ncw — APPROVED** [review]
Looks fine to me :-)

**Comment by psychopatt** [comment]
> Looks fine to me :-)

Thanks ! 😄

**Comment by psychopatt** [comment]
Related question, when does the [website authors page](https://rclone.org/authors/) get updated?

**Comment by ncw** [comment]
At the next release which should be in a week or so.

**Pull request merged**
