### PR TITLE
ftp: update dependency jlaffaye/ftp

### PR DESCRIPTION
**Pull request by ivandeex**
#### What is the purpose of this change?

Recently jlaffaye/ftp accepted patches that fix two outstanding issues:
- https://github.com/jlaffaye/ftp/pull/219 (trim trailing whitespace from the list commands)
- https://github.com/jlaffaye/ftp/pull/221 (Fix STOR of zero length files to ProFTPd with TLS)
This PR makes rclone's `go.mod` pull the patched library

#### Was the change discussed in an issue or in the forum before?

#1850 (FTP: 500 'LIST ': command not understood)
https://forum.rclone.org/t/rclone-ftps-explicit-rclone-touch-empty-files-proftpd-unable-to-build-data-connection-operation-not-permitted/22522/15

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ivandeex** [comment]
code quality test is broken until someone reviews #5093

**Comment by ivandeex** [comment]
I am in doubt whether this needs new unit tests. I think, rather not.

**Review by ncw — APPROVED** [review]
In an ideal world we'd set up ProFTP with TLS certs in the integration test server, but that is too much work I think.

So I think we should merge this as-is :-)

Thanks

**Comment by ivandeex** [comment]
Or setup a Solaris machine with an ancient FTPd. Thanks for not requesting this.

**Pull request merged**
