### PR TITLE
smb backend: Check if the connection is closed

### PR DESCRIPTION
**Pull request by happyxhw**
#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by happyxhw** [comment]
https://github.com/rclone/rclone/blob/master/backend/smb/connpool.go#L222
```
	for i, c := range f.pool {
		if !c.closed() {
			cErr := c.close()
			if cErr != nil {
				err = cErr
			}
		}
		f.pool[i] = nil
	}
```
After `--smb-idle-timeout` smb conn pool check the connection should be closed, everytime it removes the from the pool, but not closed, causing two many unused connection to smb server.

**Review by albertony — APPROVED** [review]
Good catch - your fix looks correct to me!

**Comment by albertony** [comment]
@Lesmiscore do you agree?

**Review by Lesmiscore — APPROVED** [review]
Yes.

**Comment by albertony** [comment]
Great, let's just merge it then. Thank you @happyxhw for your contribution!

**Pull request merged**
