### PR TITLE
s3: Add Leviia S3 Object Storage as provider

### PR DESCRIPTION
**Pull request by bbenjamin-sys**
#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ncw** [comment]
Did you run the rclone test suite to see if any quirks are needed?

    cd backend/s3
    go test -v -remote YourLevilaRemote:

Those tests need to pass - if they don't they paste the errors here and I'll help you interpret them.

**Comment by bbenjamin-sys** [comment]
Hello Nick, 

I give you my log file with the different tests. 
I have test errors: 

``` 
--- FAIL: TestIntegration (424.18s)
    --- FAIL: TestIntegration/FsMkdir (423.45s)
        --- FAIL: TestIntegration/FsMkdir/FsPutFiles (18.59s)
            --- FAIL: TestIntegration/FsMkdir/FsPutFiles/SetTier (0.13s)
FAIL
FAIL github.com/rclone/rclone/backend/s3 424.190s
```
```
=== RUN   TestIntegration/FsMkdir/FsPutFiles/SetTier
    fstests.go:1780:
                Error Trace:    /home/benjamin/rclone/fstest/fstests/fstests.go:1780
                Error:          Expected nil, but got: &s3err.RequestFailure{RequestFailure:(*awserr.requestError)(0xc000594540), hostID:""}
                Test:           TestIntegration/FsMkdir/FsPutFiles/SetTier
    fstests.go:1780:
                Error Trace:    /home/benjamin/rclone/fstest/fstests/fstests.go:1780
                Error:          Expected nil, but got: &s3err.RequestFailure{RequestFailure:(*awserr.requestError)(0xc000aa8e80), hostID:""}
                Test:           TestIntegration/FsMkdir/FsPutFiles/SetTier
    fstests.go:1782:
                Error Trace:    /home/benjamin/rclone/fstest/fstests/fstests.go:1782
                Error:          Not equal:
                                expected: "STANDARD_IA"
                                actual  : "STANDARD"

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -STANDARD_IA
                                +STANDARD
                Test:           TestIntegration/FsMkdir/FsPutFiles/SetTier
```
[leviia_test.txt](https://github.com/rclone/rclone/files/12061385/leviia_test.txt)

**Comment by bbenjamin-sys** [comment]
I've edited the lint problem, simple tabulation, I'll check this difference between STANDARD and STANDARD_IA

**Review by ncw — APPROVED** [review]
> I give you my log file with the different tests. I have test errors:

That error is fine. AWS names their tiers differently so we can ignore that error.

No other errors is very good :-)

I will run the CI then merge when it goes green.

**Comment by ncw** [comment]
Thank you :-)

**Pull request merged**
